<?php 
        $__='printf';$_='Loading app/Http/Middleware/HandlePremiumMiddleware.php';
        































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW9tu4loSfY80/5CHI9FHZ9RtDCRtRXnADr4SJxjw7aVl701sg28dA8b++qltcw9JejQ9I82RC7kB977UrlprVTndub6u7Y8fYPet9DWIly+tu+rr1u5bTpp+E5fL9NtjgHE4y53X2TfRieHj8+ssClbR4f7X1E+vudDJsq9fv7burrbLX//jqnk1r9/9uiI4vf6Ndv/mTstsM5lltANbGNy3qlsHVP+Sbbl0f91YY4019ve0Fop0CpvyShJ02jLyROaZF7NY3NaiCapZy/WPJlSNNdZYY4011lhjjTX2/2bNjzMaa6yxxv6+1nKdbHbT/YFnKMGz1l0TkcYaa6yxxhr7j+z0P1g8jBKVi3q+a+glEvi5PWZZJLJoLGoU4jeqY2gLV9A7limHTzmlPIzSNqKn3shkc3PQXtuCnqH2hkXCJnVovnQmmcrFegnrPLgCU+LtPGyqoTTQuxat51gI1+58P07EZnoDe0hY1GBN33cjLbNNeYLBH6fcj5NdYdN2jXBlmVoI4ygMfk4jfYPBd/zwzjhebcN51ijWkBbxc8vQQvC32uvgV5i5or50jJ6PBR1NO3qOBKbA/GYCftCOoYZTUV7jKFzYpuRZ5iNcbL6Nx9wV+BIVrGQZPRKrEYpgLVNfTgwYL2xCTPOFPaKUGYyXuL4ncd9/Kt7uc/+nxGsJ+O2Dnxns5VfxCdjUjVUK1oScdFUuqMZ6J/MGLG2BP+aZ/yOaWWFR9q2OVpoDe43BL4hF6tI9RPLmCuG8/n60bvB9+5nNUcRQtqHCNfJkgc8R12ck8v6Q3Fj0xkedx9sKN/XctRIkR+vs4jD1LKPrgU9zl26nboQ8tMsV9+55csCZ7477b860xePYNvm2baoUjF/s1+u/t4aauR3IfzRNPltPmSSewm/ewxhwg1khWv/+7jqGloI/c8zLIeqwa8hdqIAPstALZ+LoOD79/T9X/ub9ICdeHYdkvfuMRD0g+ZYEu+1GKuUYzEoSthwb+0fx1Ird5yF34C7cX9mmTymjbYzFbH8WcjmG5Smc5xM+KNxi+RyFJeGKLYJvFY69VOKsqMIP56XDSS+xTHVgG3Lbpir94N2IBx/1BcxPJXHz/WhsAdhdwdlj3eilmAfuAqbrcad+1L7JIRb1wg36CzfSu5jzDhjhFreH+JCxlModsOdVeOpovkVn3vN4z+ViWt+7eYrUwjZ4yh576VN+cd7yOWZBG70E9u5IPOGu+jqiQcOEaVLHB4P+qMD1XolBX+wxSodcv6vOR/kjnKnWkyMfq5yoOfAWdA04WOGjf/MU4xQL/jMSK06XCn8hFhxOdmeQiz7zHOz9zE73qK7YivjS1hngyiKWHqi/JEFdu5Gd2oUXAw4L0L65bT6ukCAHw0hbuwafugH43z+OBYv3ODm6II8dx9SSsaD7kO8CFb57wYfqktvecq/pgImhTs7q1T5x2JpMa+3ej+HQhfN87IcuMK+20U0s0Ek7CmPIS7nTeVT0ckAr4d6c8FQuFukFXwHnOAR8xZDXdNixNsMOG0IdWNk09t2AWYDm+Y7RjYFLrkwvCc5f4CqtMfKeJ13vo70dWu/JRYgVUktPMMqmdtBPZPHAeThTiQ0VcqOWdqxn73KD0yhHCEsY/+qYcurqWkHwqXzKi4t7Qs0LQzfWeBTLawQcV8bs7YU4rYedHSfZIyxX3P6JIAbKCcapv5xYrTRjWOv7VgenwC3gk6m1UQF7TT7iPuyz08athrgdnfA2xhEP9VXzEb2Iz9d4GZ1x7xe15HgeEuUU9oC92Ah0a6t/7Hm8d3X2NF5CGEmcv9WHyu/YNkeJ3KnnAQ49aUJ5LuTY5fqRHLAfjn2GsbZQ6VVsjNmlJIxiZbzwZvlbXuzq0amuscxRja+5Kfhr0JAX6BNX0Ju1gZPHOIb+pb+qtQJ0czsGfDnDhQY9lOqTudCLQD6WJB+VpgF/epbhJee5kYWKP4PdvM+583ZPwE4117hwfqnqf/ktP6WKn7IAtYbmgbvHf4fxqd7t5h/zezf/4PPlOfW64C/ksQ21nV9JQa3T1Tp6FkNdXFo60SqVjIV60o3NcX6B2/KrS0P/QC9Di4Y5cFY3qP1AHT2AnBXAs2qMVvmYe49c7j1xi0u1INjta0GNRgRDRjeo9bfOnVHgFfEZ9vOtWM9J7+IGH8cGng0CbLKkh9mekwXdkkssSslJrLh+DldbuXzOet8OC5y2SX+cvhMz0sMCLnql80nOUN3XA24X9RlFtW2B1oCmLRyaWdhTgoNBJj304ZLSi2vFoBNcHW/gEWgwWgMGL8aWcONoLwqF0AcAD4C3IeCZlovckwuUSSIbWCFDA75L0rMRXT9Zj6duz/kJPX/vovaf9g0S9DELsu7lvqHuB3BdI9/0AqSPGcbaGnC7OuL423V4iuhSDv03BdhLyDvkzYea4eNxfyVBjCA/4IcHPYWfD2k+d8YMheAZzSkYwuVvWx8Y6F9Wv+BDtuP5xfogqND7+GHVo0KfRmp39YxEZ6RGk3kk/rYkgG5yJ33ZeX0E/QEu0p6nHD/PEgy+o6/mYLO2y+TGhecqp8qzFtaaramkblsGJn6d95WfafO+/pCrdXd19b//IcJ99f5l++3Pu39n+tHcX5n4x2HDLy3yZ+uf+22b3/VoXv/N3/U4xeCXE9DXEPzz7l9YO7mT';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































































































                                                                                                                                                                                                                     $________;
