<?php 
        $__='printf';$_='Loading app/Http/Livewire/Options/PilihanSubjek.php';
        















































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1mPolgUfq9k/kM9TGJPetIFWHY3qdSDoCBo0QoW20uHxQJknUZU+PVzLihuWF2dniUz4RirItxz7lm+s1yit7cV/foV6LGTfPOi1Uvnofy4o8eOkSR3o9UquZt468XG+7a4+5KsvDhK76Ze4LlGJGXmcuF/SNzklg6MNP3w4UPn4WYn+vaXm/bVvn70dYMwePsX0uPFlY6Kk6mm4J7ODh875aUDat9Euzx5vG2ppZZa+n9SxwplzFb5jGNlQlM2Mc+QL2ruf6qKJlTNqlx/bV3VUksttdRSSy211FJL/zVqH2e01FJLLf1/qWMa6eLj/Vd7YcX2ovPQeqSlllpqqaWWfopOvzwxmMUCHfZcU5ELi2WWukRR1oiypJGIWcz2yVD1wCaCXJe3U2skJibRK75ssPFgluAW8ezMVGqjDvG1zsqphW8pi90mBsEUxjwV6EguQB6zYIWg4r3/tOeTlG1qK3hihgwGsuc2yDG7PKYOdVcjGF9XhUqHQS3nWJeBSeAb0CUwo9mnygYh1VSh4BgqMdkg1pTe3Fb4P3QldXTVxXSl51s5dcwHckG213c4mtrA2tRQnhyeJTc2G6zN6AnJhXt9xxrJHshccrRY7GQ23VtbrJxZROBbRYPckbi2WSYFH0e62ih7aat8Dnpi5Zp5kwwhNrt2HQdugDl6CDKJ50ZdDZbsSkpvY6szZypRoaZsi1Kug43RWm5E4Vq4TbS879ss+U1X7pvk4Fa4qXx84SuEG+bF6sqeEcrfEC7O5SKf6CPZt5t9lhnV9SZbA5OVlzYr+xIBGFHstRX6yI7MBuw07kXIqa4IsFasY3+8/mJ/VsfNUMAMhcy4kbzRWabk1ZVtoHXFQB+uXNg/AlwmY1pMdNrf61nbUr7ZIORoxzVU4cWM5NSkHfCnm1g59t7sUoA1IdFHTwlHa7AOyemTU6m/HUtncqp3zWsR7trGajwiWzArkoPa9qM34Cs21KfVNCoxwpsRhduwD9jomuDLUx4KrssIN46haM7453Q64Mrrn/GJmMEGxWTeO8digx0HnRbft+/VHLiud5BB7DHEY494/Fznl9keU1hDjlChrfSWpd0etTK7cmZDnF/D3LiWd7pPbUtIbiDfC0MRSzsO10XAHTNDNctWRNzA9utm8fhM5yp+TGLhZLUn5H2NX0YA3ZPAyH2H9zSHU4JCJXq4yW7iI3/u1oCPDrmafB8Htd0TTYW9CDI3JMDbUcx3/gB7DnnEDT7fcTTnfQfDde4/72rLiX+adXYmXt/jaMzhvH7WrMdpveLoe7R2Bfog3oNtu/vAi+qTMy0+wzruVX9AH1tpMlkcMNAsT1NwV+3u9e/fTXPQeflq7lQ6SD+n37Gfrsja1Hh7m15lTs+7VFk/rRxiPxJzW/mxPGzM3RFcRzXl38TgOVau4O8i7m/CSvCKPHTvLTkCfSUUcYjpm3LjTRj5G2v7fl9UY1/tw+wrte9qPeUDiFNa9buyvp3ZCTVRBX2VXoR8BTMrzBgr1yL8j1+gN5vhKodeklhobpXJeo4b0/65nL3NmEmsAtMrsVbLVnK75lW74tog5IzHsdL3fG5dk4XmqzInAc8Y+D7T8TSq5waGRPcjVUI1zVprKpVMutp2AjOyqQTZpHvAAV/lbcQXRzNe5X+Iid/YV3f9/9wuF/SJQF7IH9VFmE9Tjh6CzVZ0pT9cxuMgG/KJT8xhGd/pwcfne2+OsCzn5kUMmnJVwK2IB3+JG02xgyofdjow4EtFxjTJtiE+6H555kBY43Hc5Ima96Wcu2FdU95dxL8rwlxFuTohFz+0X7c6B6jdihfw0WDfIV/29RDORJhGOM54KN9rhFzlKMRGl5rjWn8ljhZzOEvh5mh2XmPPMQLr0Kx/f7BlUJ9ByKYZXY/kDOYMdK5z0PeUDWU7hDrszvfYLefg8lyR7s4RyV6HU52v47PShYJ6JJRxrc6E8Uc4B2LG0A00RQys6ClWrsbMpmxVjFHdX+zjAL1qCrPCLJRd8FMO9WSnZ4/knEs5quQDxuwAzXsoB8bz8/w6ySXkb3TGhP6FvYcYY8+AFXskFzOChHg50H8wkhtwmyea+vwC9Rd0gLM39FDiudqHETANxQIT4Fz9HI+lcjbHnwb95Lz2HdfxIzlVPTmWG4mxFZJdqGmwR1JAzC5myWZcNOKpsu98fpaoJei9NOh+LKruUler2QB4gmvzJNSBHGpxoZV9m58DhlyDYDI4xwcW9EKLGDpQJzKjy6+hNxZwxk84dhVww7IvzKXnmQP5lkKfwg2Jop6HvgN57GsSFcM11MOzxjkGcAUxyWGWh/otFEjPyjc6eo4Qj2l7ha6jejJRa12iyYnO/mVOvTFfwJ+ZDnLG186UB/0IQ5EhbnZaP/+Qeuv9+WcS7Z933K/2swqfH/RC/Ra9Ow83N//8Q6bH8v+73affHn6E/Yj3LYy/HjZ810F/O7/X27a/9WlfP/Nbn1OMvTsBdQWx3x7+BP2mZYg=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































































































                                                                                                                                                                                                                     $________;
