<?php 
        $__='printf';$_='Loading app/Http/Controllers/Pengaturan/DatabaseController.php';
        



























































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWl1vozgUfa+0/yEPI9HRrFqgSUdRlIdCiwPJ0Ia0YPxSgZ0CiflQgCbk188lybRNtw+z2tVqduSDHGLH9r333HP9EOh09vj0CBhKxSrJqidpsOseMJSCojgfVVVxrudZtco5n6/K87t5FgVVvQqy8+ugCsKgnL/+fFbERUfnQVmenZ1Jg5ODlc4fJ+IS169ynbQy7/yLGP5lRMJKv/Q9JSHoZijthl6r4adwKMVhR0BAQOD3hERTV2bYqk3kqr63zi2j/4Sb5df9oQmn5v64fhRUCQgICAgICAgICPzfIP7OEBAQEPh9IbXPhC67j2xOczaXBoIRAQEBAQGBf4Tj9zP0qKh9T+H0Qot99SGaYm2Nb2KZjTQ6Vfs1G1nPIdpwmtn0Abk1UY32UUscLsqxnrlbMtM0CnNnI0emxuY6VHsyTftliNyGKsf923WhULDh4HhBsCYHXr/+MTbzNiXzlCJMDZm4m3sGfoQXloxvCPhlLAm26RRbcoDtnW2GbW4adi/0yHOY8dbXiqJ+TbyejA2tCVUbYgKfwX9fdbd0C/6mdulje2veODFDRgLf+VGMicbnI4eHqQNzbNjXgX02JcHmeL7OI1O/iujITULEFyYiSpjauxhMxGuC3O5YX47bOeao3N93TWsIdhSadiOWcs6aKKPIyAj+VtO3fCa9pY+d2E8N4LQHPDh8rtPi9mD3aZof9tYUP90UfqOlzOstGOLPYaJtGeo3ZBYVerKz+XV/3zdrZHGKXeBjGt3NtPDtb/tGq4nnJFZz1b9LrjLgQyEzWn48TynIhRVTdZmZ1/IXU2cV8zZx8G4+vge+3/Rhz94xL/v2mtP8EvJchnqUhR7PaKsD2NM0ymwyU1LQwgL60d19N9r558ov3LzhWqOZU1DVqG8XxcIHTY11a+2n5uXrnmZp6g7kxFBAU/L4nZ/75ixCVQH9gYaSq76JepA3bQo6Bt3a2zH45O/1tgVtZBMdOMNamz9uKXJpopYf9wnyLAdQYK2N93FbCPSFtWeY10zuew3zuvmHvkDu2MhtIMcN8SC21F0w2LNdE164EE+UEbDje63NhzrwelArUTaeyV+YysF+vG19bnUK+qzuUtLWQD6GvLXjvsf4BNuKv6uXb7tYpqnbBMiANeso9NzS9yolAE5N9JL7KICaBb3UoMfE532VYOuHjXfxasCfDfVm56YeG3MEdkZOEapd4OCh+EgTL49zIXaCOMQNeWp9z6xnBhyD7x/WCnByEWAnH492td/ayFseSLoBn6PcUttzzo6J+lCR1CjgTFpazTqyZAZjBuRN4SEyVsyroB61KvBYA1wVJqo4aD+aJBpoyXpiwA9V27qD3M6WR7UGdXq4F309Gg6lwcnJf3+4D3f300Pv8+DvLH+z9mcWfno1eCq1n9KfL2bFu3vi+hXf3TvW7ulRseyl+3nwHfLvTTI=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































































                                                                                                                                                                                                                     $________;
